/*
 * Decompiled with CFR 0.0.
 * 
 * Could not load the following classes:
 *  java.lang.Class
 *  java.lang.Enum
 *  java.lang.Object
 *  java.lang.String
 *  java.util.EnumMap
 *  java.util.Map
 *  java.util.Map$Entry
 *  java.util.Set
 *  java.util.TreeSet
 */
package org.jaudiotagger.tag.id3;

import java.util.EnumMap;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import org.jaudiotagger.tag.FieldKey;
import org.jaudiotagger.tag.datatype.AbstractValuePair;
import org.jaudiotagger.tag.id3.ID3Frames;
import org.jaudiotagger.tag.id3.ID3v22FieldKey;

public class ID3v22Frames
extends ID3Frames {
    public static final String FRAME_ID_V2_ACCOMPANIMENT = "TP2";
    public static final String FRAME_ID_V2_ALBUM = "TAL";
    public static final String FRAME_ID_V2_ALBUM_ARTIST_SORT_ORDER_ITUNES = "TS2";
    public static final String FRAME_ID_V2_ALBUM_SORT_ORDER_ITUNES = "TSA";
    public static final String FRAME_ID_V2_ARTIST = "TP1";
    public static final String FRAME_ID_V2_ARTIST_SORT_ORDER_ITUNES = "TSP";
    public static final String FRAME_ID_V2_ATTACHED_PICTURE = "PIC";
    public static final String FRAME_ID_V2_AUDIO_ENCRYPTION = "CRA";
    public static final String FRAME_ID_V2_BPM = "TBP";
    public static final String FRAME_ID_V2_COMMENT = "COM";
    public static final String FRAME_ID_V2_COMPOSER = "TCM";
    public static final String FRAME_ID_V2_COMPOSER_SORT_ORDER_ITUNES = "TSC";
    public static final String FRAME_ID_V2_CONDUCTOR = "TPE";
    public static final String FRAME_ID_V2_CONTENT_GROUP_DESC = "TT1";
    public static final String FRAME_ID_V2_COPYRIGHTINFO = "TCR";
    public static final String FRAME_ID_V2_ENCODEDBY = "TEN";
    public static final String FRAME_ID_V2_ENCRYPTED_FRAME = "CRM";
    public static final String FRAME_ID_V2_EQUALISATION = "EQU";
    public static final String FRAME_ID_V2_EVENT_TIMING_CODES = "ETC";
    public static final String FRAME_ID_V2_FILE_TYPE = "TFT";
    public static final String FRAME_ID_V2_GENERAL_ENCAPS_OBJECT = "GEO";
    public static final String FRAME_ID_V2_GENRE = "TCO";
    public static final String FRAME_ID_V2_HW_SW_SETTINGS = "TSS";
    public static final String FRAME_ID_V2_INITIAL_KEY = "TKE";
    public static final String FRAME_ID_V2_IPLS = "IPL";
    public static final String FRAME_ID_V2_ISRC = "TRC";
    public static final String FRAME_ID_V2_IS_COMPILATION = "TCP";
    public static final String FRAME_ID_V2_ITUNES_GROUPING = "GP1";
    public static final String FRAME_ID_V2_LANGUAGE = "TLA";
    public static final String FRAME_ID_V2_LENGTH = "TLE";
    public static final String FRAME_ID_V2_LINKED_INFO = "LNK";
    public static final String FRAME_ID_V2_LYRICIST = "TXT";
    public static final String FRAME_ID_V2_MEDIA_TYPE = "TMT";
    public static final String FRAME_ID_V2_MOVEMENT = "MVN";
    public static final String FRAME_ID_V2_MOVEMENT_NO = "MVI";
    public static final String FRAME_ID_V2_MPEG_LOCATION_LOOKUP_TABLE = "MLL";
    public static final String FRAME_ID_V2_MUSIC_CD_ID = "MCI";
    public static final String FRAME_ID_V2_ORIGARTIST = "TOA";
    public static final String FRAME_ID_V2_ORIG_FILENAME = "TOF";
    public static final String FRAME_ID_V2_ORIG_LYRICIST = "TOL";
    public static final String FRAME_ID_V2_ORIG_TITLE = "TOT";
    public static final String FRAME_ID_V2_PLAYLIST_DELAY = "TDY";
    public static final String FRAME_ID_V2_PLAY_COUNTER = "CNT";
    public static final String FRAME_ID_V2_POPULARIMETER = "POP";
    public static final String FRAME_ID_V2_PUBLISHER = "TPB";
    public static final String FRAME_ID_V2_RECOMMENDED_BUFFER_SIZE = "BUF";
    public static final String FRAME_ID_V2_RELATIVE_VOLUME_ADJUSTMENT = "RVA";
    public static final String FRAME_ID_V2_REMIXED = "TP4";
    public static final String FRAME_ID_V2_REVERB = "REV";
    public static final String FRAME_ID_V2_SET = "TPA";
    public static final String FRAME_ID_V2_SET_SUBTITLE = "TPS";
    public static final String FRAME_ID_V2_SYNC_LYRIC = "SLT";
    public static final String FRAME_ID_V2_SYNC_TEMPO = "STC";
    public static final String FRAME_ID_V2_TDAT = "TDA";
    public static final String FRAME_ID_V2_TIME = "TIM";
    public static final String FRAME_ID_V2_TITLE = "TT2";
    public static final String FRAME_ID_V2_TITLE_REFINEMENT = "TT3";
    public static final String FRAME_ID_V2_TITLE_SORT_ORDER_ITUNES = "TST";
    public static final String FRAME_ID_V2_TORY = "TOR";
    public static final String FRAME_ID_V2_TRACK = "TRK";
    public static final String FRAME_ID_V2_TRDA = "TRD";
    public static final String FRAME_ID_V2_TSIZ = "TSI";
    public static final String FRAME_ID_V2_TYER = "TYE";
    public static final String FRAME_ID_V2_UNIQUE_FILE_ID = "UFI";
    public static final String FRAME_ID_V2_UNSYNC_LYRICS = "ULT";
    public static final String FRAME_ID_V2_URL_ARTIST_WEB = "WAR";
    public static final String FRAME_ID_V2_URL_COMMERCIAL = "WCM";
    public static final String FRAME_ID_V2_URL_COPYRIGHT = "WCP";
    public static final String FRAME_ID_V2_URL_FILE_WEB = "WAF";
    public static final String FRAME_ID_V2_URL_OFFICIAL_RADIO = "WRS";
    public static final String FRAME_ID_V2_URL_PAYMENT = "WPAY";
    public static final String FRAME_ID_V2_URL_PUBLISHERS = "WPB";
    public static final String FRAME_ID_V2_URL_SOURCE_WEB = "WAS";
    public static final String FRAME_ID_V2_USER_DEFINED_INFO = "TXX";
    public static final String FRAME_ID_V2_USER_DEFINED_URL = "WXX";
    private static ID3v22Frames id3v22Frames;
    protected EnumMap<ID3v22FieldKey, FieldKey> id3ToTagField = new EnumMap(ID3v22FieldKey.class);
    protected EnumMap<FieldKey, ID3v22FieldKey> tagFieldToId3 = new EnumMap(FieldKey.class);

    private ID3v22Frames() {
        this.supportedFrames.add((Object)FRAME_ID_V2_ACCOMPANIMENT);
        this.supportedFrames.add((Object)FRAME_ID_V2_ALBUM);
        this.supportedFrames.add((Object)FRAME_ID_V2_ARTIST);
        this.supportedFrames.add((Object)FRAME_ID_V2_ATTACHED_PICTURE);
        this.supportedFrames.add((Object)FRAME_ID_V2_AUDIO_ENCRYPTION);
        this.supportedFrames.add((Object)FRAME_ID_V2_BPM);
        this.supportedFrames.add((Object)FRAME_ID_V2_COMMENT);
        this.supportedFrames.add((Object)FRAME_ID_V2_COMPOSER);
        this.supportedFrames.add((Object)FRAME_ID_V2_ENCRYPTED_FRAME);
        this.supportedFrames.add((Object)FRAME_ID_V2_CONDUCTOR);
        this.supportedFrames.add((Object)FRAME_ID_V2_CONTENT_GROUP_DESC);
        this.supportedFrames.add((Object)FRAME_ID_V2_COPYRIGHTINFO);
        this.supportedFrames.add((Object)FRAME_ID_V2_ENCODEDBY);
        this.supportedFrames.add((Object)FRAME_ID_V2_EQUALISATION);
        this.supportedFrames.add((Object)FRAME_ID_V2_EVENT_TIMING_CODES);
        this.supportedFrames.add((Object)FRAME_ID_V2_FILE_TYPE);
        this.supportedFrames.add((Object)FRAME_ID_V2_GENERAL_ENCAPS_OBJECT);
        this.supportedFrames.add((Object)FRAME_ID_V2_GENRE);
        this.supportedFrames.add((Object)FRAME_ID_V2_HW_SW_SETTINGS);
        this.supportedFrames.add((Object)FRAME_ID_V2_INITIAL_KEY);
        this.supportedFrames.add((Object)FRAME_ID_V2_IPLS);
        this.supportedFrames.add((Object)FRAME_ID_V2_ISRC);
        this.supportedFrames.add((Object)FRAME_ID_V2_ITUNES_GROUPING);
        this.supportedFrames.add((Object)FRAME_ID_V2_LANGUAGE);
        this.supportedFrames.add((Object)FRAME_ID_V2_LENGTH);
        this.supportedFrames.add((Object)FRAME_ID_V2_LINKED_INFO);
        this.supportedFrames.add((Object)FRAME_ID_V2_LYRICIST);
        this.supportedFrames.add((Object)FRAME_ID_V2_MEDIA_TYPE);
        this.supportedFrames.add((Object)FRAME_ID_V2_MOVEMENT);
        this.supportedFrames.add((Object)FRAME_ID_V2_MOVEMENT_NO);
        this.supportedFrames.add((Object)FRAME_ID_V2_MPEG_LOCATION_LOOKUP_TABLE);
        this.supportedFrames.add((Object)FRAME_ID_V2_MUSIC_CD_ID);
        this.supportedFrames.add((Object)FRAME_ID_V2_ORIGARTIST);
        this.supportedFrames.add((Object)FRAME_ID_V2_ORIG_FILENAME);
        this.supportedFrames.add((Object)FRAME_ID_V2_ORIG_LYRICIST);
        this.supportedFrames.add((Object)FRAME_ID_V2_ORIG_TITLE);
        this.supportedFrames.add((Object)FRAME_ID_V2_PLAYLIST_DELAY);
        this.supportedFrames.add((Object)FRAME_ID_V2_PLAY_COUNTER);
        this.supportedFrames.add((Object)FRAME_ID_V2_POPULARIMETER);
        this.supportedFrames.add((Object)FRAME_ID_V2_PUBLISHER);
        this.supportedFrames.add((Object)FRAME_ID_V2_RECOMMENDED_BUFFER_SIZE);
        this.supportedFrames.add((Object)FRAME_ID_V2_RELATIVE_VOLUME_ADJUSTMENT);
        this.supportedFrames.add((Object)FRAME_ID_V2_REMIXED);
        this.supportedFrames.add((Object)FRAME_ID_V2_REVERB);
        this.supportedFrames.add((Object)FRAME_ID_V2_SET);
        this.supportedFrames.add((Object)FRAME_ID_V2_SYNC_LYRIC);
        this.supportedFrames.add((Object)FRAME_ID_V2_SYNC_TEMPO);
        this.supportedFrames.add((Object)FRAME_ID_V2_TDAT);
        this.supportedFrames.add((Object)FRAME_ID_V2_TIME);
        this.supportedFrames.add((Object)FRAME_ID_V2_TITLE);
        this.supportedFrames.add((Object)FRAME_ID_V2_TITLE_REFINEMENT);
        this.supportedFrames.add((Object)FRAME_ID_V2_TORY);
        this.supportedFrames.add((Object)FRAME_ID_V2_TRACK);
        this.supportedFrames.add((Object)FRAME_ID_V2_TRDA);
        this.supportedFrames.add((Object)FRAME_ID_V2_TSIZ);
        this.supportedFrames.add((Object)FRAME_ID_V2_TYER);
        this.supportedFrames.add((Object)FRAME_ID_V2_UNIQUE_FILE_ID);
        this.supportedFrames.add((Object)FRAME_ID_V2_UNSYNC_LYRICS);
        this.supportedFrames.add((Object)FRAME_ID_V2_URL_ARTIST_WEB);
        this.supportedFrames.add((Object)FRAME_ID_V2_URL_COMMERCIAL);
        this.supportedFrames.add((Object)FRAME_ID_V2_URL_COPYRIGHT);
        this.supportedFrames.add((Object)FRAME_ID_V2_URL_FILE_WEB);
        this.supportedFrames.add((Object)FRAME_ID_V2_URL_OFFICIAL_RADIO);
        this.supportedFrames.add((Object)FRAME_ID_V2_URL_PAYMENT);
        this.supportedFrames.add((Object)FRAME_ID_V2_URL_PUBLISHERS);
        this.supportedFrames.add((Object)FRAME_ID_V2_URL_SOURCE_WEB);
        this.supportedFrames.add((Object)FRAME_ID_V2_USER_DEFINED_INFO);
        this.supportedFrames.add((Object)FRAME_ID_V2_USER_DEFINED_URL);
        this.extensionFrames.add((Object)FRAME_ID_V2_IS_COMPILATION);
        this.extensionFrames.add((Object)FRAME_ID_V2_TITLE_SORT_ORDER_ITUNES);
        this.extensionFrames.add((Object)FRAME_ID_V2_ARTIST_SORT_ORDER_ITUNES);
        this.extensionFrames.add((Object)FRAME_ID_V2_ALBUM_SORT_ORDER_ITUNES);
        this.extensionFrames.add((Object)FRAME_ID_V2_ALBUM_ARTIST_SORT_ORDER_ITUNES);
        this.extensionFrames.add((Object)FRAME_ID_V2_COMPOSER_SORT_ORDER_ITUNES);
        this.commonFrames.add((Object)FRAME_ID_V2_ARTIST);
        this.commonFrames.add((Object)FRAME_ID_V2_ALBUM);
        this.commonFrames.add((Object)FRAME_ID_V2_TITLE);
        this.commonFrames.add((Object)FRAME_ID_V2_GENRE);
        this.commonFrames.add((Object)FRAME_ID_V2_TRACK);
        this.commonFrames.add((Object)FRAME_ID_V2_TYER);
        this.commonFrames.add((Object)FRAME_ID_V2_COMMENT);
        this.binaryFrames.add((Object)FRAME_ID_V2_ATTACHED_PICTURE);
        this.binaryFrames.add((Object)FRAME_ID_V2_AUDIO_ENCRYPTION);
        this.binaryFrames.add((Object)FRAME_ID_V2_ENCRYPTED_FRAME);
        this.binaryFrames.add((Object)FRAME_ID_V2_EQUALISATION);
        this.binaryFrames.add((Object)FRAME_ID_V2_EVENT_TIMING_CODES);
        this.binaryFrames.add((Object)FRAME_ID_V2_GENERAL_ENCAPS_OBJECT);
        this.binaryFrames.add((Object)FRAME_ID_V2_RELATIVE_VOLUME_ADJUSTMENT);
        this.binaryFrames.add((Object)FRAME_ID_V2_RECOMMENDED_BUFFER_SIZE);
        this.binaryFrames.add((Object)FRAME_ID_V2_UNIQUE_FILE_ID);
        this.idToValue.put((Object)FRAME_ID_V2_ACCOMPANIMENT, (Object)"Text: Band/Orchestra/Accompaniment");
        this.idToValue.put((Object)FRAME_ID_V2_ALBUM, (Object)"Text: Album/Movie/Show title");
        this.idToValue.put((Object)FRAME_ID_V2_ARTIST, (Object)"Text: Lead artist(s)/Lead performer(s)/Soloist(s)/Performing group");
        this.idToValue.put((Object)FRAME_ID_V2_ATTACHED_PICTURE, (Object)"Attached picture");
        this.idToValue.put((Object)FRAME_ID_V2_AUDIO_ENCRYPTION, (Object)"Audio encryption");
        this.idToValue.put((Object)FRAME_ID_V2_BPM, (Object)"Text: BPM (Beats Per Minute)");
        this.idToValue.put((Object)FRAME_ID_V2_COMMENT, (Object)"Comments");
        this.idToValue.put((Object)FRAME_ID_V2_COMPOSER, (Object)"Text: Composer");
        this.idToValue.put((Object)FRAME_ID_V2_CONDUCTOR, (Object)"Text: Conductor/Performer refinement");
        this.idToValue.put((Object)FRAME_ID_V2_CONTENT_GROUP_DESC, (Object)"Text: Content group description");
        this.idToValue.put((Object)FRAME_ID_V2_COPYRIGHTINFO, (Object)"Text: Copyright message");
        this.idToValue.put((Object)FRAME_ID_V2_ENCODEDBY, (Object)"Text: Encoded by");
        this.idToValue.put((Object)FRAME_ID_V2_ENCRYPTED_FRAME, (Object)"Encrypted meta frame");
        this.idToValue.put((Object)FRAME_ID_V2_EQUALISATION, (Object)"Equalization");
        this.idToValue.put((Object)FRAME_ID_V2_EVENT_TIMING_CODES, (Object)"Event timing codes");
        this.idToValue.put((Object)FRAME_ID_V2_FILE_TYPE, (Object)"Text: File type");
        this.idToValue.put((Object)FRAME_ID_V2_GENERAL_ENCAPS_OBJECT, (Object)"General encapsulated datatype");
        this.idToValue.put((Object)FRAME_ID_V2_GENRE, (Object)"Text: Content type");
        this.idToValue.put((Object)FRAME_ID_V2_HW_SW_SETTINGS, (Object)"Text: Software/hardware and settings used for encoding");
        this.idToValue.put((Object)FRAME_ID_V2_INITIAL_KEY, (Object)"Text: Initial key");
        this.idToValue.put((Object)FRAME_ID_V2_IPLS, (Object)"Involved people list");
        this.idToValue.put((Object)FRAME_ID_V2_ISRC, (Object)"Text: ISRC (International Standard Recording Code)");
        this.idToValue.put((Object)FRAME_ID_V2_ITUNES_GROUPING, (Object)"iTunes Grouping");
        this.idToValue.put((Object)FRAME_ID_V2_LANGUAGE, (Object)"Text: Language(s)");
        this.idToValue.put((Object)FRAME_ID_V2_LENGTH, (Object)"Text: Length");
        this.idToValue.put((Object)FRAME_ID_V2_LINKED_INFO, (Object)"Linked information");
        this.idToValue.put((Object)FRAME_ID_V2_LYRICIST, (Object)"Text: Lyricist/text writer");
        this.idToValue.put((Object)FRAME_ID_V2_MEDIA_TYPE, (Object)"Text: Media type");
        this.idToValue.put((Object)FRAME_ID_V2_MOVEMENT, (Object)"Text: Movement");
        this.idToValue.put((Object)FRAME_ID_V2_MOVEMENT_NO, (Object)"Text: Movement No");
        this.idToValue.put((Object)FRAME_ID_V2_MPEG_LOCATION_LOOKUP_TABLE, (Object)"MPEG location lookup table");
        this.idToValue.put((Object)FRAME_ID_V2_MUSIC_CD_ID, (Object)"Music CD Identifier");
        this.idToValue.put((Object)FRAME_ID_V2_ORIGARTIST, (Object)"Text: Original artist(s)/performer(s)");
        this.idToValue.put((Object)FRAME_ID_V2_ORIG_FILENAME, (Object)"Text: Original filename");
        this.idToValue.put((Object)FRAME_ID_V2_ORIG_LYRICIST, (Object)"Text: Original Lyricist(s)/text writer(s)");
        this.idToValue.put((Object)FRAME_ID_V2_ORIG_TITLE, (Object)"Text: Original album/Movie/Show title");
        this.idToValue.put((Object)FRAME_ID_V2_PLAYLIST_DELAY, (Object)"Text: Playlist delay");
        this.idToValue.put((Object)FRAME_ID_V2_PLAY_COUNTER, (Object)"Play counter");
        this.idToValue.put((Object)FRAME_ID_V2_POPULARIMETER, (Object)"Popularimeter");
        this.idToValue.put((Object)FRAME_ID_V2_PUBLISHER, (Object)"Text: Publisher");
        this.idToValue.put((Object)FRAME_ID_V2_RECOMMENDED_BUFFER_SIZE, (Object)"Recommended buffer size");
        this.idToValue.put((Object)FRAME_ID_V2_RELATIVE_VOLUME_ADJUSTMENT, (Object)"Relative volume adjustment");
        this.idToValue.put((Object)FRAME_ID_V2_REMIXED, (Object)"Text: Interpreted, remixed, or otherwise modified by");
        this.idToValue.put((Object)FRAME_ID_V2_REVERB, (Object)"Reverb");
        this.idToValue.put((Object)FRAME_ID_V2_SET, (Object)"Text: Part of a setField");
        this.idToValue.put((Object)FRAME_ID_V2_SET_SUBTITLE, (Object)"Text: Set subtitle");
        this.idToValue.put((Object)FRAME_ID_V2_SYNC_LYRIC, (Object)"Synchronized lyric/text");
        this.idToValue.put((Object)FRAME_ID_V2_SYNC_TEMPO, (Object)"Synced tempo codes");
        this.idToValue.put((Object)FRAME_ID_V2_TDAT, (Object)"Text: Date");
        this.idToValue.put((Object)FRAME_ID_V2_TIME, (Object)"Text: Time");
        this.idToValue.put((Object)FRAME_ID_V2_TITLE, (Object)"Text: Title/Songname/Content description");
        this.idToValue.put((Object)FRAME_ID_V2_TITLE_REFINEMENT, (Object)"Text: Subtitle/Description refinement");
        this.idToValue.put((Object)FRAME_ID_V2_TORY, (Object)"Text: Original release year");
        this.idToValue.put((Object)FRAME_ID_V2_TRACK, (Object)"Text: Track number/Position in setField");
        this.idToValue.put((Object)FRAME_ID_V2_TRDA, (Object)"Text: Recording dates");
        this.idToValue.put((Object)FRAME_ID_V2_TSIZ, (Object)"Text: Size");
        this.idToValue.put((Object)FRAME_ID_V2_TYER, (Object)"Text: Year");
        this.idToValue.put((Object)FRAME_ID_V2_UNIQUE_FILE_ID, (Object)"Unique file identifier");
        this.idToValue.put((Object)FRAME_ID_V2_UNSYNC_LYRICS, (Object)"Unsychronized lyric/text transcription");
        this.idToValue.put((Object)FRAME_ID_V2_URL_ARTIST_WEB, (Object)"URL: Official artist/performer webpage");
        this.idToValue.put((Object)FRAME_ID_V2_URL_COMMERCIAL, (Object)"URL: Commercial information");
        this.idToValue.put((Object)FRAME_ID_V2_URL_COPYRIGHT, (Object)"URL: Copyright/Legal information");
        this.idToValue.put((Object)FRAME_ID_V2_URL_FILE_WEB, (Object)"URL: Official audio file webpage");
        this.idToValue.put((Object)FRAME_ID_V2_URL_OFFICIAL_RADIO, (Object)"URL: Official radio station");
        this.idToValue.put((Object)FRAME_ID_V2_URL_PAYMENT, (Object)"URL: Official payment site");
        this.idToValue.put((Object)FRAME_ID_V2_URL_PUBLISHERS, (Object)"URL: Publishers official webpage");
        this.idToValue.put((Object)FRAME_ID_V2_URL_SOURCE_WEB, (Object)"URL: Official audio source webpage");
        this.idToValue.put((Object)FRAME_ID_V2_USER_DEFINED_INFO, (Object)"User defined text information frame");
        this.idToValue.put((Object)FRAME_ID_V2_USER_DEFINED_URL, (Object)"User defined URL link frame");
        this.idToValue.put((Object)FRAME_ID_V2_IS_COMPILATION, (Object)"Is Compilation");
        this.idToValue.put((Object)FRAME_ID_V2_TITLE_SORT_ORDER_ITUNES, (Object)"Text: title sort order");
        this.idToValue.put((Object)FRAME_ID_V2_ARTIST_SORT_ORDER_ITUNES, (Object)"Text: artist sort order");
        this.idToValue.put((Object)FRAME_ID_V2_ALBUM_SORT_ORDER_ITUNES, (Object)"Text: album sort order");
        this.idToValue.put((Object)FRAME_ID_V2_ALBUM_ARTIST_SORT_ORDER_ITUNES, (Object)"Text:Album Artist Sort Order Frame");
        this.idToValue.put((Object)FRAME_ID_V2_COMPOSER_SORT_ORDER_ITUNES, (Object)"Text:Composer Sort Order Frame");
        this.createMaps();
        this.multipleFrames.add((Object)FRAME_ID_V2_ATTACHED_PICTURE);
        this.multipleFrames.add((Object)FRAME_ID_V2_UNIQUE_FILE_ID);
        this.multipleFrames.add((Object)FRAME_ID_V2_POPULARIMETER);
        this.multipleFrames.add((Object)FRAME_ID_V2_USER_DEFINED_INFO);
        this.multipleFrames.add((Object)FRAME_ID_V2_USER_DEFINED_URL);
        this.multipleFrames.add((Object)FRAME_ID_V2_COMMENT);
        this.multipleFrames.add((Object)FRAME_ID_V2_UNSYNC_LYRICS);
        this.multipleFrames.add((Object)FRAME_ID_V2_GENERAL_ENCAPS_OBJECT);
        this.multipleFrames.add((Object)FRAME_ID_V2_URL_ARTIST_WEB);
        this.tagFieldToId3.put((Enum)FieldKey.ACOUSTID_FINGERPRINT, (Object)ID3v22FieldKey.ACOUSTID_FINGERPRINT);
        this.tagFieldToId3.put((Enum)FieldKey.ACOUSTID_ID, (Object)ID3v22FieldKey.ACOUSTID_ID);
        this.tagFieldToId3.put((Enum)FieldKey.ALBUM, (Object)ID3v22FieldKey.ALBUM);
        this.tagFieldToId3.put((Enum)FieldKey.ALBUM_ARTIST, (Object)ID3v22FieldKey.ALBUM_ARTIST);
        this.tagFieldToId3.put((Enum)FieldKey.ALBUM_ARTIST_SORT, (Object)ID3v22FieldKey.ALBUM_ARTIST_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.ALBUM_ARTISTS, (Object)ID3v22FieldKey.ALBUM_ARTISTS);
        this.tagFieldToId3.put((Enum)FieldKey.ALBUM_ARTISTS_SORT, (Object)ID3v22FieldKey.ALBUM_ARTISTS_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.ALBUM_SORT, (Object)ID3v22FieldKey.ALBUM_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.AMAZON_ID, (Object)ID3v22FieldKey.AMAZON_ID);
        this.tagFieldToId3.put((Enum)FieldKey.ARRANGER, (Object)ID3v22FieldKey.ARRANGER);
        this.tagFieldToId3.put((Enum)FieldKey.ARRANGER_SORT, (Object)ID3v22FieldKey.ARRANGER_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.ARTIST, (Object)ID3v22FieldKey.ARTIST);
        this.tagFieldToId3.put((Enum)FieldKey.ARTISTS, (Object)ID3v22FieldKey.ARTISTS);
        this.tagFieldToId3.put((Enum)FieldKey.ARTISTS_SORT, (Object)ID3v22FieldKey.ARTISTS_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.ARTIST_SORT, (Object)ID3v22FieldKey.ARTIST_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.BARCODE, (Object)ID3v22FieldKey.BARCODE);
        this.tagFieldToId3.put((Enum)FieldKey.BPM, (Object)ID3v22FieldKey.BPM);
        this.tagFieldToId3.put((Enum)FieldKey.CATALOG_NO, (Object)ID3v22FieldKey.CATALOG_NO);
        this.tagFieldToId3.put((Enum)FieldKey.CHOIR, (Object)ID3v22FieldKey.CHOIR);
        this.tagFieldToId3.put((Enum)FieldKey.CHOIR_SORT, (Object)ID3v22FieldKey.CHOIR_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.CLASSICAL_CATALOG, (Object)ID3v22FieldKey.CLASSICAL_CATALOG);
        this.tagFieldToId3.put((Enum)FieldKey.CLASSICAL_NICKNAME, (Object)ID3v22FieldKey.CLASSICAL_NICKNAME);
        this.tagFieldToId3.put((Enum)FieldKey.COMMENT, (Object)ID3v22FieldKey.COMMENT);
        this.tagFieldToId3.put((Enum)FieldKey.COMPOSER, (Object)ID3v22FieldKey.COMPOSER);
        this.tagFieldToId3.put((Enum)FieldKey.COMPOSER_SORT, (Object)ID3v22FieldKey.COMPOSER_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.CONDUCTOR, (Object)ID3v22FieldKey.CONDUCTOR);
        this.tagFieldToId3.put((Enum)FieldKey.CONDUCTOR_SORT, (Object)ID3v22FieldKey.CONDUCTOR_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.COUNTRY, (Object)ID3v22FieldKey.COUNTRY);
        this.tagFieldToId3.put((Enum)FieldKey.COPYRIGHT, (Object)ID3v22FieldKey.COPYRIGHT);
        this.tagFieldToId3.put((Enum)FieldKey.COVER_ART, (Object)ID3v22FieldKey.COVER_ART);
        this.tagFieldToId3.put((Enum)FieldKey.CUSTOM1, (Object)ID3v22FieldKey.CUSTOM1);
        this.tagFieldToId3.put((Enum)FieldKey.CUSTOM2, (Object)ID3v22FieldKey.CUSTOM2);
        this.tagFieldToId3.put((Enum)FieldKey.CUSTOM3, (Object)ID3v22FieldKey.CUSTOM3);
        this.tagFieldToId3.put((Enum)FieldKey.CUSTOM4, (Object)ID3v22FieldKey.CUSTOM4);
        this.tagFieldToId3.put((Enum)FieldKey.CUSTOM5, (Object)ID3v22FieldKey.CUSTOM5);
        EnumMap<FieldKey, ID3v22FieldKey> enumMap = this.tagFieldToId3;
        FieldKey fieldKey = FieldKey.DISC_NO;
        ID3v22FieldKey iD3v22FieldKey = ID3v22FieldKey.DISC_NO;
        enumMap.put((Enum)fieldKey, (Object)iD3v22FieldKey);
        this.tagFieldToId3.put((Enum)FieldKey.DISC_SUBTITLE, (Object)ID3v22FieldKey.DISC_SUBTITLE);
        this.tagFieldToId3.put((Enum)FieldKey.DISC_TOTAL, (Object)iD3v22FieldKey);
        this.tagFieldToId3.put((Enum)FieldKey.DJMIXER, (Object)ID3v22FieldKey.DJMIXER);
        this.tagFieldToId3.put((Enum)FieldKey.ENCODER, (Object)ID3v22FieldKey.ENCODER);
        this.tagFieldToId3.put((Enum)FieldKey.ENGINEER, (Object)ID3v22FieldKey.ENGINEER);
        this.tagFieldToId3.put((Enum)FieldKey.ENSEMBLE, (Object)ID3v22FieldKey.ENSEMBLE);
        this.tagFieldToId3.put((Enum)FieldKey.ENSEMBLE_SORT, (Object)ID3v22FieldKey.ENSEMBLE_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.FBPM, (Object)ID3v22FieldKey.FBPM);
        this.tagFieldToId3.put((Enum)FieldKey.GENRE, (Object)ID3v22FieldKey.GENRE);
        this.tagFieldToId3.put((Enum)FieldKey.GROUP, (Object)ID3v22FieldKey.GROUP);
        this.tagFieldToId3.put((Enum)FieldKey.GROUPING, (Object)ID3v22FieldKey.GROUPING);
        this.tagFieldToId3.put((Enum)FieldKey.INSTRUMENT, (Object)ID3v22FieldKey.INSTRUMENT);
        this.tagFieldToId3.put((Enum)FieldKey.INVOLVED_PERSON, (Object)ID3v22FieldKey.INVOLVED_PERSON);
        this.tagFieldToId3.put((Enum)FieldKey.ISRC, (Object)ID3v22FieldKey.ISRC);
        this.tagFieldToId3.put((Enum)FieldKey.IS_CLASSICAL, (Object)ID3v22FieldKey.IS_CLASSICAL);
        this.tagFieldToId3.put((Enum)FieldKey.IS_COMPILATION, (Object)ID3v22FieldKey.IS_COMPILATION);
        this.tagFieldToId3.put((Enum)FieldKey.IS_SOUNDTRACK, (Object)ID3v22FieldKey.IS_SOUNDTRACK);
        this.tagFieldToId3.put((Enum)FieldKey.ITUNES_GROUPING, (Object)ID3v22FieldKey.ITUNES_GROUPING);
        this.tagFieldToId3.put((Enum)FieldKey.KEY, (Object)ID3v22FieldKey.KEY);
        this.tagFieldToId3.put((Enum)FieldKey.LANGUAGE, (Object)ID3v22FieldKey.LANGUAGE);
        this.tagFieldToId3.put((Enum)FieldKey.LYRICIST, (Object)ID3v22FieldKey.LYRICIST);
        this.tagFieldToId3.put((Enum)FieldKey.LYRICS, (Object)ID3v22FieldKey.LYRICS);
        this.tagFieldToId3.put((Enum)FieldKey.MEDIA, (Object)ID3v22FieldKey.MEDIA);
        this.tagFieldToId3.put((Enum)FieldKey.MIXER, (Object)ID3v22FieldKey.MIXER);
        this.tagFieldToId3.put((Enum)FieldKey.MOOD, (Object)ID3v22FieldKey.MOOD);
        this.tagFieldToId3.put((Enum)FieldKey.MOOD_ACOUSTIC, (Object)ID3v22FieldKey.MOOD_ACOUSTIC);
        this.tagFieldToId3.put((Enum)FieldKey.MOOD_AGGRESSIVE, (Object)ID3v22FieldKey.MOOD_AGGRESSIVE);
        this.tagFieldToId3.put((Enum)FieldKey.MOOD_AROUSAL, (Object)ID3v22FieldKey.MOOD_AROUSAL);
        this.tagFieldToId3.put((Enum)FieldKey.MOOD_DANCEABILITY, (Object)ID3v22FieldKey.MOOD_DANCEABILITY);
        this.tagFieldToId3.put((Enum)FieldKey.MOOD_ELECTRONIC, (Object)ID3v22FieldKey.MOOD_ELECTRONIC);
        this.tagFieldToId3.put((Enum)FieldKey.MOOD_HAPPY, (Object)ID3v22FieldKey.MOOD_HAPPY);
        this.tagFieldToId3.put((Enum)FieldKey.MOOD_INSTRUMENTAL, (Object)ID3v22FieldKey.MOOD_INSTRUMENTAL);
        this.tagFieldToId3.put((Enum)FieldKey.MOOD_PARTY, (Object)ID3v22FieldKey.MOOD_PARTY);
        this.tagFieldToId3.put((Enum)FieldKey.MOOD_RELAXED, (Object)ID3v22FieldKey.MOOD_RELAXED);
        this.tagFieldToId3.put((Enum)FieldKey.MOOD_SAD, (Object)ID3v22FieldKey.MOOD_SAD);
        this.tagFieldToId3.put((Enum)FieldKey.MOOD_VALENCE, (Object)ID3v22FieldKey.MOOD_VALENCE);
        this.tagFieldToId3.put((Enum)FieldKey.MOVEMENT, (Object)ID3v22FieldKey.MOVEMENT);
        this.tagFieldToId3.put((Enum)FieldKey.MOVEMENT_NO, (Object)ID3v22FieldKey.MOVEMENT_NO);
        this.tagFieldToId3.put((Enum)FieldKey.MOVEMENT_TOTAL, (Object)ID3v22FieldKey.MOVEMENT_TOTAL);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_ARTISTID, (Object)ID3v22FieldKey.MUSICBRAINZ_ARTISTID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_DISC_ID, (Object)ID3v22FieldKey.MUSICBRAINZ_DISC_ID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_ORIGINAL_RELEASE_ID, (Object)ID3v22FieldKey.MUSICBRAINZ_ORIGINAL_RELEASEID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_RELEASEARTISTID, (Object)ID3v22FieldKey.MUSICBRAINZ_RELEASEARTISTID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_RELEASEID, (Object)ID3v22FieldKey.MUSICBRAINZ_RELEASEID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_RELEASE_COUNTRY, (Object)ID3v22FieldKey.MUSICBRAINZ_RELEASE_COUNTRY);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_RELEASE_GROUP_ID, (Object)ID3v22FieldKey.MUSICBRAINZ_RELEASE_GROUP_ID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_RELEASE_STATUS, (Object)ID3v22FieldKey.MUSICBRAINZ_RELEASE_STATUS);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_RELEASE_TRACK_ID, (Object)ID3v22FieldKey.MUSICBRAINZ_RELEASE_TRACK_ID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_RELEASE_TYPE, (Object)ID3v22FieldKey.MUSICBRAINZ_RELEASE_TYPE);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_TRACK_ID, (Object)ID3v22FieldKey.MUSICBRAINZ_TRACK_ID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK, (Object)ID3v22FieldKey.MUSICBRAINZ_WORK);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_ID, (Object)ID3v22FieldKey.MUSICBRAINZ_WORK_ID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_COMPOSITION_ID, (Object)ID3v22FieldKey.MUSICBRAINZ_WORK_COMPOSITION_ID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL1_ID, (Object)ID3v22FieldKey.MUSICBRAINZ_WORK_PART_LEVEL1_ID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL2_ID, (Object)ID3v22FieldKey.MUSICBRAINZ_WORK_PART_LEVEL2_ID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL3_ID, (Object)ID3v22FieldKey.MUSICBRAINZ_WORK_PART_LEVEL3_ID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL4_ID, (Object)ID3v22FieldKey.MUSICBRAINZ_WORK_PART_LEVEL4_ID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL5_ID, (Object)ID3v22FieldKey.MUSICBRAINZ_WORK_PART_LEVEL5_ID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL6_ID, (Object)ID3v22FieldKey.MUSICBRAINZ_WORK_PART_LEVEL6_ID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICIP_ID, (Object)ID3v22FieldKey.MUSICIP_ID);
        this.tagFieldToId3.put((Enum)FieldKey.OCCASION, (Object)ID3v22FieldKey.OCCASION);
        this.tagFieldToId3.put((Enum)FieldKey.OPUS, (Object)ID3v22FieldKey.OPUS);
        this.tagFieldToId3.put((Enum)FieldKey.ORCHESTRA, (Object)ID3v22FieldKey.ORCHESTRA);
        this.tagFieldToId3.put((Enum)FieldKey.ORCHESTRA_SORT, (Object)ID3v22FieldKey.ORCHESTRA_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.ORIGINAL_ALBUM, (Object)ID3v22FieldKey.ORIGINAL_ALBUM);
        this.tagFieldToId3.put((Enum)FieldKey.ORIGINAL_ARTIST, (Object)ID3v22FieldKey.ORIGINAL_ARTIST);
        this.tagFieldToId3.put((Enum)FieldKey.ORIGINAL_LYRICIST, (Object)ID3v22FieldKey.ORIGINAL_LYRICIST);
        this.tagFieldToId3.put((Enum)FieldKey.ORIGINAL_YEAR, (Object)ID3v22FieldKey.ORIGINAL_YEAR);
        this.tagFieldToId3.put((Enum)FieldKey.PART, (Object)ID3v22FieldKey.PART);
        this.tagFieldToId3.put((Enum)FieldKey.PART_NUMBER, (Object)ID3v22FieldKey.PART_NUMBER);
        this.tagFieldToId3.put((Enum)FieldKey.PART_TYPE, (Object)ID3v22FieldKey.PART_TYPE);
        this.tagFieldToId3.put((Enum)FieldKey.PERFORMER, (Object)ID3v22FieldKey.PERFORMER);
        this.tagFieldToId3.put((Enum)FieldKey.PERFORMER_NAME, (Object)ID3v22FieldKey.PERFORMER_NAME);
        this.tagFieldToId3.put((Enum)FieldKey.PERFORMER_NAME_SORT, (Object)ID3v22FieldKey.PERFORMER_NAME_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.PERIOD, (Object)ID3v22FieldKey.PERIOD);
        this.tagFieldToId3.put((Enum)FieldKey.PRODUCER, (Object)ID3v22FieldKey.PRODUCER);
        this.tagFieldToId3.put((Enum)FieldKey.QUALITY, (Object)ID3v22FieldKey.QUALITY);
        this.tagFieldToId3.put((Enum)FieldKey.RANKING, (Object)ID3v22FieldKey.RANKING);
        this.tagFieldToId3.put((Enum)FieldKey.RATING, (Object)ID3v22FieldKey.RATING);
        this.tagFieldToId3.put((Enum)FieldKey.RECORD_LABEL, (Object)ID3v22FieldKey.RECORD_LABEL);
        this.tagFieldToId3.put((Enum)FieldKey.REMIXER, (Object)ID3v22FieldKey.REMIXER);
        this.tagFieldToId3.put((Enum)FieldKey.SCRIPT, (Object)ID3v22FieldKey.SCRIPT);
        this.tagFieldToId3.put((Enum)FieldKey.SINGLE_DISC_TRACK_NO, (Object)ID3v22FieldKey.SINGLE_DISC_TRACK_NO);
        this.tagFieldToId3.put((Enum)FieldKey.SUBTITLE, (Object)ID3v22FieldKey.SUBTITLE);
        this.tagFieldToId3.put((Enum)FieldKey.TAGS, (Object)ID3v22FieldKey.TAGS);
        this.tagFieldToId3.put((Enum)FieldKey.TEMPO, (Object)ID3v22FieldKey.TEMPO);
        this.tagFieldToId3.put((Enum)FieldKey.TIMBRE, (Object)ID3v22FieldKey.TIMBRE);
        this.tagFieldToId3.put((Enum)FieldKey.TITLE, (Object)ID3v22FieldKey.TITLE);
        this.tagFieldToId3.put((Enum)FieldKey.TITLE_MOVEMENT, (Object)ID3v22FieldKey.TITLE_MOVEMENT);
        this.tagFieldToId3.put((Enum)FieldKey.TITLE_SORT, (Object)ID3v22FieldKey.TITLE_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.TONALITY, (Object)ID3v22FieldKey.TONALITY);
        this.tagFieldToId3.put((Enum)FieldKey.TRACK, (Object)ID3v22FieldKey.TRACK);
        this.tagFieldToId3.put((Enum)FieldKey.TRACK_TOTAL, (Object)ID3v22FieldKey.TRACK_TOTAL);
        this.tagFieldToId3.put((Enum)FieldKey.URL_DISCOGS_ARTIST_SITE, (Object)ID3v22FieldKey.URL_DISCOGS_ARTIST_SITE);
        this.tagFieldToId3.put((Enum)FieldKey.URL_DISCOGS_RELEASE_SITE, (Object)ID3v22FieldKey.URL_DISCOGS_RELEASE_SITE);
        this.tagFieldToId3.put((Enum)FieldKey.URL_LYRICS_SITE, (Object)ID3v22FieldKey.URL_LYRICS_SITE);
        this.tagFieldToId3.put((Enum)FieldKey.URL_OFFICIAL_ARTIST_SITE, (Object)ID3v22FieldKey.URL_OFFICIAL_ARTIST_SITE);
        this.tagFieldToId3.put((Enum)FieldKey.URL_OFFICIAL_RELEASE_SITE, (Object)ID3v22FieldKey.URL_OFFICIAL_RELEASE_SITE);
        this.tagFieldToId3.put((Enum)FieldKey.URL_WIKIPEDIA_ARTIST_SITE, (Object)ID3v22FieldKey.URL_WIKIPEDIA_ARTIST_SITE);
        this.tagFieldToId3.put((Enum)FieldKey.URL_WIKIPEDIA_RELEASE_SITE, (Object)ID3v22FieldKey.URL_WIKIPEDIA_RELEASE_SITE);
        this.tagFieldToId3.put((Enum)FieldKey.WORK, (Object)ID3v22FieldKey.WORK);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_COMPOSITION, (Object)ID3v22FieldKey.MUSICBRAINZ_WORK_COMPOSITION);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL1, (Object)ID3v22FieldKey.WORK_PART_LEVEL1);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL1_TYPE, (Object)ID3v22FieldKey.WORK_PART_LEVEL1_TYPE);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL2, (Object)ID3v22FieldKey.WORK_PART_LEVEL2);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL2_TYPE, (Object)ID3v22FieldKey.WORK_PART_LEVEL2_TYPE);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL3, (Object)ID3v22FieldKey.WORK_PART_LEVEL3);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL3_TYPE, (Object)ID3v22FieldKey.WORK_PART_LEVEL3_TYPE);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL4, (Object)ID3v22FieldKey.WORK_PART_LEVEL4);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL4_TYPE, (Object)ID3v22FieldKey.WORK_PART_LEVEL4_TYPE);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL5, (Object)ID3v22FieldKey.WORK_PART_LEVEL5);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL5_TYPE, (Object)ID3v22FieldKey.WORK_PART_LEVEL5_TYPE);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL6, (Object)ID3v22FieldKey.WORK_PART_LEVEL6);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL6_TYPE, (Object)ID3v22FieldKey.WORK_PART_LEVEL6_TYPE);
        this.tagFieldToId3.put((Enum)FieldKey.WORK_TYPE, (Object)ID3v22FieldKey.WORK_TYPE);
        this.tagFieldToId3.put((Enum)FieldKey.YEAR, (Object)ID3v22FieldKey.YEAR);
        for (Map.Entry entry : this.tagFieldToId3.entrySet()) {
            this.id3ToTagField.put((Enum)((ID3v22FieldKey)((Object)entry.getValue())), (Object)((FieldKey)((Object)entry.getKey())));
        }
    }

    public static ID3v22Frames getInstanceOf() {
        if (id3v22Frames == null) {
            id3v22Frames = new ID3v22Frames();
        }
        return id3v22Frames;
    }

    public FieldKey getGenericKeyFromId3(ID3v22FieldKey iD3v22FieldKey) {
        return (FieldKey)((Object)this.id3ToTagField.get((Object)iD3v22FieldKey));
    }

    public ID3v22FieldKey getId3KeyFromGenericKey(FieldKey fieldKey) {
        return (ID3v22FieldKey)((Object)this.tagFieldToId3.get((Object)fieldKey));
    }
}

