/*
 * Decompiled with CFR 0.0.
 * 
 * Could not load the following classes:
 *  java.lang.Class
 *  java.lang.Enum
 *  java.lang.Object
 *  java.lang.String
 *  java.util.EnumMap
 *  java.util.Map
 *  java.util.Map$Entry
 *  java.util.Set
 *  java.util.TreeSet
 */
package org.jaudiotagger.tag.id3;

import java.util.EnumMap;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import org.jaudiotagger.tag.FieldKey;
import org.jaudiotagger.tag.datatype.AbstractValuePair;
import org.jaudiotagger.tag.id3.ID3Frames;
import org.jaudiotagger.tag.id3.ID3v24FieldKey;

public class ID3v24Frames
extends ID3Frames {
    public static final String FRAME_ID_ACCOMPANIMENT = "TPE2";
    public static final String FRAME_ID_ALBUM = "TALB";
    public static final String FRAME_ID_ALBUM_ARTIST_SORT_ORDER_ITUNES = "TSO2";
    public static final String FRAME_ID_ALBUM_SORT_ORDER = "TSOA";
    public static final String FRAME_ID_ARTIST = "TPE1";
    public static final String FRAME_ID_ARTIST_SORT_ORDER = "TSOP";
    public static final String FRAME_ID_ATTACHED_PICTURE = "APIC";
    public static final String FRAME_ID_AUDIO_ENCRYPTION = "AENC";
    public static final String FRAME_ID_AUDIO_SEEK_POINT_INDEX = "ASPI";
    public static final String FRAME_ID_BPM = "TBPM";
    public static final String FRAME_ID_COMMENT = "COMM";
    public static final String FRAME_ID_COMMERCIAL_FRAME = "COMR";
    public static final String FRAME_ID_COMPOSER = "TCOM";
    public static final String FRAME_ID_COMPOSER_SORT_ORDER_ITUNES = "TSOC";
    public static final String FRAME_ID_CONDUCTOR = "TPE3";
    public static final String FRAME_ID_CONTENT_GROUP_DESC = "TIT1";
    public static final String FRAME_ID_COPYRIGHTINFO = "TCOP";
    public static final String FRAME_ID_ENCODEDBY = "TENC";
    public static final String FRAME_ID_ENCODING_TIME = "TDEN";
    public static final String FRAME_ID_ENCRYPTION = "ENCR";
    public static final String FRAME_ID_EQUALISATION2 = "EQU2";
    public static final String FRAME_ID_EVENT_TIMING_CODES = "ETCO";
    public static final String FRAME_ID_FILE_OWNER = "TOWN";
    public static final String FRAME_ID_FILE_TYPE = "TFLT";
    public static final String FRAME_ID_GENERAL_ENCAPS_OBJECT = "GEOB";
    public static final String FRAME_ID_GENRE = "TCON";
    public static final String FRAME_ID_GROUP_ID_REG = "GRID";
    public static final String FRAME_ID_HW_SW_SETTINGS = "TSSE";
    public static final String FRAME_ID_INITIAL_KEY = "TKEY";
    public static final String FRAME_ID_INVOLVED_PEOPLE = "TIPL";
    public static final String FRAME_ID_ISRC = "TSRC";
    public static final String FRAME_ID_IS_COMPILATION = "TCMP";
    public static final String FRAME_ID_ITUNES_GROUPING = "GRP1";
    public static final String FRAME_ID_LANGUAGE = "TLAN";
    public static final String FRAME_ID_LENGTH = "TLEN";
    public static final String FRAME_ID_LINKED_INFO = "LINK";
    public static final String FRAME_ID_LYRICIST = "TEXT";
    public static final String FRAME_ID_MEDIA_TYPE = "TMED";
    public static final String FRAME_ID_MOOD = "TMOO";
    public static final String FRAME_ID_MOVEMENT = "MVNM";
    public static final String FRAME_ID_MOVEMENT_NO = "MVIN";
    public static final String FRAME_ID_MPEG_LOCATION_LOOKUP_TABLE = "MLLT";
    public static final String FRAME_ID_MUSICIAN_CREDITS = "TMCL";
    public static final String FRAME_ID_MUSIC_CD_ID = "MCDI";
    public static final String FRAME_ID_ORIGARTIST = "TOPE";
    public static final String FRAME_ID_ORIGINAL_RELEASE_TIME = "TDOR";
    public static final String FRAME_ID_ORIG_FILENAME = "TOFN";
    public static final String FRAME_ID_ORIG_LYRICIST = "TOLY";
    public static final String FRAME_ID_ORIG_TITLE = "TOAL";
    public static final String FRAME_ID_OWNERSHIP = "OWNE";
    public static final String FRAME_ID_PERFORMER_SORT_OWNER = "TSOP";
    public static final String FRAME_ID_PLAYLIST_DELAY = "TDLY";
    public static final String FRAME_ID_PLAY_COUNTER = "PCNT";
    public static final String FRAME_ID_POPULARIMETER = "POPM";
    public static final String FRAME_ID_POSITION_SYNC = "POSS";
    public static final String FRAME_ID_PRIVATE = "PRIV";
    public static final String FRAME_ID_PRODUCED_NOTICE = "TPRO";
    public static final String FRAME_ID_PUBLISHER = "TPUB";
    public static final String FRAME_ID_RADIO_NAME = "TRSN";
    public static final String FRAME_ID_RADIO_OWNER = "TRSO";
    public static final String FRAME_ID_RECOMMENDED_BUFFER_SIZE = "RBUF";
    public static final String FRAME_ID_RELATIVE_VOLUME_ADJUSTMENT2 = "RVA2";
    public static final String FRAME_ID_RELEASE_TIME = "TDRL";
    public static final String FRAME_ID_REMIXED = "TPE4";
    public static final String FRAME_ID_REVERB = "RVRB";
    public static final String FRAME_ID_SEEK = "SEEK";
    public static final String FRAME_ID_SET = "TPOS";
    public static final String FRAME_ID_SET_SUBTITLE = "TSST";
    public static final String FRAME_ID_SIGNATURE = "SIGN";
    public static final String FRAME_ID_SYNC_LYRIC = "SYLT";
    public static final String FRAME_ID_SYNC_TEMPO = "SYTC";
    public static final String FRAME_ID_TAGGING_TIME = "TDTG";
    public static final String FRAME_ID_TERMS_OF_USE = "USER";
    public static final String FRAME_ID_TITLE = "TIT2";
    public static final String FRAME_ID_TITLE_REFINEMENT = "TIT3";
    public static final String FRAME_ID_TITLE_SORT_ORDER = "TSOT";
    public static final String FRAME_ID_TITLE_SORT_OWNER = "TSOT";
    public static final String FRAME_ID_TRACK = "TRCK";
    public static final String FRAME_ID_UNIQUE_FILE_ID = "UFID";
    public static final String FRAME_ID_UNSYNC_LYRICS = "USLT";
    public static final String FRAME_ID_URL_ARTIST_WEB = "WOAR";
    public static final String FRAME_ID_URL_COMMERCIAL = "WCOM";
    public static final String FRAME_ID_URL_COPYRIGHT = "WCOP";
    public static final String FRAME_ID_URL_FILE_WEB = "WOAF";
    public static final String FRAME_ID_URL_OFFICIAL_RADIO = "WORS";
    public static final String FRAME_ID_URL_PAYMENT = "WPAY";
    public static final String FRAME_ID_URL_PUBLISHERS = "WPUB";
    public static final String FRAME_ID_URL_SOURCE_WEB = "WOAS";
    public static final String FRAME_ID_USER_DEFINED_INFO = "TXXX";
    public static final String FRAME_ID_USER_DEFINED_URL = "WXXX";
    public static final String FRAME_ID_YEAR = "TDRC";
    private static ID3v24Frames id3v24Frames;
    protected EnumMap<ID3v24FieldKey, FieldKey> id3ToTagField = new EnumMap(ID3v24FieldKey.class);
    protected EnumMap<FieldKey, ID3v24FieldKey> tagFieldToId3 = new EnumMap(FieldKey.class);

    private ID3v24Frames() {
        this.supportedFrames.add((Object)FRAME_ID_ACCOMPANIMENT);
        this.supportedFrames.add((Object)FRAME_ID_ALBUM);
        this.supportedFrames.add((Object)FRAME_ID_ALBUM_SORT_ORDER);
        this.supportedFrames.add((Object)FRAME_ID_ARTIST);
        this.supportedFrames.add((Object)FRAME_ID_ATTACHED_PICTURE);
        this.supportedFrames.add((Object)FRAME_ID_AUDIO_ENCRYPTION);
        this.supportedFrames.add((Object)FRAME_ID_AUDIO_SEEK_POINT_INDEX);
        this.supportedFrames.add((Object)FRAME_ID_BPM);
        this.supportedFrames.add((Object)FRAME_ID_COMMENT);
        this.supportedFrames.add((Object)FRAME_ID_COMMERCIAL_FRAME);
        this.supportedFrames.add((Object)FRAME_ID_COMPOSER);
        this.supportedFrames.add((Object)FRAME_ID_CONDUCTOR);
        this.supportedFrames.add((Object)FRAME_ID_CONTENT_GROUP_DESC);
        this.supportedFrames.add((Object)FRAME_ID_COPYRIGHTINFO);
        this.supportedFrames.add((Object)FRAME_ID_ENCODEDBY);
        this.supportedFrames.add((Object)FRAME_ID_ENCODING_TIME);
        this.supportedFrames.add((Object)FRAME_ID_ENCRYPTION);
        this.supportedFrames.add((Object)FRAME_ID_EQUALISATION2);
        this.supportedFrames.add((Object)FRAME_ID_EVENT_TIMING_CODES);
        this.supportedFrames.add((Object)FRAME_ID_FILE_OWNER);
        this.supportedFrames.add((Object)FRAME_ID_FILE_TYPE);
        this.supportedFrames.add((Object)FRAME_ID_GENERAL_ENCAPS_OBJECT);
        this.supportedFrames.add((Object)FRAME_ID_GENRE);
        this.supportedFrames.add((Object)FRAME_ID_GROUP_ID_REG);
        this.supportedFrames.add((Object)FRAME_ID_HW_SW_SETTINGS);
        this.supportedFrames.add((Object)FRAME_ID_INITIAL_KEY);
        this.supportedFrames.add((Object)FRAME_ID_INVOLVED_PEOPLE);
        this.supportedFrames.add((Object)FRAME_ID_ISRC);
        this.supportedFrames.add((Object)FRAME_ID_ITUNES_GROUPING);
        this.supportedFrames.add((Object)FRAME_ID_LANGUAGE);
        this.supportedFrames.add((Object)FRAME_ID_LENGTH);
        this.supportedFrames.add((Object)FRAME_ID_LINKED_INFO);
        this.supportedFrames.add((Object)FRAME_ID_LYRICIST);
        this.supportedFrames.add((Object)FRAME_ID_MEDIA_TYPE);
        this.supportedFrames.add((Object)FRAME_ID_MOOD);
        this.supportedFrames.add((Object)FRAME_ID_MOVEMENT);
        this.supportedFrames.add((Object)FRAME_ID_MOVEMENT_NO);
        this.supportedFrames.add((Object)FRAME_ID_MPEG_LOCATION_LOOKUP_TABLE);
        this.supportedFrames.add((Object)FRAME_ID_MUSIC_CD_ID);
        this.supportedFrames.add((Object)FRAME_ID_ORIGARTIST);
        this.supportedFrames.add((Object)FRAME_ID_ORIGINAL_RELEASE_TIME);
        this.supportedFrames.add((Object)FRAME_ID_ORIG_FILENAME);
        this.supportedFrames.add((Object)FRAME_ID_ORIG_LYRICIST);
        this.supportedFrames.add((Object)FRAME_ID_ORIG_TITLE);
        this.supportedFrames.add((Object)FRAME_ID_OWNERSHIP);
        this.supportedFrames.add((Object)"TSOP");
        this.supportedFrames.add((Object)FRAME_ID_PLAYLIST_DELAY);
        this.supportedFrames.add((Object)FRAME_ID_PLAY_COUNTER);
        this.supportedFrames.add((Object)FRAME_ID_POPULARIMETER);
        this.supportedFrames.add((Object)FRAME_ID_POSITION_SYNC);
        this.supportedFrames.add((Object)FRAME_ID_PRIVATE);
        this.supportedFrames.add((Object)FRAME_ID_PRODUCED_NOTICE);
        this.supportedFrames.add((Object)FRAME_ID_PUBLISHER);
        this.supportedFrames.add((Object)FRAME_ID_RADIO_NAME);
        this.supportedFrames.add((Object)FRAME_ID_RADIO_OWNER);
        this.supportedFrames.add((Object)FRAME_ID_RECOMMENDED_BUFFER_SIZE);
        this.supportedFrames.add((Object)FRAME_ID_RELATIVE_VOLUME_ADJUSTMENT2);
        this.supportedFrames.add((Object)FRAME_ID_RELEASE_TIME);
        this.supportedFrames.add((Object)FRAME_ID_REMIXED);
        this.supportedFrames.add((Object)FRAME_ID_REVERB);
        this.supportedFrames.add((Object)FRAME_ID_SEEK);
        this.supportedFrames.add((Object)FRAME_ID_SET);
        this.supportedFrames.add((Object)FRAME_ID_SET_SUBTITLE);
        this.supportedFrames.add((Object)FRAME_ID_SIGNATURE);
        this.supportedFrames.add((Object)FRAME_ID_SYNC_LYRIC);
        this.supportedFrames.add((Object)FRAME_ID_SYNC_TEMPO);
        this.supportedFrames.add((Object)FRAME_ID_TAGGING_TIME);
        this.supportedFrames.add((Object)FRAME_ID_TERMS_OF_USE);
        this.supportedFrames.add((Object)FRAME_ID_TITLE);
        this.supportedFrames.add((Object)FRAME_ID_TITLE_REFINEMENT);
        this.supportedFrames.add((Object)"TSOT");
        this.supportedFrames.add((Object)FRAME_ID_TRACK);
        this.supportedFrames.add((Object)FRAME_ID_UNIQUE_FILE_ID);
        this.supportedFrames.add((Object)FRAME_ID_UNSYNC_LYRICS);
        this.supportedFrames.add((Object)FRAME_ID_URL_ARTIST_WEB);
        this.supportedFrames.add((Object)FRAME_ID_URL_COMMERCIAL);
        this.supportedFrames.add((Object)FRAME_ID_URL_COPYRIGHT);
        this.supportedFrames.add((Object)FRAME_ID_URL_FILE_WEB);
        this.supportedFrames.add((Object)FRAME_ID_URL_OFFICIAL_RADIO);
        this.supportedFrames.add((Object)FRAME_ID_URL_PAYMENT);
        this.supportedFrames.add((Object)FRAME_ID_URL_PUBLISHERS);
        this.supportedFrames.add((Object)FRAME_ID_URL_SOURCE_WEB);
        this.supportedFrames.add((Object)FRAME_ID_USER_DEFINED_INFO);
        this.supportedFrames.add((Object)FRAME_ID_USER_DEFINED_URL);
        this.supportedFrames.add((Object)FRAME_ID_YEAR);
        this.extensionFrames.add((Object)FRAME_ID_IS_COMPILATION);
        this.extensionFrames.add((Object)FRAME_ID_ALBUM_ARTIST_SORT_ORDER_ITUNES);
        this.extensionFrames.add((Object)FRAME_ID_COMPOSER_SORT_ORDER_ITUNES);
        this.commonFrames.add((Object)FRAME_ID_ARTIST);
        this.commonFrames.add((Object)FRAME_ID_ALBUM);
        this.commonFrames.add((Object)FRAME_ID_TITLE);
        this.commonFrames.add((Object)FRAME_ID_GENRE);
        this.commonFrames.add((Object)FRAME_ID_TRACK);
        this.commonFrames.add((Object)FRAME_ID_YEAR);
        this.commonFrames.add((Object)FRAME_ID_COMMENT);
        this.binaryFrames.add((Object)FRAME_ID_ATTACHED_PICTURE);
        this.binaryFrames.add((Object)FRAME_ID_AUDIO_ENCRYPTION);
        this.binaryFrames.add((Object)FRAME_ID_ENCRYPTION);
        this.binaryFrames.add((Object)FRAME_ID_EQUALISATION2);
        this.binaryFrames.add((Object)FRAME_ID_EVENT_TIMING_CODES);
        this.binaryFrames.add((Object)FRAME_ID_GENERAL_ENCAPS_OBJECT);
        this.binaryFrames.add((Object)FRAME_ID_RELATIVE_VOLUME_ADJUSTMENT2);
        this.binaryFrames.add((Object)FRAME_ID_RECOMMENDED_BUFFER_SIZE);
        this.binaryFrames.add((Object)FRAME_ID_UNIQUE_FILE_ID);
        this.idToValue.put((Object)FRAME_ID_ACCOMPANIMENT, (Object)"Text: Band/Orchestra/Accompaniment");
        this.idToValue.put((Object)FRAME_ID_ALBUM, (Object)"Text: Album/Movie/Show title");
        this.idToValue.put((Object)FRAME_ID_ALBUM_SORT_ORDER, (Object)"Album sort order");
        this.idToValue.put((Object)FRAME_ID_ARTIST, (Object)"Text: Lead artist(s)/Lead performer(s)/Soloist(s)/Performing group");
        this.idToValue.put((Object)FRAME_ID_ATTACHED_PICTURE, (Object)"Attached picture");
        this.idToValue.put((Object)FRAME_ID_AUDIO_ENCRYPTION, (Object)"Audio encryption");
        this.idToValue.put((Object)FRAME_ID_AUDIO_SEEK_POINT_INDEX, (Object)"Audio seek point index");
        this.idToValue.put((Object)FRAME_ID_BPM, (Object)"Text: BPM (Beats Per Minute)");
        this.idToValue.put((Object)FRAME_ID_COMMENT, (Object)"Comments");
        this.idToValue.put((Object)FRAME_ID_COMMERCIAL_FRAME, (Object)"Commercial Frame");
        this.idToValue.put((Object)FRAME_ID_COMPOSER, (Object)"Text: Composer");
        this.idToValue.put((Object)FRAME_ID_CONDUCTOR, (Object)"Text: Conductor/Performer refinement");
        this.idToValue.put((Object)FRAME_ID_CONTENT_GROUP_DESC, (Object)"Text: Content group description");
        this.idToValue.put((Object)FRAME_ID_COPYRIGHTINFO, (Object)"Text: Copyright message");
        this.idToValue.put((Object)FRAME_ID_ENCODEDBY, (Object)"Text: Encoded by");
        this.idToValue.put((Object)FRAME_ID_ENCODING_TIME, (Object)"Text: Encoding time");
        this.idToValue.put((Object)FRAME_ID_ENCRYPTION, (Object)"Encryption method registration");
        this.idToValue.put((Object)FRAME_ID_EQUALISATION2, (Object)"Equalization (2)");
        this.idToValue.put((Object)FRAME_ID_EVENT_TIMING_CODES, (Object)"Event timing codes");
        this.idToValue.put((Object)FRAME_ID_FILE_OWNER, (Object)"Text:File Owner");
        this.idToValue.put((Object)FRAME_ID_FILE_TYPE, (Object)"Text: File type");
        this.idToValue.put((Object)FRAME_ID_GENERAL_ENCAPS_OBJECT, (Object)"General encapsulated datatype");
        this.idToValue.put((Object)FRAME_ID_GENRE, (Object)"Text: Content type");
        this.idToValue.put((Object)FRAME_ID_GROUP_ID_REG, (Object)"Group ID Registration");
        this.idToValue.put((Object)FRAME_ID_HW_SW_SETTINGS, (Object)"Text: Software/hardware and settings used for encoding");
        this.idToValue.put((Object)FRAME_ID_INITIAL_KEY, (Object)"Text: Initial key");
        this.idToValue.put((Object)FRAME_ID_INVOLVED_PEOPLE, (Object)"Involved people list");
        this.idToValue.put((Object)FRAME_ID_ISRC, (Object)"Text: ISRC (International Standard Recording Code)");
        this.idToValue.put((Object)FRAME_ID_ITUNES_GROUPING, (Object)"iTunes Grouping");
        this.idToValue.put((Object)FRAME_ID_LANGUAGE, (Object)"Text: Language(s)");
        this.idToValue.put((Object)FRAME_ID_LENGTH, (Object)"Text: Length");
        this.idToValue.put((Object)FRAME_ID_LINKED_INFO, (Object)"Linked information");
        this.idToValue.put((Object)FRAME_ID_LYRICIST, (Object)"Text: Lyricist/text writer");
        this.idToValue.put((Object)FRAME_ID_MEDIA_TYPE, (Object)"Text: Media type");
        this.idToValue.put((Object)FRAME_ID_MOOD, (Object)"Text: Mood");
        this.idToValue.put((Object)FRAME_ID_MOVEMENT, (Object)"Text: Movement");
        this.idToValue.put((Object)FRAME_ID_MOVEMENT_NO, (Object)"Text: Movement No");
        this.idToValue.put((Object)FRAME_ID_MPEG_LOCATION_LOOKUP_TABLE, (Object)"MPEG location lookup table");
        this.idToValue.put((Object)FRAME_ID_MUSIC_CD_ID, (Object)"Music CD Identifier");
        this.idToValue.put((Object)FRAME_ID_ORIGARTIST, (Object)"Text: Original artist(s)/performer(s)");
        this.idToValue.put((Object)FRAME_ID_ORIGINAL_RELEASE_TIME, (Object)"Text: Original release time");
        this.idToValue.put((Object)FRAME_ID_ORIG_FILENAME, (Object)"Text: Original filename");
        this.idToValue.put((Object)FRAME_ID_ORIG_LYRICIST, (Object)"Text: Original Lyricist(s)/text writer(s)");
        this.idToValue.put((Object)FRAME_ID_ORIG_TITLE, (Object)"Text: Original album/Movie/Show title");
        this.idToValue.put((Object)FRAME_ID_OWNERSHIP, (Object)"Ownership");
        this.idToValue.put((Object)"TSOP", (Object)"Performance Sort Order");
        this.idToValue.put((Object)FRAME_ID_PLAYLIST_DELAY, (Object)"Text: Playlist delay");
        this.idToValue.put((Object)FRAME_ID_PLAY_COUNTER, (Object)"Play counter");
        this.idToValue.put((Object)FRAME_ID_POPULARIMETER, (Object)"Popularimeter");
        this.idToValue.put((Object)FRAME_ID_POSITION_SYNC, (Object)"Position Sync");
        this.idToValue.put((Object)FRAME_ID_PRIVATE, (Object)"Private frame");
        this.idToValue.put((Object)FRAME_ID_PRODUCED_NOTICE, (Object)"Produced Notice");
        this.idToValue.put((Object)FRAME_ID_PUBLISHER, (Object)"Text: Publisher");
        this.idToValue.put((Object)FRAME_ID_RADIO_NAME, (Object)"Text: Radio Name");
        this.idToValue.put((Object)FRAME_ID_RADIO_OWNER, (Object)"Text: Radio Owner");
        this.idToValue.put((Object)FRAME_ID_RECOMMENDED_BUFFER_SIZE, (Object)"Recommended buffer size");
        this.idToValue.put((Object)FRAME_ID_RELATIVE_VOLUME_ADJUSTMENT2, (Object)"Relative volume adjustment(2)");
        this.idToValue.put((Object)FRAME_ID_RELEASE_TIME, (Object)"Release Time");
        this.idToValue.put((Object)FRAME_ID_REMIXED, (Object)"Text: Interpreted, remixed, or otherwise modified by");
        this.idToValue.put((Object)FRAME_ID_REVERB, (Object)"Reverb");
        this.idToValue.put((Object)FRAME_ID_SEEK, (Object)"Seek");
        this.idToValue.put((Object)FRAME_ID_SET, (Object)"Text: Part of a setField");
        this.idToValue.put((Object)FRAME_ID_SET_SUBTITLE, (Object)"Text: Set subtitle");
        this.idToValue.put((Object)FRAME_ID_SIGNATURE, (Object)"Signature");
        this.idToValue.put((Object)FRAME_ID_SYNC_LYRIC, (Object)"Synchronized lyric/text");
        this.idToValue.put((Object)FRAME_ID_SYNC_TEMPO, (Object)"Synced tempo codes");
        this.idToValue.put((Object)FRAME_ID_TAGGING_TIME, (Object)"Text: Tagging time");
        this.idToValue.put((Object)FRAME_ID_TERMS_OF_USE, (Object)"Terms of Use");
        this.idToValue.put((Object)FRAME_ID_TITLE, (Object)"Text: title");
        this.idToValue.put((Object)FRAME_ID_TITLE_REFINEMENT, (Object)"Text: Subtitle/Description refinement");
        this.idToValue.put((Object)"TSOT", (Object)"Text: title sort order");
        this.idToValue.put((Object)FRAME_ID_TRACK, (Object)"Text: Track number/Position in setField");
        this.idToValue.put((Object)FRAME_ID_UNIQUE_FILE_ID, (Object)"Unique file identifier");
        this.idToValue.put((Object)FRAME_ID_UNSYNC_LYRICS, (Object)"Unsychronized lyric/text transcription");
        this.idToValue.put((Object)FRAME_ID_URL_ARTIST_WEB, (Object)"URL: Official artist/performer webpage");
        this.idToValue.put((Object)FRAME_ID_URL_COMMERCIAL, (Object)"URL: Commercial information");
        this.idToValue.put((Object)FRAME_ID_URL_COPYRIGHT, (Object)"URL: Copyright/Legal information");
        this.idToValue.put((Object)FRAME_ID_URL_FILE_WEB, (Object)"URL: Official audio file webpage");
        this.idToValue.put((Object)FRAME_ID_URL_OFFICIAL_RADIO, (Object)"URL: Official Radio website");
        this.idToValue.put((Object)FRAME_ID_URL_PAYMENT, (Object)"URL: Payment for this recording ");
        this.idToValue.put((Object)FRAME_ID_URL_PUBLISHERS, (Object)"URL: Publishers official webpage");
        this.idToValue.put((Object)FRAME_ID_URL_SOURCE_WEB, (Object)"URL: Official audio source webpage");
        this.idToValue.put((Object)FRAME_ID_USER_DEFINED_INFO, (Object)"User defined text information frame");
        this.idToValue.put((Object)FRAME_ID_USER_DEFINED_URL, (Object)"User defined URL link frame");
        this.idToValue.put((Object)FRAME_ID_YEAR, (Object)"Text:Year");
        this.idToValue.put((Object)FRAME_ID_IS_COMPILATION, (Object)"Is Compilation");
        this.idToValue.put((Object)FRAME_ID_ALBUM_ARTIST_SORT_ORDER_ITUNES, (Object)"Text:Album Artist Sort Order Frame");
        this.idToValue.put((Object)FRAME_ID_COMPOSER_SORT_ORDER_ITUNES, (Object)"Text:Composer Sort Order Frame");
        this.createMaps();
        this.multipleFrames.add((Object)FRAME_ID_USER_DEFINED_INFO);
        this.multipleFrames.add((Object)FRAME_ID_USER_DEFINED_URL);
        this.multipleFrames.add((Object)FRAME_ID_ATTACHED_PICTURE);
        this.multipleFrames.add((Object)FRAME_ID_PRIVATE);
        this.multipleFrames.add((Object)FRAME_ID_COMMENT);
        this.multipleFrames.add((Object)FRAME_ID_UNIQUE_FILE_ID);
        this.multipleFrames.add((Object)FRAME_ID_UNSYNC_LYRICS);
        this.multipleFrames.add((Object)FRAME_ID_POPULARIMETER);
        this.multipleFrames.add((Object)FRAME_ID_GENERAL_ENCAPS_OBJECT);
        this.multipleFrames.add((Object)FRAME_ID_URL_ARTIST_WEB);
        this.discardIfFileAlteredFrames.add((Object)FRAME_ID_EVENT_TIMING_CODES);
        this.discardIfFileAlteredFrames.add((Object)FRAME_ID_MPEG_LOCATION_LOOKUP_TABLE);
        this.discardIfFileAlteredFrames.add((Object)FRAME_ID_POSITION_SYNC);
        this.discardIfFileAlteredFrames.add((Object)FRAME_ID_SYNC_LYRIC);
        this.discardIfFileAlteredFrames.add((Object)FRAME_ID_SYNC_TEMPO);
        this.discardIfFileAlteredFrames.add((Object)FRAME_ID_EVENT_TIMING_CODES);
        this.discardIfFileAlteredFrames.add((Object)FRAME_ID_ENCODEDBY);
        this.discardIfFileAlteredFrames.add((Object)FRAME_ID_LENGTH);
        this.tagFieldToId3.put((Enum)FieldKey.ACOUSTID_FINGERPRINT, (Object)ID3v24FieldKey.ACOUSTID_FINGERPRINT);
        this.tagFieldToId3.put((Enum)FieldKey.ACOUSTID_ID, (Object)ID3v24FieldKey.ACOUSTID_ID);
        this.tagFieldToId3.put((Enum)FieldKey.ALBUM, (Object)ID3v24FieldKey.ALBUM);
        this.tagFieldToId3.put((Enum)FieldKey.ALBUM_ARTIST, (Object)ID3v24FieldKey.ALBUM_ARTIST);
        this.tagFieldToId3.put((Enum)FieldKey.ALBUM_ARTIST_SORT, (Object)ID3v24FieldKey.ALBUM_ARTIST_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.ALBUM_ARTISTS, (Object)ID3v24FieldKey.ALBUM_ARTISTS);
        this.tagFieldToId3.put((Enum)FieldKey.ALBUM_ARTISTS_SORT, (Object)ID3v24FieldKey.ALBUM_ARTISTS_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.ALBUM_SORT, (Object)ID3v24FieldKey.ALBUM_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.AMAZON_ID, (Object)ID3v24FieldKey.AMAZON_ID);
        this.tagFieldToId3.put((Enum)FieldKey.ARRANGER, (Object)ID3v24FieldKey.ARRANGER);
        this.tagFieldToId3.put((Enum)FieldKey.ARRANGER_SORT, (Object)ID3v24FieldKey.ARRANGER_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.ARTIST, (Object)ID3v24FieldKey.ARTIST);
        this.tagFieldToId3.put((Enum)FieldKey.ARTISTS, (Object)ID3v24FieldKey.ARTISTS);
        this.tagFieldToId3.put((Enum)FieldKey.ARTISTS_SORT, (Object)ID3v24FieldKey.ARTISTS_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.ARTIST_SORT, (Object)ID3v24FieldKey.ARTIST_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.BARCODE, (Object)ID3v24FieldKey.BARCODE);
        this.tagFieldToId3.put((Enum)FieldKey.BPM, (Object)ID3v24FieldKey.BPM);
        this.tagFieldToId3.put((Enum)FieldKey.CATALOG_NO, (Object)ID3v24FieldKey.CATALOG_NO);
        this.tagFieldToId3.put((Enum)FieldKey.CHOIR, (Object)ID3v24FieldKey.CHOIR);
        this.tagFieldToId3.put((Enum)FieldKey.CHOIR_SORT, (Object)ID3v24FieldKey.CHOIR_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.CLASSICAL_CATALOG, (Object)ID3v24FieldKey.CLASSICAL_CATALOG);
        this.tagFieldToId3.put((Enum)FieldKey.CLASSICAL_NICKNAME, (Object)ID3v24FieldKey.CLASSICAL_NICKNAME);
        this.tagFieldToId3.put((Enum)FieldKey.COMMENT, (Object)ID3v24FieldKey.COMMENT);
        this.tagFieldToId3.put((Enum)FieldKey.COMPOSER, (Object)ID3v24FieldKey.COMPOSER);
        this.tagFieldToId3.put((Enum)FieldKey.COMPOSER_SORT, (Object)ID3v24FieldKey.COMPOSER_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.CONDUCTOR, (Object)ID3v24FieldKey.CONDUCTOR);
        this.tagFieldToId3.put((Enum)FieldKey.CONDUCTOR_SORT, (Object)ID3v24FieldKey.CONDUCTOR_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.COPYRIGHT, (Object)ID3v24FieldKey.COPYRIGHT);
        this.tagFieldToId3.put((Enum)FieldKey.COUNTRY, (Object)ID3v24FieldKey.COUNTRY);
        this.tagFieldToId3.put((Enum)FieldKey.COVER_ART, (Object)ID3v24FieldKey.COVER_ART);
        this.tagFieldToId3.put((Enum)FieldKey.CUSTOM1, (Object)ID3v24FieldKey.CUSTOM1);
        this.tagFieldToId3.put((Enum)FieldKey.CUSTOM2, (Object)ID3v24FieldKey.CUSTOM2);
        this.tagFieldToId3.put((Enum)FieldKey.CUSTOM3, (Object)ID3v24FieldKey.CUSTOM3);
        this.tagFieldToId3.put((Enum)FieldKey.CUSTOM4, (Object)ID3v24FieldKey.CUSTOM4);
        this.tagFieldToId3.put((Enum)FieldKey.CUSTOM5, (Object)ID3v24FieldKey.CUSTOM5);
        EnumMap<FieldKey, ID3v24FieldKey> enumMap = this.tagFieldToId3;
        FieldKey fieldKey = FieldKey.DISC_NO;
        ID3v24FieldKey iD3v24FieldKey = ID3v24FieldKey.DISC_NO;
        enumMap.put((Enum)fieldKey, (Object)iD3v24FieldKey);
        this.tagFieldToId3.put((Enum)FieldKey.DISC_SUBTITLE, (Object)ID3v24FieldKey.DISC_SUBTITLE);
        this.tagFieldToId3.put((Enum)FieldKey.DISC_TOTAL, (Object)iD3v24FieldKey);
        this.tagFieldToId3.put((Enum)FieldKey.DJMIXER, (Object)ID3v24FieldKey.DJMIXER);
        this.tagFieldToId3.put((Enum)FieldKey.MOOD_ELECTRONIC, (Object)ID3v24FieldKey.MOOD_ELECTRONIC);
        this.tagFieldToId3.put((Enum)FieldKey.ENCODER, (Object)ID3v24FieldKey.ENCODER);
        this.tagFieldToId3.put((Enum)FieldKey.ENGINEER, (Object)ID3v24FieldKey.ENGINEER);
        this.tagFieldToId3.put((Enum)FieldKey.ENSEMBLE, (Object)ID3v24FieldKey.ENSEMBLE);
        this.tagFieldToId3.put((Enum)FieldKey.ENSEMBLE_SORT, (Object)ID3v24FieldKey.ENSEMBLE_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.FBPM, (Object)ID3v24FieldKey.FBPM);
        this.tagFieldToId3.put((Enum)FieldKey.GENRE, (Object)ID3v24FieldKey.GENRE);
        this.tagFieldToId3.put((Enum)FieldKey.GROUP, (Object)ID3v24FieldKey.GROUP);
        this.tagFieldToId3.put((Enum)FieldKey.GROUPING, (Object)ID3v24FieldKey.GROUPING);
        this.tagFieldToId3.put((Enum)FieldKey.INSTRUMENT, (Object)ID3v24FieldKey.INSTRUMENT);
        this.tagFieldToId3.put((Enum)FieldKey.INVOLVED_PERSON, (Object)ID3v24FieldKey.INVOLVED_PERSON);
        this.tagFieldToId3.put((Enum)FieldKey.ISRC, (Object)ID3v24FieldKey.ISRC);
        this.tagFieldToId3.put((Enum)FieldKey.IS_CLASSICAL, (Object)ID3v24FieldKey.IS_CLASSICAL);
        this.tagFieldToId3.put((Enum)FieldKey.IS_COMPILATION, (Object)ID3v24FieldKey.IS_COMPILATION);
        this.tagFieldToId3.put((Enum)FieldKey.IS_SOUNDTRACK, (Object)ID3v24FieldKey.IS_SOUNDTRACK);
        this.tagFieldToId3.put((Enum)FieldKey.ITUNES_GROUPING, (Object)ID3v24FieldKey.ITUNES_GROUPING);
        this.tagFieldToId3.put((Enum)FieldKey.KEY, (Object)ID3v24FieldKey.KEY);
        this.tagFieldToId3.put((Enum)FieldKey.LANGUAGE, (Object)ID3v24FieldKey.LANGUAGE);
        this.tagFieldToId3.put((Enum)FieldKey.LYRICIST, (Object)ID3v24FieldKey.LYRICIST);
        this.tagFieldToId3.put((Enum)FieldKey.LYRICS, (Object)ID3v24FieldKey.LYRICS);
        this.tagFieldToId3.put((Enum)FieldKey.MEDIA, (Object)ID3v24FieldKey.MEDIA);
        this.tagFieldToId3.put((Enum)FieldKey.MIXER, (Object)ID3v24FieldKey.MIXER);
        this.tagFieldToId3.put((Enum)FieldKey.MOOD, (Object)ID3v24FieldKey.MOOD);
        this.tagFieldToId3.put((Enum)FieldKey.MOOD_ACOUSTIC, (Object)ID3v24FieldKey.MOOD_ACOUSTIC);
        this.tagFieldToId3.put((Enum)FieldKey.MOOD_AGGRESSIVE, (Object)ID3v24FieldKey.MOOD_AGGRESSIVE);
        this.tagFieldToId3.put((Enum)FieldKey.MOOD_AROUSAL, (Object)ID3v24FieldKey.MOOD_AROUSAL);
        this.tagFieldToId3.put((Enum)FieldKey.MOOD_DANCEABILITY, (Object)ID3v24FieldKey.MOOD_DANCEABILITY);
        this.tagFieldToId3.put((Enum)FieldKey.MOOD_HAPPY, (Object)ID3v24FieldKey.MOOD_HAPPY);
        this.tagFieldToId3.put((Enum)FieldKey.MOOD_INSTRUMENTAL, (Object)ID3v24FieldKey.MOOD_INSTRUMENTAL);
        this.tagFieldToId3.put((Enum)FieldKey.MOOD_PARTY, (Object)ID3v24FieldKey.MOOD_PARTY);
        this.tagFieldToId3.put((Enum)FieldKey.MOOD_RELAXED, (Object)ID3v24FieldKey.MOOD_RELAXED);
        this.tagFieldToId3.put((Enum)FieldKey.MOOD_SAD, (Object)ID3v24FieldKey.MOOD_SAD);
        this.tagFieldToId3.put((Enum)FieldKey.MOOD_VALENCE, (Object)ID3v24FieldKey.MOOD_VALENCE);
        this.tagFieldToId3.put((Enum)FieldKey.MOVEMENT, (Object)ID3v24FieldKey.MOVEMENT);
        this.tagFieldToId3.put((Enum)FieldKey.MOVEMENT_NO, (Object)ID3v24FieldKey.MOVEMENT_NO);
        this.tagFieldToId3.put((Enum)FieldKey.MOVEMENT_TOTAL, (Object)ID3v24FieldKey.MOVEMENT_TOTAL);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_ARTISTID, (Object)ID3v24FieldKey.MUSICBRAINZ_ARTISTID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_DISC_ID, (Object)ID3v24FieldKey.MUSICBRAINZ_DISC_ID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_ORIGINAL_RELEASE_ID, (Object)ID3v24FieldKey.MUSICBRAINZ_ORIGINAL_RELEASEID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_RELEASEARTISTID, (Object)ID3v24FieldKey.MUSICBRAINZ_RELEASEARTISTID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_RELEASEID, (Object)ID3v24FieldKey.MUSICBRAINZ_RELEASEID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_RELEASE_COUNTRY, (Object)ID3v24FieldKey.MUSICBRAINZ_RELEASE_COUNTRY);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_RELEASE_GROUP_ID, (Object)ID3v24FieldKey.MUSICBRAINZ_RELEASE_GROUP_ID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_RELEASE_STATUS, (Object)ID3v24FieldKey.MUSICBRAINZ_RELEASE_STATUS);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_RELEASE_TRACK_ID, (Object)ID3v24FieldKey.MUSICBRAINZ_RELEASE_TRACK_ID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_RELEASE_TYPE, (Object)ID3v24FieldKey.MUSICBRAINZ_RELEASE_TYPE);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_TRACK_ID, (Object)ID3v24FieldKey.MUSICBRAINZ_TRACK_ID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK, (Object)ID3v24FieldKey.MUSICBRAINZ_WORK);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_ID, (Object)ID3v24FieldKey.MUSICBRAINZ_WORK_ID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_COMPOSITION, (Object)ID3v24FieldKey.WORK_COMPOSITION);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_COMPOSITION_ID, (Object)ID3v24FieldKey.MUSICBRAINZ_WORK_COMPOSITION_ID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL1_ID, (Object)ID3v24FieldKey.MUSICBRAINZ_WORK_PART_LEVEL1_ID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL2_ID, (Object)ID3v24FieldKey.MUSICBRAINZ_WORK_PART_LEVEL2_ID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL3_ID, (Object)ID3v24FieldKey.MUSICBRAINZ_WORK_PART_LEVEL3_ID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL4_ID, (Object)ID3v24FieldKey.MUSICBRAINZ_WORK_PART_LEVEL4_ID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL5_ID, (Object)ID3v24FieldKey.MUSICBRAINZ_WORK_PART_LEVEL5_ID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL6_ID, (Object)ID3v24FieldKey.MUSICBRAINZ_WORK_PART_LEVEL6_ID);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICIP_ID, (Object)ID3v24FieldKey.MUSICIP_ID);
        this.tagFieldToId3.put((Enum)FieldKey.OCCASION, (Object)ID3v24FieldKey.OCCASION);
        this.tagFieldToId3.put((Enum)FieldKey.OPUS, (Object)ID3v24FieldKey.OPUS);
        this.tagFieldToId3.put((Enum)FieldKey.ORCHESTRA, (Object)ID3v24FieldKey.ORCHESTRA);
        this.tagFieldToId3.put((Enum)FieldKey.ORCHESTRA_SORT, (Object)ID3v24FieldKey.ORCHESTRA_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.ORIGINAL_ALBUM, (Object)ID3v24FieldKey.ORIGINAL_ALBUM);
        this.tagFieldToId3.put((Enum)FieldKey.ORIGINAL_ARTIST, (Object)ID3v24FieldKey.ORIGINAL_ARTIST);
        this.tagFieldToId3.put((Enum)FieldKey.ORIGINAL_LYRICIST, (Object)ID3v24FieldKey.ORIGINAL_LYRICIST);
        this.tagFieldToId3.put((Enum)FieldKey.ORIGINAL_YEAR, (Object)ID3v24FieldKey.ORIGINAL_YEAR);
        this.tagFieldToId3.put((Enum)FieldKey.PART, (Object)ID3v24FieldKey.PART);
        this.tagFieldToId3.put((Enum)FieldKey.PART_NUMBER, (Object)ID3v24FieldKey.PART_NUMBER);
        this.tagFieldToId3.put((Enum)FieldKey.PART_TYPE, (Object)ID3v24FieldKey.PART_TYPE);
        this.tagFieldToId3.put((Enum)FieldKey.PERFORMER, (Object)ID3v24FieldKey.PERFORMER);
        this.tagFieldToId3.put((Enum)FieldKey.PERFORMER_NAME, (Object)ID3v24FieldKey.PERFORMER_NAME);
        this.tagFieldToId3.put((Enum)FieldKey.PERFORMER_NAME_SORT, (Object)ID3v24FieldKey.PERFORMER_NAME_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.PERIOD, (Object)ID3v24FieldKey.PERIOD);
        this.tagFieldToId3.put((Enum)FieldKey.PRODUCER, (Object)ID3v24FieldKey.PRODUCER);
        this.tagFieldToId3.put((Enum)FieldKey.QUALITY, (Object)ID3v24FieldKey.QUALITY);
        this.tagFieldToId3.put((Enum)FieldKey.RANKING, (Object)ID3v24FieldKey.RANKING);
        this.tagFieldToId3.put((Enum)FieldKey.RATING, (Object)ID3v24FieldKey.RATING);
        this.tagFieldToId3.put((Enum)FieldKey.RECORD_LABEL, (Object)ID3v24FieldKey.RECORD_LABEL);
        this.tagFieldToId3.put((Enum)FieldKey.REMIXER, (Object)ID3v24FieldKey.REMIXER);
        this.tagFieldToId3.put((Enum)FieldKey.SCRIPT, (Object)ID3v24FieldKey.SCRIPT);
        this.tagFieldToId3.put((Enum)FieldKey.SINGLE_DISC_TRACK_NO, (Object)ID3v24FieldKey.SINGLE_DISC_TRACK_NO);
        this.tagFieldToId3.put((Enum)FieldKey.SUBTITLE, (Object)ID3v24FieldKey.SUBTITLE);
        this.tagFieldToId3.put((Enum)FieldKey.TAGS, (Object)ID3v24FieldKey.TAGS);
        this.tagFieldToId3.put((Enum)FieldKey.TEMPO, (Object)ID3v24FieldKey.TEMPO);
        this.tagFieldToId3.put((Enum)FieldKey.TIMBRE, (Object)ID3v24FieldKey.TIMBRE);
        this.tagFieldToId3.put((Enum)FieldKey.TITLE, (Object)ID3v24FieldKey.TITLE);
        this.tagFieldToId3.put((Enum)FieldKey.TITLE_MOVEMENT, (Object)ID3v24FieldKey.TITLE_MOVEMENT);
        this.tagFieldToId3.put((Enum)FieldKey.TITLE_SORT, (Object)ID3v24FieldKey.TITLE_SORT);
        this.tagFieldToId3.put((Enum)FieldKey.TONALITY, (Object)ID3v24FieldKey.TONALITY);
        this.tagFieldToId3.put((Enum)FieldKey.TRACK, (Object)ID3v24FieldKey.TRACK);
        this.tagFieldToId3.put((Enum)FieldKey.TRACK_TOTAL, (Object)ID3v24FieldKey.TRACK_TOTAL);
        this.tagFieldToId3.put((Enum)FieldKey.URL_DISCOGS_ARTIST_SITE, (Object)ID3v24FieldKey.URL_DISCOGS_ARTIST_SITE);
        this.tagFieldToId3.put((Enum)FieldKey.URL_DISCOGS_RELEASE_SITE, (Object)ID3v24FieldKey.URL_DISCOGS_RELEASE_SITE);
        this.tagFieldToId3.put((Enum)FieldKey.URL_LYRICS_SITE, (Object)ID3v24FieldKey.URL_LYRICS_SITE);
        this.tagFieldToId3.put((Enum)FieldKey.URL_OFFICIAL_ARTIST_SITE, (Object)ID3v24FieldKey.URL_OFFICIAL_ARTIST_SITE);
        this.tagFieldToId3.put((Enum)FieldKey.URL_OFFICIAL_RELEASE_SITE, (Object)ID3v24FieldKey.URL_OFFICIAL_RELEASE_SITE);
        this.tagFieldToId3.put((Enum)FieldKey.URL_WIKIPEDIA_ARTIST_SITE, (Object)ID3v24FieldKey.URL_WIKIPEDIA_ARTIST_SITE);
        this.tagFieldToId3.put((Enum)FieldKey.URL_WIKIPEDIA_RELEASE_SITE, (Object)ID3v24FieldKey.URL_WIKIPEDIA_RELEASE_SITE);
        this.tagFieldToId3.put((Enum)FieldKey.WORK, (Object)ID3v24FieldKey.WORK);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL1, (Object)ID3v24FieldKey.WORK_PART_LEVEL1);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL1_TYPE, (Object)ID3v24FieldKey.WORK_PART_LEVEL1_TYPE);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL2, (Object)ID3v24FieldKey.WORK_PART_LEVEL2);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL2_TYPE, (Object)ID3v24FieldKey.WORK_PART_LEVEL2_TYPE);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL3, (Object)ID3v24FieldKey.WORK_PART_LEVEL3);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL3_TYPE, (Object)ID3v24FieldKey.WORK_PARTOF_LEVEL3_TYPE);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL4, (Object)ID3v24FieldKey.WORK_PART_LEVEL4);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL4_TYPE, (Object)ID3v24FieldKey.WORK_PART_LEVEL4_TYPE);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL5, (Object)ID3v24FieldKey.WORK_PART_LEVEL5);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL5_TYPE, (Object)ID3v24FieldKey.WORK_PART_LEVEL5_TYPE);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL6, (Object)ID3v24FieldKey.WORK_PART_LEVEL6);
        this.tagFieldToId3.put((Enum)FieldKey.MUSICBRAINZ_WORK_PART_LEVEL6_TYPE, (Object)ID3v24FieldKey.WORK_PART_LEVEL6_TYPE);
        this.tagFieldToId3.put((Enum)FieldKey.WORK_TYPE, (Object)ID3v24FieldKey.WORK_TYPE);
        this.tagFieldToId3.put((Enum)FieldKey.YEAR, (Object)ID3v24FieldKey.YEAR);
        for (Map.Entry entry : this.tagFieldToId3.entrySet()) {
            this.id3ToTagField.put((Enum)((ID3v24FieldKey)((Object)entry.getValue())), (Object)((FieldKey)((Object)entry.getKey())));
        }
    }

    public static ID3v24Frames getInstanceOf() {
        if (id3v24Frames == null) {
            id3v24Frames = new ID3v24Frames();
        }
        return id3v24Frames;
    }

    public FieldKey getGenericKeyFromId3(ID3v24FieldKey iD3v24FieldKey) {
        return (FieldKey)((Object)this.id3ToTagField.get((Object)iD3v24FieldKey));
    }

    public ID3v24FieldKey getId3KeyFromGenericKey(FieldKey fieldKey) {
        return (ID3v24FieldKey)((Object)this.tagFieldToId3.get((Object)fieldKey));
    }
}

