/*
 * Decompiled with CFR 0.0.
 * 
 * Could not load the following classes:
 *  java.lang.Enum
 *  java.lang.Object
 *  java.lang.String
 *  java.lang.StringBuilder
 */
package org.jaudiotagger.tag.mp4;

import org.jaudiotagger.tag.mp4.Mp4TagFieldSubType;
import org.jaudiotagger.tag.mp4.field.Mp4FieldType;
import org.jaudiotagger.tag.reference.Tagger;

public final class Mp4FieldKey
extends Enum<Mp4FieldKey> {
    private static final /* synthetic */ Mp4FieldKey[] $VALUES;
    public static final /* enum */ Mp4FieldKey ACOUSTID_FINGERPRINT;
    public static final /* enum */ Mp4FieldKey ACOUSTID_FINGERPRINT_OLD;
    public static final /* enum */ Mp4FieldKey ACOUSTID_ID;
    public static final /* enum */ Mp4FieldKey AK_ID;
    public static final /* enum */ Mp4FieldKey ALBUM;
    public static final /* enum */ Mp4FieldKey ALBUM_ARTIST;
    public static final /* enum */ Mp4FieldKey ALBUM_ARTISTS;
    public static final /* enum */ Mp4FieldKey ALBUM_ARTISTS_SORT;
    public static final /* enum */ Mp4FieldKey ALBUM_ARTIST_SORT;
    public static final /* enum */ Mp4FieldKey ALBUM_SORT;
    public static final /* enum */ Mp4FieldKey AP_ID;
    public static final /* enum */ Mp4FieldKey ARRANGER;
    public static final /* enum */ Mp4FieldKey ARRANGER_SORT;
    public static final /* enum */ Mp4FieldKey ARTIST;
    public static final /* enum */ Mp4FieldKey ARTISTS;
    public static final /* enum */ Mp4FieldKey ARTISTS_SORT;
    public static final /* enum */ Mp4FieldKey ARTIST_SORT;
    public static final /* enum */ Mp4FieldKey ARTWORK;
    public static final /* enum */ Mp4FieldKey ASIN;
    public static final /* enum */ Mp4FieldKey AT_ID;
    public static final /* enum */ Mp4FieldKey BARCODE;
    public static final /* enum */ Mp4FieldKey BPM;
    public static final /* enum */ Mp4FieldKey CATALOGNO;
    public static final /* enum */ Mp4FieldKey CATEGORY;
    public static final /* enum */ Mp4FieldKey CDDB_1;
    public static final /* enum */ Mp4FieldKey CDDB_IDS;
    public static final /* enum */ Mp4FieldKey CDDB_TRACKNUMBER;
    public static final /* enum */ Mp4FieldKey CHOIR;
    public static final /* enum */ Mp4FieldKey CHOIR_SORT;
    public static final /* enum */ Mp4FieldKey CLASSICAL_CATALOG;
    public static final /* enum */ Mp4FieldKey CLASSICAL_NICKNAME;
    public static final /* enum */ Mp4FieldKey CN_ID;
    public static final /* enum */ Mp4FieldKey COMMENT;
    public static final /* enum */ Mp4FieldKey COMPILATION;
    public static final /* enum */ Mp4FieldKey COMPOSER;
    public static final /* enum */ Mp4FieldKey COMPOSER_SORT;
    public static final /* enum */ Mp4FieldKey CONDUCTOR;
    public static final /* enum */ Mp4FieldKey CONDUCTOR_MM3BETA;
    public static final /* enum */ Mp4FieldKey CONDUCTOR_SORT;
    public static final /* enum */ Mp4FieldKey CONTENT_TYPE;
    public static final /* enum */ Mp4FieldKey COPYRIGHT;
    public static final /* enum */ Mp4FieldKey COUNTRY;
    public static final /* enum */ Mp4FieldKey CUSTOM_1;
    public static final /* enum */ Mp4FieldKey CUSTOM_2;
    public static final /* enum */ Mp4FieldKey CUSTOM_3;
    public static final /* enum */ Mp4FieldKey CUSTOM_4;
    public static final /* enum */ Mp4FieldKey CUSTOM_5;
    public static final /* enum */ Mp4FieldKey DAY;
    public static final /* enum */ Mp4FieldKey DESCRIPTION;
    public static final /* enum */ Mp4FieldKey DISCNUMBER;
    public static final /* enum */ Mp4FieldKey DISC_SUBTITLE;
    public static final /* enum */ Mp4FieldKey DJMIXER;
    public static final /* enum */ Mp4FieldKey ENCODER;
    public static final /* enum */ Mp4FieldKey ENGINEER;
    public static final /* enum */ Mp4FieldKey ENSEMBLE;
    public static final /* enum */ Mp4FieldKey ENSEMBLE_SORT;
    public static final /* enum */ Mp4FieldKey EPISODE_GLOBAL_ID;
    public static final /* enum */ Mp4FieldKey FBPM;
    public static final /* enum */ Mp4FieldKey GENRE;
    public static final /* enum */ Mp4FieldKey GENRE_CUSTOM;
    public static final /* enum */ Mp4FieldKey GE_ID;
    public static final /* enum */ Mp4FieldKey GROUP;
    public static final /* enum */ Mp4FieldKey GROUPING;
    public static final /* enum */ Mp4FieldKey INSTRUMENT;
    public static final /* enum */ Mp4FieldKey INVOLVED_PEOPLE;
    public static final /* enum */ Mp4FieldKey ISRC;
    public static final /* enum */ Mp4FieldKey ISRC_MMBETA;
    public static final /* enum */ Mp4FieldKey IS_CLASSICAL;
    public static final /* enum */ Mp4FieldKey IS_SOUNDTRACK;
    public static final /* enum */ Mp4FieldKey ITUNES_NORM;
    public static final /* enum */ Mp4FieldKey ITUNES_SMPB;
    public static final /* enum */ Mp4FieldKey KEY;
    public static final /* enum */ Mp4FieldKey KEYS;
    public static final /* enum */ Mp4FieldKey KEYWORD;
    public static final /* enum */ Mp4FieldKey KEY_OLD;
    public static final /* enum */ Mp4FieldKey LABEL;
    public static final /* enum */ Mp4FieldKey LANGUAGE;
    public static final /* enum */ Mp4FieldKey LYRICIST;
    public static final /* enum */ Mp4FieldKey LYRICIST_MM3BETA;
    public static final /* enum */ Mp4FieldKey LYRICS;
    public static final /* enum */ Mp4FieldKey MEDIA;
    public static final /* enum */ Mp4FieldKey MIXER;
    public static final /* enum */ Mp4FieldKey MM_CUSTOM_1;
    public static final /* enum */ Mp4FieldKey MM_CUSTOM_2;
    public static final /* enum */ Mp4FieldKey MM_CUSTOM_3;
    public static final /* enum */ Mp4FieldKey MM_CUSTOM_4;
    public static final /* enum */ Mp4FieldKey MM_CUSTOM_5;
    public static final /* enum */ Mp4FieldKey MM_INVOLVED_PEOPLE;
    public static final /* enum */ Mp4FieldKey MM_OCCASION;
    public static final /* enum */ Mp4FieldKey MM_ORIGINAL_ALBUM_TITLE;
    public static final /* enum */ Mp4FieldKey MM_ORIGINAL_ARTIST;
    public static final /* enum */ Mp4FieldKey MM_ORIGINAL_LYRICIST;
    public static final /* enum */ Mp4FieldKey MM_ORIGINAL_YEAR;
    public static final /* enum */ Mp4FieldKey MM_PUBLISHER;
    public static final /* enum */ Mp4FieldKey MM_QUALITY;
    public static final /* enum */ Mp4FieldKey MM_TEMPO;
    public static final /* enum */ Mp4FieldKey MOOD;
    public static final /* enum */ Mp4FieldKey MOOD_ACOUSTIC;
    public static final /* enum */ Mp4FieldKey MOOD_AGGRESSIVE;
    public static final /* enum */ Mp4FieldKey MOOD_AROUSAL;
    public static final /* enum */ Mp4FieldKey MOOD_DANCEABILITY;
    public static final /* enum */ Mp4FieldKey MOOD_ELECTRONIC;
    public static final /* enum */ Mp4FieldKey MOOD_HAPPY;
    public static final /* enum */ Mp4FieldKey MOOD_INSTRUMENTAL;
    public static final /* enum */ Mp4FieldKey MOOD_MM3BETA;
    public static final /* enum */ Mp4FieldKey MOOD_PARTY;
    public static final /* enum */ Mp4FieldKey MOOD_RELAXED;
    public static final /* enum */ Mp4FieldKey MOOD_SAD;
    public static final /* enum */ Mp4FieldKey MOOD_VALENCE;
    public static final /* enum */ Mp4FieldKey MOVEMENT;
    public static final /* enum */ Mp4FieldKey MOVEMENT_NO;
    public static final /* enum */ Mp4FieldKey MOVEMENT_TOTAL;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_ALBUMARTISTID;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_ALBUMID;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_ALBUM_STATUS;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_ALBUM_TYPE;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_ARTISTID;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_DISCID;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_ORIGINALALBUMID;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_RELEASE_GROUPID;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_RELEASE_TRACKID;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_TRACKID;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_WORK;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_WORKID;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_WORK_COMPOSITION;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_WORK_COMPOSITION_ID;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_WORK_PART_LEVEL1;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_WORK_PART_LEVEL1_ID;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_WORK_PART_LEVEL1_TYPE;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_WORK_PART_LEVEL2;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_WORK_PART_LEVEL2_ID;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_WORK_PART_LEVEL2_TYPE;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_WORK_PART_LEVEL3;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_WORK_PART_LEVEL3_ID;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_WORK_PART_LEVEL3_TYPE;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_WORK_PART_LEVEL4;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_WORK_PART_LEVEL4_ID;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_WORK_PART_LEVEL4_TYPE;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_WORK_PART_LEVEL5;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_WORK_PART_LEVEL5_ID;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_WORK_PART_LEVEL5_TYPE;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_WORK_PART_LEVEL6;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_WORK_PART_LEVEL6_ID;
    public static final /* enum */ Mp4FieldKey MUSICBRAINZ_WORK_PART_LEVEL6_TYPE;
    public static final /* enum */ Mp4FieldKey MUSICIP_PUID;
    public static final /* enum */ Mp4FieldKey OCCASION;
    public static final /* enum */ Mp4FieldKey OPUS;
    public static final /* enum */ Mp4FieldKey ORCHESTRA;
    public static final /* enum */ Mp4FieldKey ORCHESTRA_SORT;
    public static final /* enum */ Mp4FieldKey ORIGINAL_ALBUM_TITLE;
    public static final /* enum */ Mp4FieldKey ORIGINAL_ARTIST;
    public static final /* enum */ Mp4FieldKey ORIGINAL_LYRICIST;
    public static final /* enum */ Mp4FieldKey PART;
    public static final /* enum */ Mp4FieldKey PART_NUMBER;
    public static final /* enum */ Mp4FieldKey PART_OF_GAPLESS_ALBUM;
    public static final /* enum */ Mp4FieldKey PART_TYPE;
    public static final /* enum */ Mp4FieldKey PERFORMER;
    public static final /* enum */ Mp4FieldKey PERFORMER_NAME;
    public static final /* enum */ Mp4FieldKey PERFORMER_NAME_SORT;
    public static final /* enum */ Mp4FieldKey PERIOD;
    public static final /* enum */ Mp4FieldKey PL_ID;
    public static final /* enum */ Mp4FieldKey PODCAST_KEYWORD;
    public static final /* enum */ Mp4FieldKey PODCAST_URL;
    public static final /* enum */ Mp4FieldKey PRODUCER;
    public static final /* enum */ Mp4FieldKey PURCHASE_DATE;
    public static final /* enum */ Mp4FieldKey QUALITY;
    public static final /* enum */ Mp4FieldKey RANKING;
    public static final /* enum */ Mp4FieldKey RATING;
    public static final /* enum */ Mp4FieldKey RELEASECOUNTRY;
    public static final /* enum */ Mp4FieldKey REMIXER;
    public static final /* enum */ Mp4FieldKey SCORE;
    public static final /* enum */ Mp4FieldKey SCRIPT;
    public static final /* enum */ Mp4FieldKey SF_ID;
    public static final /* enum */ Mp4FieldKey SHOW;
    public static final /* enum */ Mp4FieldKey SHOW_SORT;
    public static final /* enum */ Mp4FieldKey SINGLE_DISC_TRACK_NO;
    public static final /* enum */ Mp4FieldKey SUBTITLE;
    public static final /* enum */ Mp4FieldKey TAGS;
    public static final /* enum */ Mp4FieldKey TEMPO;
    public static final /* enum */ Mp4FieldKey TIMBRE;
    public static final /* enum */ Mp4FieldKey TITLE;
    public static final /* enum */ Mp4FieldKey TITLE_MOVEMENT;
    public static final /* enum */ Mp4FieldKey TITLE_SORT;
    public static final /* enum */ Mp4FieldKey TONALITY;
    public static final /* enum */ Mp4FieldKey TOOL;
    public static final /* enum */ Mp4FieldKey TRACK;
    public static final /* enum */ Mp4FieldKey TV_EPISODE;
    public static final /* enum */ Mp4FieldKey TV_EPISODE_NUMBER;
    public static final /* enum */ Mp4FieldKey TV_NETWORK;
    public static final /* enum */ Mp4FieldKey TV_SEASON;
    public static final /* enum */ Mp4FieldKey URL_DISCOGS_ARTIST_SITE;
    public static final /* enum */ Mp4FieldKey URL_DISCOGS_RELEASE_SITE;
    public static final /* enum */ Mp4FieldKey URL_LYRICS_SITE;
    public static final /* enum */ Mp4FieldKey URL_OFFICIAL_ARTIST_SITE;
    public static final /* enum */ Mp4FieldKey URL_OFFICIAL_RELEASE_SITE;
    public static final /* enum */ Mp4FieldKey URL_WIKIPEDIA_ARTIST_SITE;
    public static final /* enum */ Mp4FieldKey URL_WIKIPEDIA_RELEASE_SITE;
    public static final /* enum */ Mp4FieldKey WINAMP_PUBLISHER;
    public static final /* enum */ Mp4FieldKey WORK;
    public static final /* enum */ Mp4FieldKey WORK_TYPE;
    private int fieldLength;
    private String fieldName;
    private Mp4FieldType fieldType;
    private String identifier;
    private String issuer;
    private Mp4TagFieldSubType subclassType;
    private Tagger tagger;

    static {
        Mp4FieldKey mp4FieldKey;
        Mp4FieldKey mp4FieldKey2;
        Mp4FieldKey mp4FieldKey3;
        Mp4FieldKey mp4FieldKey4;
        Mp4FieldKey mp4FieldKey5;
        Mp4FieldKey mp4FieldKey6;
        Mp4FieldKey mp4FieldKey7;
        Mp4FieldKey mp4FieldKey8;
        Mp4FieldKey mp4FieldKey9;
        Mp4FieldKey mp4FieldKey10;
        Mp4FieldKey mp4FieldKey11;
        Mp4FieldKey mp4FieldKey12;
        Mp4FieldKey mp4FieldKey13;
        Mp4FieldKey mp4FieldKey14;
        Mp4FieldKey mp4FieldKey15;
        Mp4FieldKey mp4FieldKey16;
        Mp4FieldKey mp4FieldKey17;
        Mp4FieldKey mp4FieldKey18;
        Mp4FieldKey mp4FieldKey19;
        Mp4FieldKey mp4FieldKey20;
        Mp4FieldKey mp4FieldKey21;
        Mp4FieldKey mp4FieldKey22;
        Mp4FieldKey mp4FieldKey23;
        Mp4FieldKey mp4FieldKey24;
        Mp4FieldKey mp4FieldKey25;
        Mp4FieldKey mp4FieldKey26;
        Mp4FieldKey mp4FieldKey27;
        Mp4FieldKey mp4FieldKey28;
        Mp4FieldKey mp4FieldKey29;
        Mp4FieldKey mp4FieldKey30;
        Mp4FieldKey mp4FieldKey31;
        Mp4FieldKey mp4FieldKey32;
        Mp4FieldKey mp4FieldKey33;
        Mp4FieldKey mp4FieldKey34;
        Mp4FieldKey mp4FieldKey35;
        Mp4FieldKey mp4FieldKey36;
        Mp4FieldKey mp4FieldKey37;
        Mp4FieldKey mp4FieldKey38;
        Mp4FieldKey mp4FieldKey39;
        Mp4FieldKey mp4FieldKey40;
        Mp4FieldKey mp4FieldKey41;
        Mp4FieldKey mp4FieldKey42;
        Mp4FieldKey mp4FieldKey43;
        Mp4FieldKey mp4FieldKey44;
        Mp4FieldKey mp4FieldKey45;
        Mp4FieldKey mp4FieldKey46;
        Mp4FieldKey mp4FieldKey47;
        Mp4FieldKey mp4FieldKey48;
        Mp4FieldKey mp4FieldKey49;
        Mp4FieldKey mp4FieldKey50;
        Mp4FieldKey mp4FieldKey51;
        Mp4FieldKey mp4FieldKey52;
        Mp4FieldKey mp4FieldKey53;
        Mp4FieldKey mp4FieldKey54;
        Mp4FieldKey mp4FieldKey55;
        Mp4FieldKey mp4FieldKey56;
        Mp4FieldKey mp4FieldKey57;
        Mp4FieldKey mp4FieldKey58;
        Mp4FieldKey mp4FieldKey59;
        Mp4FieldKey mp4FieldKey60;
        Mp4FieldKey mp4FieldKey61;
        Mp4FieldKey mp4FieldKey62;
        Mp4FieldKey mp4FieldKey63;
        Mp4FieldKey mp4FieldKey64;
        Mp4FieldKey mp4FieldKey65;
        Mp4FieldKey mp4FieldKey66;
        Mp4FieldKey mp4FieldKey67;
        Mp4FieldKey mp4FieldKey68;
        Mp4FieldKey mp4FieldKey69;
        Mp4FieldKey mp4FieldKey70;
        Mp4FieldKey mp4FieldKey71;
        Mp4FieldKey mp4FieldKey72;
        Mp4FieldKey mp4FieldKey73;
        Mp4FieldKey mp4FieldKey74;
        Mp4FieldKey mp4FieldKey75;
        Mp4FieldKey mp4FieldKey76;
        Mp4FieldKey mp4FieldKey77;
        Mp4FieldKey mp4FieldKey78;
        Mp4FieldKey mp4FieldKey79;
        Mp4FieldKey mp4FieldKey80;
        Mp4FieldKey mp4FieldKey81;
        Mp4FieldKey mp4FieldKey82;
        Mp4FieldKey mp4FieldKey83;
        Mp4FieldKey mp4FieldKey84;
        Mp4FieldKey mp4FieldKey85;
        Mp4FieldKey mp4FieldKey86;
        Mp4FieldKey mp4FieldKey87;
        Mp4FieldKey mp4FieldKey88;
        Mp4FieldKey mp4FieldKey89;
        Mp4FieldKey mp4FieldKey90;
        Mp4FieldKey mp4FieldKey91;
        Mp4FieldKey mp4FieldKey92;
        Mp4FieldKey mp4FieldKey93;
        Mp4FieldKey mp4FieldKey94;
        Mp4FieldKey mp4FieldKey95;
        Mp4FieldKey mp4FieldKey96;
        Mp4FieldKey mp4FieldKey97;
        Mp4FieldKey mp4FieldKey98;
        Mp4FieldKey mp4FieldKey99;
        Mp4FieldKey mp4FieldKey100;
        Mp4FieldKey mp4FieldKey101;
        Mp4FieldKey mp4FieldKey102;
        Mp4FieldKey mp4FieldKey103;
        Mp4FieldKey mp4FieldKey104;
        Mp4FieldKey mp4FieldKey105;
        Mp4FieldKey mp4FieldKey106;
        Mp4FieldKey mp4FieldKey107;
        Mp4FieldKey mp4FieldKey108;
        Mp4FieldKey mp4FieldKey109;
        Mp4FieldKey mp4FieldKey110;
        Mp4FieldKey mp4FieldKey111;
        Mp4FieldKey mp4FieldKey112;
        Mp4FieldKey mp4FieldKey113;
        Mp4FieldKey mp4FieldKey114;
        Mp4FieldKey mp4FieldKey115;
        Mp4FieldKey mp4FieldKey116;
        Mp4FieldKey mp4FieldKey117;
        Mp4FieldKey mp4FieldKey118;
        Mp4FieldKey mp4FieldKey119;
        Mp4FieldKey mp4FieldKey120;
        Mp4FieldKey mp4FieldKey121;
        Mp4FieldKey mp4FieldKey122;
        Mp4FieldKey mp4FieldKey123;
        Mp4FieldKey mp4FieldKey124;
        Mp4FieldKey mp4FieldKey125;
        Mp4FieldKey mp4FieldKey126;
        Mp4FieldKey mp4FieldKey127;
        Mp4FieldKey mp4FieldKey128;
        Mp4FieldKey mp4FieldKey129;
        Mp4FieldKey mp4FieldKey130;
        Mp4FieldKey mp4FieldKey131;
        Mp4FieldKey mp4FieldKey132;
        Mp4FieldKey mp4FieldKey133;
        Mp4FieldKey mp4FieldKey134;
        Mp4FieldKey mp4FieldKey135;
        Mp4FieldKey mp4FieldKey136;
        Mp4FieldKey mp4FieldKey137;
        Mp4FieldKey mp4FieldKey138;
        Mp4FieldKey mp4FieldKey139;
        Mp4FieldKey mp4FieldKey140;
        Mp4FieldKey mp4FieldKey141;
        Mp4FieldKey mp4FieldKey142;
        Mp4FieldKey mp4FieldKey143;
        Mp4FieldKey mp4FieldKey144;
        Mp4FieldKey mp4FieldKey145;
        Mp4FieldKey mp4FieldKey146;
        Mp4FieldKey mp4FieldKey147;
        Mp4FieldKey mp4FieldKey148;
        Mp4FieldKey mp4FieldKey149;
        Mp4FieldKey mp4FieldKey150;
        Mp4FieldKey mp4FieldKey151;
        Mp4FieldKey mp4FieldKey152;
        Mp4FieldKey mp4FieldKey153;
        Mp4FieldKey mp4FieldKey154;
        Mp4FieldKey mp4FieldKey155;
        Mp4FieldKey mp4FieldKey156;
        Mp4FieldKey mp4FieldKey157;
        Mp4FieldKey mp4FieldKey158;
        Mp4FieldKey mp4FieldKey159;
        Mp4FieldKey mp4FieldKey160;
        Mp4FieldKey mp4FieldKey161;
        Mp4FieldKey mp4FieldKey162;
        Mp4FieldKey mp4FieldKey163;
        Mp4FieldKey mp4FieldKey164;
        Mp4FieldKey mp4FieldKey165;
        Mp4FieldKey mp4FieldKey166;
        Mp4FieldKey mp4FieldKey167;
        Mp4FieldKey mp4FieldKey168;
        Mp4FieldKey mp4FieldKey169;
        Mp4FieldKey mp4FieldKey170;
        Mp4FieldKey mp4FieldKey171;
        Mp4FieldKey mp4FieldKey172;
        Mp4FieldKey mp4FieldKey173;
        Mp4FieldKey mp4FieldKey174;
        Mp4FieldKey mp4FieldKey175;
        Mp4FieldKey mp4FieldKey176;
        Mp4FieldKey mp4FieldKey177;
        Mp4FieldKey mp4FieldKey178;
        Mp4FieldKey mp4FieldKey179;
        Mp4FieldKey mp4FieldKey180;
        Mp4FieldKey mp4FieldKey181;
        Mp4FieldKey mp4FieldKey182;
        Mp4FieldKey mp4FieldKey183;
        Mp4FieldKey mp4FieldKey184;
        Mp4FieldKey mp4FieldKey185;
        Mp4FieldKey mp4FieldKey186;
        Mp4FieldKey mp4FieldKey187;
        Mp4FieldKey mp4FieldKey188;
        Mp4FieldKey mp4FieldKey189;
        Mp4FieldKey mp4FieldKey190;
        Mp4FieldKey mp4FieldKey191;
        Mp4FieldKey mp4FieldKey192;
        Mp4FieldKey mp4FieldKey193;
        Mp4FieldKey mp4FieldKey194;
        Mp4FieldKey mp4FieldKey195;
        Mp4FieldKey mp4FieldKey196;
        Mp4FieldKey mp4FieldKey197;
        Mp4FieldKey mp4FieldKey198;
        Mp4FieldKey mp4FieldKey199;
        Mp4FieldKey mp4FieldKey200;
        Mp4FieldType mp4FieldType = Mp4FieldType.TEXT;
        Tagger tagger = Tagger.PICARD;
        ACOUSTID_FINGERPRINT = mp4FieldKey28 = new Mp4FieldKey("com.apple.iTunes", "Acoustid Fingerprint", mp4FieldType, tagger);
        ACOUSTID_FINGERPRINT_OLD = mp4FieldKey144 = new Mp4FieldKey("com.apple.iTunes", "AcoustId Fingerprint", mp4FieldType, tagger);
        ACOUSTID_ID = mp4FieldKey103 = new Mp4FieldKey("com.apple.iTunes", "Acoustid Id", mp4FieldType, tagger);
        Mp4TagFieldSubType mp4TagFieldSubType = Mp4TagFieldSubType.UNKNOWN;
        Mp4FieldType mp4FieldType2 = Mp4FieldType.INTEGER;
        AK_ID = mp4FieldKey13 = new Mp4FieldKey("akID", mp4TagFieldSubType, mp4FieldType2, 1);
        Mp4TagFieldSubType mp4TagFieldSubType2 = Mp4TagFieldSubType.TEXT;
        ALBUM = mp4FieldKey196 = new Mp4FieldKey("\u00a9alb", mp4TagFieldSubType2, mp4FieldType);
        ALBUM_ARTIST = mp4FieldKey64 = new Mp4FieldKey("aART", mp4TagFieldSubType2, mp4FieldType);
        ALBUM_ARTIST_SORT = mp4FieldKey53 = new Mp4FieldKey("soaa", mp4TagFieldSubType2, mp4FieldType);
        ALBUM_SORT = mp4FieldKey163 = new Mp4FieldKey("soal", mp4TagFieldSubType2, mp4FieldType);
        AP_ID = mp4FieldKey187 = new Mp4FieldKey("apID", mp4TagFieldSubType, mp4FieldType);
        ARRANGER = mp4FieldKey16 = new Mp4FieldKey("com.apple.iTunes", "ARRANGER", mp4FieldType, tagger);
        Tagger tagger2 = Tagger.JAIKOZ;
        ARRANGER_SORT = mp4FieldKey91 = new Mp4FieldKey("com.apple.iTunes", "ARRANGER_SORT", mp4FieldType, tagger2);
        ARTIST = mp4FieldKey38 = new Mp4FieldKey("\u00a9ART", mp4TagFieldSubType2, mp4FieldType);
        ARTISTS = mp4FieldKey184 = new Mp4FieldKey("com.apple.iTunes", "ARTISTS", mp4FieldType, tagger2);
        ARTISTS_SORT = mp4FieldKey188 = new Mp4FieldKey("com.apple.iTunes", "ARTISTS_SORT", mp4FieldType, tagger2);
        ALBUM_ARTISTS = mp4FieldKey15 = new Mp4FieldKey("com.apple.iTunes", "ALBUM_ARTISTS", mp4FieldType, tagger2);
        ALBUM_ARTISTS_SORT = mp4FieldKey197 = new Mp4FieldKey("com.apple.iTunes", "ALBUM_ARTISTS_SORT", mp4FieldType, tagger2);
        ARTIST_SORT = mp4FieldKey36 = new Mp4FieldKey("soar", mp4TagFieldSubType2, mp4FieldType);
        ARTWORK = mp4FieldKey52 = new Mp4FieldKey("covr", Mp4TagFieldSubType.ARTWORK, Mp4FieldType.COVERART_JPEG);
        ASIN = mp4FieldKey47 = new Mp4FieldKey("com.apple.iTunes", "ASIN", mp4FieldType, tagger);
        AT_ID = mp4FieldKey128 = new Mp4FieldKey("atID", mp4TagFieldSubType, mp4FieldType2, 4);
        BARCODE = mp4FieldKey111 = new Mp4FieldKey("com.apple.iTunes", "BARCODE", mp4FieldType, tagger);
        Mp4TagFieldSubType mp4TagFieldSubType3 = Mp4TagFieldSubType.BYTE;
        BPM = mp4FieldKey132 = new Mp4FieldKey("tmpo", mp4TagFieldSubType3, mp4FieldType2, 2);
        CATALOGNO = mp4FieldKey74 = new Mp4FieldKey("com.apple.iTunes", "CATALOGNUMBER", mp4FieldType, tagger);
        CATEGORY = mp4FieldKey168 = new Mp4FieldKey("catg", mp4TagFieldSubType2, mp4FieldType);
        CDDB_1 = mp4FieldKey50 = new Mp4FieldKey("com.apple.iTunes", "iTunes_CDDB_1", mp4FieldType);
        CDDB_IDS = mp4FieldKey72 = new Mp4FieldKey("com.apple.iTunes", "iTunes_CDDB_IDs", mp4FieldType);
        CDDB_TRACKNUMBER = mp4FieldKey97 = new Mp4FieldKey("com.apple.iTunes", "iTunes_CDDB_TrackNumber", mp4FieldType);
        CN_ID = mp4FieldKey109 = new Mp4FieldKey("cnID", mp4TagFieldSubType, mp4FieldType2, 4);
        CHOIR = mp4FieldKey191 = new Mp4FieldKey("com.apple.iTunes", "CHOR", mp4FieldType, tagger2);
        CHOIR_SORT = mp4FieldKey143 = new Mp4FieldKey("com.apple.iTunes", "CHOIR_SORT", mp4FieldType, tagger2);
        CLASSICAL_CATALOG = mp4FieldKey48 = new Mp4FieldKey("com.apple.iTunes", "CLASSICAL_CATALOG", mp4FieldType, tagger2);
        CLASSICAL_NICKNAME = mp4FieldKey73 = new Mp4FieldKey("com.apple.iTunes", "CLASSICAL_NICKNAME", mp4FieldType, tagger2);
        COMMENT = mp4FieldKey39 = new Mp4FieldKey("\u00a9cmt", mp4TagFieldSubType2, mp4FieldType);
        COMPILATION = mp4FieldKey102 = new Mp4FieldKey("cpil", mp4TagFieldSubType3, mp4FieldType2, 1);
        COMPOSER = mp4FieldKey121 = new Mp4FieldKey("\u00a9wrt", mp4TagFieldSubType2, mp4FieldType);
        COMPOSER_SORT = mp4FieldKey175 = new Mp4FieldKey("soco", mp4TagFieldSubType2, mp4FieldType);
        CONDUCTOR = mp4FieldKey156 = new Mp4FieldKey("com.apple.iTunes", "CONDUCTOR", mp4FieldType, tagger);
        Tagger tagger3 = Tagger.MEDIA_MONKEY;
        CONDUCTOR_MM3BETA = mp4FieldKey85 = new Mp4FieldKey("cond", mp4TagFieldSubType2, mp4FieldType, tagger3);
        CONDUCTOR_SORT = mp4FieldKey = new Mp4FieldKey("com.apple.iTunes", "CONDUCTOR_SORT", mp4FieldType, tagger2);
        CONTENT_TYPE = mp4FieldKey42 = new Mp4FieldKey("stik", mp4TagFieldSubType3, mp4FieldType2, 1);
        COPYRIGHT = mp4FieldKey190 = new Mp4FieldKey("cprt", mp4TagFieldSubType2, mp4FieldType);
        Mp4FieldType mp4FieldType3 = Mp4FieldType.TEXT;
        Tagger tagger4 = Tagger.PICARD;
        COUNTRY = mp4FieldKey18 = new Mp4FieldKey("com.apple.iTunes", "Country", mp4FieldType3, tagger4);
        CUSTOM_1 = mp4FieldKey2 = new Mp4FieldKey("cus1", mp4TagFieldSubType2, mp4FieldType3, tagger3);
        CUSTOM_2 = mp4FieldKey87 = new Mp4FieldKey("cus2", mp4TagFieldSubType2, mp4FieldType3, tagger3);
        CUSTOM_3 = mp4FieldKey56 = new Mp4FieldKey("cus3", mp4TagFieldSubType2, mp4FieldType3, tagger3);
        CUSTOM_4 = mp4FieldKey159 = new Mp4FieldKey("cus4", mp4TagFieldSubType2, mp4FieldType3, tagger3);
        CUSTOM_5 = mp4FieldKey194 = new Mp4FieldKey("cus5", mp4TagFieldSubType2, mp4FieldType3, tagger3);
        Mp4TagFieldSubType mp4TagFieldSubType4 = Mp4TagFieldSubType.TEXT;
        DAY = mp4FieldKey99 = new Mp4FieldKey("\u00a9day", mp4TagFieldSubType4, mp4FieldType3);
        DESCRIPTION = mp4FieldKey92 = new Mp4FieldKey("desc", mp4TagFieldSubType4, mp4FieldType3);
        Mp4TagFieldSubType mp4TagFieldSubType5 = Mp4TagFieldSubType.DISC_NO;
        Mp4FieldType mp4FieldType4 = Mp4FieldType.IMPLICIT;
        DISCNUMBER = mp4FieldKey60 = new Mp4FieldKey("disk", mp4TagFieldSubType5, mp4FieldType4);
        DISC_SUBTITLE = mp4FieldKey118 = new Mp4FieldKey("com.apple.iTunes", "DISCSUBTITLE", mp4FieldType3, tagger4);
        DJMIXER = mp4FieldKey193 = new Mp4FieldKey("com.apple.iTunes", "DJMIXER", mp4FieldType3, tagger4);
        ENCODER = mp4FieldKey94 = new Mp4FieldKey("\u00a9too", mp4TagFieldSubType4, mp4FieldType3);
        ENGINEER = mp4FieldKey119 = new Mp4FieldKey("com.apple.iTunes", "ENGINEER", mp4FieldType3, tagger4);
        Tagger tagger5 = Tagger.JAIKOZ;
        ENSEMBLE = mp4FieldKey49 = new Mp4FieldKey("com.apple.iTunes", "Ensemble", mp4FieldType3, tagger5);
        ENSEMBLE_SORT = mp4FieldKey181 = new Mp4FieldKey("com.apple.iTunes", "Ensemble Sort", mp4FieldType3, tagger5);
        EPISODE_GLOBAL_ID = mp4FieldKey108 = new Mp4FieldKey("egid", Mp4TagFieldSubType.NUMBER, mp4FieldType4);
        FBPM = mp4FieldKey104 = new Mp4FieldKey("com.apple.iTunes", "fBPM", mp4FieldType3, tagger5);
        GENRE = mp4FieldKey195 = new Mp4FieldKey("gnre", Mp4TagFieldSubType.GENRE, mp4FieldType4);
        GENRE_CUSTOM = mp4FieldKey172 = new Mp4FieldKey("\u00a9gen", mp4TagFieldSubType4, mp4FieldType3);
        GE_ID = mp4FieldKey46 = new Mp4FieldKey("geID", Mp4TagFieldSubType.UNKNOWN, Mp4FieldType.INTEGER, 4);
        GROUP = mp4FieldKey89 = new Mp4FieldKey("com.apple.iTunes", "GROUP", mp4FieldType3, tagger5);
        GROUPING = mp4FieldKey30 = new Mp4FieldKey("\u00a9grp", mp4TagFieldSubType4, mp4FieldType3);
        INSTRUMENT = mp4FieldKey26 = new Mp4FieldKey("com.apple.iTunes", "INSTRUMENT", mp4FieldType3, tagger5);
        INVOLVED_PEOPLE = mp4FieldKey192 = new Mp4FieldKey("peop", mp4TagFieldSubType4, mp4FieldType3, tagger3);
        ISRC = mp4FieldKey29 = new Mp4FieldKey("com.apple.iTunes", "ISRC", mp4FieldType3, tagger4);
        ISRC_MMBETA = mp4FieldKey200 = new Mp4FieldKey("isrc", mp4TagFieldSubType4, mp4FieldType3, tagger3);
        IS_CLASSICAL = mp4FieldKey170 = new Mp4FieldKey("com.apple.iTunes", "IS_CLASSICAL", mp4FieldType3, tagger5);
        IS_SOUNDTRACK = mp4FieldKey24 = new Mp4FieldKey("com.apple.iTunes", "IS_SOUNDTRACK", mp4FieldType3, tagger5);
        ITUNES_NORM = mp4FieldKey6 = new Mp4FieldKey("com.apple.iTunes", "iTunNORM", mp4FieldType3);
        ITUNES_SMPB = mp4FieldKey40 = new Mp4FieldKey("com.apple.iTunes", "iTunSMPB", mp4FieldType3);
        KEY = mp4FieldKey186 = new Mp4FieldKey("com.apple.iTunes", "initialkey", mp4FieldType3);
        KEYS = mp4FieldKey169 = new Mp4FieldKey("keys", mp4TagFieldSubType4, mp4FieldType3);
        KEYWORD = mp4FieldKey138 = new Mp4FieldKey("keyw", mp4TagFieldSubType4, mp4FieldType3);
        KEY_OLD = mp4FieldKey68 = new Mp4FieldKey("com.apple.iTunes", "KEY", mp4FieldType3, tagger5);
        LABEL = mp4FieldKey107 = new Mp4FieldKey("com.apple.iTunes", "LABEL", mp4FieldType3, tagger4);
        LANGUAGE = mp4FieldKey27 = new Mp4FieldKey("com.apple.iTunes", "LANGUAGE", mp4FieldType3, tagger5);
        LYRICIST = mp4FieldKey62 = new Mp4FieldKey("com.apple.iTunes", "LYRICIST", mp4FieldType3, tagger4);
        Tagger tagger6 = Tagger.MEDIA_MONKEY;
        LYRICIST_MM3BETA = mp4FieldKey180 = new Mp4FieldKey("lyrc", mp4TagFieldSubType4, mp4FieldType3, tagger6);
        LYRICS = mp4FieldKey189 = new Mp4FieldKey("\u00a9lyr", mp4TagFieldSubType4, mp4FieldType3);
        MEDIA = mp4FieldKey146 = new Mp4FieldKey("com.apple.iTunes", "MEDIA", mp4FieldType3, tagger4);
        Mp4FieldType mp4FieldType5 = Mp4FieldType.TEXT;
        Tagger tagger7 = Tagger.PICARD;
        MIXER = mp4FieldKey136 = new Mp4FieldKey("com.apple.iTunes", "MIXER", mp4FieldType5, tagger7);
        MM_CUSTOM_1 = mp4FieldKey147 = new Mp4FieldKey("com.apple.iTunes", "CUSTOM1", mp4FieldType5, tagger6);
        MM_CUSTOM_2 = mp4FieldKey110 = new Mp4FieldKey("com.apple.iTunes", "CUSTOM2", mp4FieldType5, tagger6);
        MM_CUSTOM_3 = mp4FieldKey179 = new Mp4FieldKey("com.apple.iTunes", "CUSTOM3", mp4FieldType5, tagger6);
        MM_CUSTOM_4 = mp4FieldKey59 = new Mp4FieldKey("com.apple.iTunes", "CUSTOM4", mp4FieldType5, tagger6);
        MM_CUSTOM_5 = mp4FieldKey113 = new Mp4FieldKey("com.apple.iTunes", "CUSTOM5", mp4FieldType5, tagger6);
        MM_INVOLVED_PEOPLE = mp4FieldKey22 = new Mp4FieldKey("com.apple.iTunes", "INVOLVED PEOPLE", mp4FieldType5, tagger6);
        MM_OCCASION = mp4FieldKey185 = new Mp4FieldKey("com.apple.iTunes", "OCCASION", mp4FieldType5, tagger6);
        MM_ORIGINAL_ALBUM_TITLE = mp4FieldKey61 = new Mp4FieldKey("com.apple.iTunes", "ORIGINAL ALBUM", mp4FieldType5, tagger6);
        MM_ORIGINAL_ARTIST = mp4FieldKey23 = new Mp4FieldKey("com.apple.iTunes", "ORIGINAL ARTIST", mp4FieldType5, tagger6);
        MM_ORIGINAL_LYRICIST = mp4FieldKey116 = new Mp4FieldKey("com.apple.iTunes", "ORIGINAL LYRICIST", mp4FieldType5, tagger6);
        MM_ORIGINAL_YEAR = mp4FieldKey174 = new Mp4FieldKey("com.apple.iTunes", "ORIGINAL YEAR", mp4FieldType5, tagger6);
        MM_PUBLISHER = mp4FieldKey25 = new Mp4FieldKey("com.apple.iTunes", "ORGANIZATION", mp4FieldType5, tagger6);
        MM_QUALITY = mp4FieldKey55 = new Mp4FieldKey("com.apple.iTunes", "QUALITY", mp4FieldType5, tagger6);
        MM_TEMPO = mp4FieldKey178 = new Mp4FieldKey("com.apple.iTunes", "TEMPO", mp4FieldType5, tagger6);
        MOOD = mp4FieldKey20 = new Mp4FieldKey("com.apple.iTunes", "MOOD", mp4FieldType5, tagger7);
        Tagger tagger8 = Tagger.JAIKOZ;
        MOOD_ACOUSTIC = mp4FieldKey57 = new Mp4FieldKey("com.apple.iTunes", "MOOD_ACOUSTIC", mp4FieldType5, tagger8);
        MOOD_AGGRESSIVE = mp4FieldKey183 = new Mp4FieldKey("com.apple.iTunes", "MOOD_AGGRESSIVE", mp4FieldType5, tagger8);
        MOOD_AROUSAL = mp4FieldKey114 = new Mp4FieldKey("com.apple.iTunes", "MOOD_AROUSAL", mp4FieldType5, tagger8);
        MOOD_DANCEABILITY = mp4FieldKey5 = new Mp4FieldKey("com.apple.iTunes", "MOOD_DANCEABILITY", mp4FieldType5, tagger8);
        MOOD_ELECTRONIC = mp4FieldKey120 = new Mp4FieldKey("com.apple.iTunes", "MOOD_ELECTRONIC", mp4FieldType5, tagger8);
        MOOD_HAPPY = mp4FieldKey117 = new Mp4FieldKey("com.apple.iTunes", "MOOD_HAPPY", mp4FieldType5, tagger8);
        MOOD_INSTRUMENTAL = mp4FieldKey21 = new Mp4FieldKey("com.apple.iTunes", "MOOD_INSTRUMENTAL", mp4FieldType5, tagger8);
        Mp4TagFieldSubType mp4TagFieldSubType6 = Mp4TagFieldSubType.TEXT;
        MOOD_MM3BETA = mp4FieldKey58 = new Mp4FieldKey("mood", mp4TagFieldSubType6, mp4FieldType5, tagger6);
        MOOD_PARTY = mp4FieldKey19 = new Mp4FieldKey("com.apple.iTunes", "MOOD_PARTY", mp4FieldType5, tagger8);
        MOOD_RELAXED = mp4FieldKey112 = new Mp4FieldKey("com.apple.iTunes", "MOOD_RELAXED", mp4FieldType5, tagger8);
        MOOD_SAD = mp4FieldKey177 = new Mp4FieldKey("com.apple.iTunes", "MOOD_SAD", mp4FieldType5, tagger8);
        MOOD_VALENCE = mp4FieldKey77 = new Mp4FieldKey("com.apple.iTunes", "MOOD_VALENCE", mp4FieldType5, tagger8);
        MOVEMENT = mp4FieldKey100 = new Mp4FieldKey("\u00a9mvn", mp4TagFieldSubType6, mp4FieldType5);
        Mp4TagFieldSubType mp4TagFieldSubType7 = Mp4TagFieldSubType.BYTE;
        Mp4FieldType mp4FieldType6 = Mp4FieldType.INTEGER;
        MOVEMENT_NO = mp4FieldKey115 = new Mp4FieldKey("\u00a9mvi", mp4TagFieldSubType7, mp4FieldType6, 1);
        MOVEMENT_TOTAL = mp4FieldKey54 = new Mp4FieldKey("\u00a9mvc", mp4TagFieldSubType7, mp4FieldType6, 1);
        MUSICBRAINZ_ALBUMARTISTID = mp4FieldKey176 = new Mp4FieldKey("com.apple.iTunes", "MusicBrainz Album Artist Id", mp4FieldType5, tagger7);
        MUSICBRAINZ_ALBUMID = mp4FieldKey125 = new Mp4FieldKey("com.apple.iTunes", "MusicBrainz Album Id", mp4FieldType5, tagger7);
        MUSICBRAINZ_ALBUM_STATUS = mp4FieldKey8 = new Mp4FieldKey("com.apple.iTunes", "MusicBrainz Album Status", mp4FieldType5, tagger7);
        MUSICBRAINZ_ALBUM_TYPE = mp4FieldKey123 = new Mp4FieldKey("com.apple.iTunes", "MusicBrainz Album Type", mp4FieldType5, tagger7);
        MUSICBRAINZ_ARTISTID = mp4FieldKey155 = new Mp4FieldKey("com.apple.iTunes", "MusicBrainz Artist Id", mp4FieldType5, tagger7);
        MUSICBRAINZ_DISCID = mp4FieldKey32 = new Mp4FieldKey("com.apple.iTunes", "MusicBrainz Disc Id", mp4FieldType5, tagger7);
        MUSICBRAINZ_ORIGINALALBUMID = mp4FieldKey106 = new Mp4FieldKey("com.apple.iTunes", "MusicBrainz Original Album Id", mp4FieldType5, tagger8);
        MUSICBRAINZ_RELEASE_GROUPID = mp4FieldKey71 = new Mp4FieldKey("com.apple.iTunes", "MusicBrainz Release Group Id", mp4FieldType5, tagger7);
        MUSICBRAINZ_RELEASE_TRACKID = mp4FieldKey4 = new Mp4FieldKey("com.apple.iTunes", "MusicBrainz Release Track Id", mp4FieldType5, tagger7);
        MUSICBRAINZ_TRACKID = mp4FieldKey70 = new Mp4FieldKey("com.apple.iTunes", "MusicBrainz Track Id", mp4FieldType5, tagger7);
        MUSICBRAINZ_WORK = mp4FieldKey158 = new Mp4FieldKey("com.apple.iTunes", "MUSICBRAINZ_WORK", mp4FieldType5, tagger8);
        MUSICBRAINZ_WORKID = mp4FieldKey81 = new Mp4FieldKey("com.apple.iTunes", "MusicBrainz Work Id", mp4FieldType5, tagger7);
        MUSICBRAINZ_WORK_COMPOSITION = mp4FieldKey96 = new Mp4FieldKey("com.apple.iTunes", "MUSICBRAINZ_WORK_COMPOSITION", mp4FieldType5, tagger8);
        MUSICBRAINZ_WORK_COMPOSITION_ID = mp4FieldKey76 = new Mp4FieldKey("com.apple.iTunes", "MUSICBRAINZ_WORK_COMPOSITION_ID", mp4FieldType5, tagger8);
        Mp4FieldType mp4FieldType7 = Mp4FieldType.TEXT;
        MUSICBRAINZ_WORK_PART_LEVEL1 = mp4FieldKey75 = new Mp4FieldKey("com.apple.iTunes", "MUSICBRAINZ_WORK_PART_LEVEL1", mp4FieldType7, tagger8);
        MUSICBRAINZ_WORK_PART_LEVEL1_ID = mp4FieldKey7 = new Mp4FieldKey("com.apple.iTunes", "MUSICBRAINZ_WORK_PART_LEVEL1_ID", mp4FieldType7, tagger8);
        MUSICBRAINZ_WORK_PART_LEVEL1_TYPE = mp4FieldKey173 = new Mp4FieldKey("com.apple.iTunes", "MUSICBRAINZ_WORK_PART_LEVEL1_TYPE", mp4FieldType7, tagger8);
        MUSICBRAINZ_WORK_PART_LEVEL2 = mp4FieldKey127 = new Mp4FieldKey("com.apple.iTunes", "MUSICBRAINZ_WORK_PART_LEVEL2", mp4FieldType7, tagger8);
        MUSICBRAINZ_WORK_PART_LEVEL2_ID = mp4FieldKey10 = new Mp4FieldKey("com.apple.iTunes", "MUSICBRAINZ_WORK_PART_LEVEL2_ID", mp4FieldType7, tagger8);
        MUSICBRAINZ_WORK_PART_LEVEL2_TYPE = mp4FieldKey131 = new Mp4FieldKey("com.apple.iTunes", "MUSICBRAINZ_WORK_PART_LEVEL2_TYPE", mp4FieldType7, tagger8);
        MUSICBRAINZ_WORK_PART_LEVEL3 = mp4FieldKey167 = new Mp4FieldKey("com.apple.iTunes", "MUSICBRAINZ_WORK_PART_LEVEL3", mp4FieldType7, tagger8);
        MUSICBRAINZ_WORK_PART_LEVEL3_ID = mp4FieldKey37 = new Mp4FieldKey("com.apple.iTunes", "MUSICBRAINZ_WORK_PART_LEVEL3_ID", mp4FieldType7, tagger8);
        MUSICBRAINZ_WORK_PART_LEVEL3_TYPE = mp4FieldKey95 = new Mp4FieldKey("com.apple.iTunes", "MUSICBRAINZ_WORK_PART_LEVEL3_TYPE", mp4FieldType7, tagger8);
        MUSICBRAINZ_WORK_PART_LEVEL4 = mp4FieldKey34 = new Mp4FieldKey("com.apple.iTunes", "MUSICBRAINZ_WORK_PART_LEVEL4", mp4FieldType7, tagger8);
        MUSICBRAINZ_WORK_PART_LEVEL4_ID = mp4FieldKey154 = new Mp4FieldKey("com.apple.iTunes", "MUSICBRAINZ_WORK_PART_LEVEL4_ID", mp4FieldType7, tagger8);
        MUSICBRAINZ_WORK_PART_LEVEL4_TYPE = mp4FieldKey122 = new Mp4FieldKey("com.apple.iTunes", "MUSICBRAINZ_WORK_PART_LEVEL4_TYPE", mp4FieldType7, tagger8);
        MUSICBRAINZ_WORK_PART_LEVEL5 = mp4FieldKey165 = new Mp4FieldKey("com.apple.iTunes", "MUSICBRAINZ_WORK_PART_LEVEL5", mp4FieldType7, tagger8);
        MUSICBRAINZ_WORK_PART_LEVEL5_ID = mp4FieldKey82 = new Mp4FieldKey("com.apple.iTunes", "MUSICBRAINZ_WORK_PART_LEVEL5_ID", mp4FieldType7, tagger8);
        MUSICBRAINZ_WORK_PART_LEVEL5_TYPE = mp4FieldKey105 = new Mp4FieldKey("com.apple.iTunes", "MUSICBRAINZ_WORK_PART_LEVEL5_TYPE", mp4FieldType7, tagger8);
        MUSICBRAINZ_WORK_PART_LEVEL6 = mp4FieldKey84 = new Mp4FieldKey("com.apple.iTunes", "MUSICBRAINZ_WORK_PART_LEVEL6", mp4FieldType7, tagger8);
        MUSICBRAINZ_WORK_PART_LEVEL6_ID = mp4FieldKey157 = new Mp4FieldKey("com.apple.iTunes", "MUSICBRAINZ_WORK_PART_LEVEL6_ID", mp4FieldType7, tagger8);
        Tagger tagger9 = Tagger.JAIKOZ;
        MUSICBRAINZ_WORK_PART_LEVEL6_TYPE = mp4FieldKey9 = new Mp4FieldKey("com.apple.iTunes", "MUSICBRAINZ_WORK_PART_LEVEL6_TYPE", mp4FieldType7, tagger9);
        Tagger tagger10 = Tagger.PICARD;
        MUSICIP_PUID = mp4FieldKey151 = new Mp4FieldKey("com.apple.iTunes", "MusicIP PUID", mp4FieldType7, tagger10);
        Tagger tagger11 = Tagger.MEDIA_MONKEY;
        OCCASION = mp4FieldKey129 = new Mp4FieldKey("occa", mp4TagFieldSubType6, mp4FieldType7, tagger11);
        OPUS = mp4FieldKey162 = new Mp4FieldKey("com.apple.iTunes", "OPUS", mp4FieldType7, tagger9);
        ORCHESTRA = mp4FieldKey35 = new Mp4FieldKey("com.apple.iTunes", "ORCHESTRA", mp4FieldType7, tagger10);
        ORCHESTRA_SORT = mp4FieldKey134 = new Mp4FieldKey("com.apple.iTunes", "ORCHESTRA_SORT", mp4FieldType7, tagger9);
        Mp4TagFieldSubType mp4TagFieldSubType8 = Mp4TagFieldSubType.TEXT;
        ORIGINAL_ALBUM_TITLE = mp4FieldKey41 = new Mp4FieldKey("otit", mp4TagFieldSubType8, mp4FieldType7, tagger11);
        ORIGINAL_ARTIST = mp4FieldKey135 = new Mp4FieldKey("oart", mp4TagFieldSubType8, mp4FieldType7, tagger11);
        ORIGINAL_LYRICIST = mp4FieldKey43 = new Mp4FieldKey("olyr", mp4TagFieldSubType8, mp4FieldType7, tagger11);
        PART = mp4FieldKey140 = new Mp4FieldKey("com.apple.iTunes", "PART", mp4FieldType7, tagger10);
        PART_NUMBER = mp4FieldKey139 = new Mp4FieldKey("com.apple.iTunes", "PARTNUMBER", mp4FieldType7, tagger9);
        Mp4TagFieldSubType mp4TagFieldSubType9 = Mp4TagFieldSubType.BYTE;
        Mp4FieldType mp4FieldType8 = Mp4FieldType.INTEGER;
        PART_OF_GAPLESS_ALBUM = mp4FieldKey63 = new Mp4FieldKey("pgap", mp4TagFieldSubType9, mp4FieldType8);
        PART_TYPE = mp4FieldKey3 = new Mp4FieldKey("com.apple.iTunes", "PART_TYPE", mp4FieldType7, tagger9);
        PERFORMER = mp4FieldKey67 = new Mp4FieldKey("com.apple.iTunes", "Performer", mp4FieldType7, tagger10);
        PERFORMER_NAME = mp4FieldKey148 = new Mp4FieldKey("com.apple.iTunes", "PERFORMER_NAME", mp4FieldType7, tagger9);
        PERFORMER_NAME_SORT = mp4FieldKey90 = new Mp4FieldKey("com.apple.iTunes", "PERFORMER_NAME_SORT", mp4FieldType7, tagger9);
        PERIOD = mp4FieldKey198 = new Mp4FieldKey("com.apple.iTunes", "PERIOD", mp4FieldType7, tagger9);
        Mp4TagFieldSubType mp4TagFieldSubType10 = Mp4TagFieldSubType.UNKNOWN;
        PL_ID = mp4FieldKey199 = new Mp4FieldKey("plID", mp4TagFieldSubType10, mp4FieldType8, 8);
        PODCAST_KEYWORD = mp4FieldKey137 = new Mp4FieldKey("keyw", mp4TagFieldSubType8, mp4FieldType7);
        Mp4TagFieldSubType mp4TagFieldSubType11 = Mp4TagFieldSubType.NUMBER;
        Mp4FieldType mp4FieldType9 = Mp4FieldType.IMPLICIT;
        PODCAST_URL = mp4FieldKey133 = new Mp4FieldKey("purl", mp4TagFieldSubType11, mp4FieldType9);
        PRODUCER = mp4FieldKey44 = new Mp4FieldKey("com.apple.iTunes", "PRODUCER", mp4FieldType7, tagger10);
        PURCHASE_DATE = mp4FieldKey141 = new Mp4FieldKey("purd", mp4TagFieldSubType8, mp4FieldType7);
        QUALITY = mp4FieldKey145 = new Mp4FieldKey("qual", mp4TagFieldSubType8, mp4FieldType7, tagger11);
        RANKING = mp4FieldKey45 = new Mp4FieldKey("com.apple.iTunes", "RANKING", mp4FieldType7, tagger9);
        RATING = mp4FieldKey142 = new Mp4FieldKey("rtng", mp4TagFieldSubType9, mp4FieldType8, 1);
        Mp4FieldType mp4FieldType10 = Mp4FieldType.TEXT;
        RELEASECOUNTRY = mp4FieldKey150 = new Mp4FieldKey("com.apple.iTunes", "MusicBrainz Album Release Country", mp4FieldType10, tagger10);
        REMIXER = mp4FieldKey78 = new Mp4FieldKey("com.apple.iTunes", "REMIXER", mp4FieldType10, tagger10);
        SCORE = mp4FieldKey98 = new Mp4FieldKey("rate", mp4TagFieldSubType8, mp4FieldType10, tagger11);
        SCRIPT = mp4FieldKey80 = new Mp4FieldKey("com.apple.iTunes", "SCRIPT", mp4FieldType10, tagger9);
        SF_ID = mp4FieldKey164 = new Mp4FieldKey("sfID", mp4TagFieldSubType10, mp4FieldType8, 4);
        SHOW = mp4FieldKey86 = new Mp4FieldKey("tvsh", mp4TagFieldSubType8, mp4FieldType10);
        SHOW_SORT = mp4FieldKey12 = new Mp4FieldKey("sosn", mp4TagFieldSubType8, mp4FieldType10);
        SINGLE_DISC_TRACK_NO = mp4FieldKey83 = new Mp4FieldKey("com.apple.iTunes", "SINGLE_DISC_TRACK_NO", mp4FieldType10, tagger9);
        SUBTITLE = mp4FieldKey161 = new Mp4FieldKey("com.apple.iTunes", "SUBTITLE", mp4FieldType10, tagger10);
        TAGS = mp4FieldKey65 = new Mp4FieldKey("com.apple.iTunes", "TAGS", mp4FieldType10, tagger9);
        TEMPO = mp4FieldKey160 = new Mp4FieldKey("empo", mp4TagFieldSubType8, mp4FieldType10, tagger11);
        TIMBRE = mp4FieldKey126 = new Mp4FieldKey("com.apple.iTunes", "TIMBRE_BRIGHTNESS", mp4FieldType10, tagger9);
        TITLE = mp4FieldKey14 = new Mp4FieldKey("\u00a9nam", mp4TagFieldSubType8, mp4FieldType10);
        TITLE_MOVEMENT = mp4FieldKey130 = new Mp4FieldKey("com.apple.iTunes", "TITLE_MOVEMENT", mp4FieldType10, tagger9);
        TITLE_SORT = mp4FieldKey166 = new Mp4FieldKey("sonm", mp4TagFieldSubType8, mp4FieldType10);
        TONALITY = mp4FieldKey33 = new Mp4FieldKey("com.apple.iTunes", "TONALITY", mp4FieldType10, tagger9);
        TOOL = mp4FieldKey101 = new Mp4FieldKey("tool", mp4TagFieldSubType9, mp4FieldType8, 4);
        TRACK = mp4FieldKey17 = new Mp4FieldKey("trkn", Mp4TagFieldSubType.TRACK_NO, mp4FieldType9);
        TV_EPISODE = mp4FieldKey171 = new Mp4FieldKey("tves", mp4TagFieldSubType9, mp4FieldType8, 1);
        TV_EPISODE_NUMBER = mp4FieldKey51 = new Mp4FieldKey("tven", mp4TagFieldSubType8, mp4FieldType10);
        TV_NETWORK = mp4FieldKey88 = new Mp4FieldKey("tvnn", mp4TagFieldSubType8, mp4FieldType10);
        TV_SEASON = mp4FieldKey153 = new Mp4FieldKey("tvsn", mp4TagFieldSubType9, mp4FieldType8, 1);
        Tagger tagger12 = Tagger.JAIKOZ;
        URL_DISCOGS_ARTIST_SITE = mp4FieldKey11 = new Mp4FieldKey("com.apple.iTunes", "URL_DISCOGS_ARTIST_SITE", mp4FieldType10, tagger12);
        URL_DISCOGS_RELEASE_SITE = mp4FieldKey79 = new Mp4FieldKey("com.apple.iTunes", "URL_DISCOGS_RELEASE_SITE", mp4FieldType10, tagger12);
        URL_LYRICS_SITE = mp4FieldKey149 = new Mp4FieldKey("com.apple.iTunes", "URL_LYRICS_SITE", mp4FieldType10, tagger12);
        URL_OFFICIAL_ARTIST_SITE = mp4FieldKey69 = new Mp4FieldKey("com.apple.iTunes", "URL_OFFICIAL_ARTIST_SITE", mp4FieldType10, tagger12);
        URL_OFFICIAL_RELEASE_SITE = mp4FieldKey93 = new Mp4FieldKey("com.apple.iTunes", "URL_OFFICIAL_RELEASE_SITE", mp4FieldType10, tagger12);
        URL_WIKIPEDIA_ARTIST_SITE = mp4FieldKey66 = new Mp4FieldKey("com.apple.iTunes", "URL_WIKIPEDIA_ARTIST_SITE", mp4FieldType10, tagger12);
        URL_WIKIPEDIA_RELEASE_SITE = mp4FieldKey182 = new Mp4FieldKey("com.apple.iTunes", "URL_WIKIPEDIA_RELEASE_SITE", mp4FieldType10, tagger12);
        WINAMP_PUBLISHER = mp4FieldKey124 = new Mp4FieldKey("com.nullsoft.winamp", "publisher", mp4FieldType10, Tagger.WINAMP);
        WORK = mp4FieldKey152 = new Mp4FieldKey("\u00a9wrk", Mp4TagFieldSubType.TEXT, mp4FieldType10);
        WORK_TYPE = mp4FieldKey31 = new Mp4FieldKey("com.apple.iTunes", "WORK_TYPE", mp4FieldType10, tagger12);
        Mp4FieldKey[] arrmp4FieldKey = new Mp4FieldKey[]{ACOUSTID_FINGERPRINT, ACOUSTID_FINGERPRINT_OLD, ACOUSTID_ID, AK_ID, ALBUM, ALBUM_ARTIST, ALBUM_ARTIST_SORT, ALBUM_SORT, AP_ID, ARRANGER, ARRANGER_SORT, ARTIST, ARTISTS, ARTISTS_SORT, ALBUM_ARTISTS, ALBUM_ARTISTS_SORT, ARTIST_SORT, ARTWORK, ASIN, AT_ID, BARCODE, BPM, CATALOGNO, CATEGORY, CDDB_1, CDDB_IDS, CDDB_TRACKNUMBER, CN_ID, CHOIR, CHOIR_SORT, CLASSICAL_CATALOG, CLASSICAL_NICKNAME, COMMENT, COMPILATION, COMPOSER, COMPOSER_SORT, CONDUCTOR, CONDUCTOR_MM3BETA, CONDUCTOR_SORT, CONTENT_TYPE, COPYRIGHT, COUNTRY, CUSTOM_1, CUSTOM_2, CUSTOM_3, CUSTOM_4, CUSTOM_5, DAY, DESCRIPTION, DISCNUMBER, DISC_SUBTITLE, DJMIXER, ENCODER, ENGINEER, ENSEMBLE, ENSEMBLE_SORT, EPISODE_GLOBAL_ID, FBPM, GENRE, GENRE_CUSTOM, GE_ID, GROUP, GROUPING, INSTRUMENT, INVOLVED_PEOPLE, ISRC, ISRC_MMBETA, IS_CLASSICAL, IS_SOUNDTRACK, ITUNES_NORM, ITUNES_SMPB, KEY, KEYS, KEYWORD, KEY_OLD, LABEL, LANGUAGE, LYRICIST, LYRICIST_MM3BETA, LYRICS, MEDIA, MIXER, MM_CUSTOM_1, MM_CUSTOM_2, MM_CUSTOM_3, MM_CUSTOM_4, MM_CUSTOM_5, MM_INVOLVED_PEOPLE, MM_OCCASION, MM_ORIGINAL_ALBUM_TITLE, MM_ORIGINAL_ARTIST, MM_ORIGINAL_LYRICIST, MM_ORIGINAL_YEAR, MM_PUBLISHER, MM_QUALITY, MM_TEMPO, MOOD, MOOD_ACOUSTIC, MOOD_AGGRESSIVE, MOOD_AROUSAL, MOOD_DANCEABILITY, MOOD_ELECTRONIC, MOOD_HAPPY, MOOD_INSTRUMENTAL, MOOD_MM3BETA, MOOD_PARTY, MOOD_RELAXED, MOOD_SAD, MOOD_VALENCE, MOVEMENT, MOVEMENT_NO, MOVEMENT_TOTAL, MUSICBRAINZ_ALBUMARTISTID, MUSICBRAINZ_ALBUMID, MUSICBRAINZ_ALBUM_STATUS, MUSICBRAINZ_ALBUM_TYPE, MUSICBRAINZ_ARTISTID, MUSICBRAINZ_DISCID, MUSICBRAINZ_ORIGINALALBUMID, MUSICBRAINZ_RELEASE_GROUPID, MUSICBRAINZ_RELEASE_TRACKID, MUSICBRAINZ_TRACKID, MUSICBRAINZ_WORK, MUSICBRAINZ_WORKID, MUSICBRAINZ_WORK_COMPOSITION, MUSICBRAINZ_WORK_COMPOSITION_ID, MUSICBRAINZ_WORK_PART_LEVEL1, MUSICBRAINZ_WORK_PART_LEVEL1_ID, MUSICBRAINZ_WORK_PART_LEVEL1_TYPE, MUSICBRAINZ_WORK_PART_LEVEL2, MUSICBRAINZ_WORK_PART_LEVEL2_ID, MUSICBRAINZ_WORK_PART_LEVEL2_TYPE, MUSICBRAINZ_WORK_PART_LEVEL3, MUSICBRAINZ_WORK_PART_LEVEL3_ID, MUSICBRAINZ_WORK_PART_LEVEL3_TYPE, MUSICBRAINZ_WORK_PART_LEVEL4, MUSICBRAINZ_WORK_PART_LEVEL4_ID, MUSICBRAINZ_WORK_PART_LEVEL4_TYPE, MUSICBRAINZ_WORK_PART_LEVEL5, MUSICBRAINZ_WORK_PART_LEVEL5_ID, MUSICBRAINZ_WORK_PART_LEVEL5_TYPE, MUSICBRAINZ_WORK_PART_LEVEL6, MUSICBRAINZ_WORK_PART_LEVEL6_ID, MUSICBRAINZ_WORK_PART_LEVEL6_TYPE, MUSICIP_PUID, OCCASION, OPUS, ORCHESTRA, ORCHESTRA_SORT, ORIGINAL_ALBUM_TITLE, ORIGINAL_ARTIST, ORIGINAL_LYRICIST, PART, PART_NUMBER, PART_OF_GAPLESS_ALBUM, PART_TYPE, PERFORMER, PERFORMER_NAME, PERFORMER_NAME_SORT, PERIOD, PL_ID, PODCAST_KEYWORD, PODCAST_URL, PRODUCER, PURCHASE_DATE, QUALITY, RANKING, RATING, RELEASECOUNTRY, REMIXER, SCORE, SCRIPT, SF_ID, SHOW, SHOW_SORT, SINGLE_DISC_TRACK_NO, SUBTITLE, TAGS, TEMPO, TIMBRE, TITLE, TITLE_MOVEMENT, TITLE_SORT, TONALITY, TOOL, TRACK, TV_EPISODE, TV_EPISODE_NUMBER, TV_NETWORK, TV_SEASON, URL_DISCOGS_ARTIST_SITE, URL_DISCOGS_RELEASE_SITE, URL_LYRICS_SITE, URL_OFFICIAL_ARTIST_SITE, URL_OFFICIAL_RELEASE_SITE, URL_WIKIPEDIA_ARTIST_SITE, URL_WIKIPEDIA_RELEASE_SITE, WINAMP_PUBLISHER, WORK, WORK_TYPE};
        $VALUES = arrmp4FieldKey;
    }

    private Mp4FieldKey(String string3, String string4, Mp4FieldType mp4FieldType) {
        this.issuer = string3;
        this.identifier = string4;
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("----:");
        stringBuilder.append(string3);
        stringBuilder.append(":");
        stringBuilder.append(string4);
        this.fieldName = stringBuilder.toString();
        this.subclassType = Mp4TagFieldSubType.REVERSE_DNS;
        this.fieldType = mp4FieldType;
    }

    private Mp4FieldKey(String string3, String string4, Mp4FieldType mp4FieldType, Tagger tagger) {
        this.issuer = string3;
        this.identifier = string4;
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("----:");
        stringBuilder.append(string3);
        stringBuilder.append(":");
        stringBuilder.append(string4);
        this.fieldName = stringBuilder.toString();
        this.subclassType = Mp4TagFieldSubType.REVERSE_DNS;
        this.fieldType = mp4FieldType;
        this.tagger = tagger;
    }

    private Mp4FieldKey(String string3, Mp4TagFieldSubType mp4TagFieldSubType, Mp4FieldType mp4FieldType) {
        this.fieldName = string3;
        this.subclassType = mp4TagFieldSubType;
        this.fieldType = mp4FieldType;
    }

    private Mp4FieldKey(String string3, Mp4TagFieldSubType mp4TagFieldSubType, Mp4FieldType mp4FieldType, int n3) {
        this.fieldName = string3;
        this.subclassType = mp4TagFieldSubType;
        this.fieldType = mp4FieldType;
        this.fieldLength = n3;
    }

    private Mp4FieldKey(String string3, Mp4TagFieldSubType mp4TagFieldSubType, Mp4FieldType mp4FieldType, Tagger tagger) {
        this.fieldName = string3;
        this.subclassType = mp4TagFieldSubType;
        this.fieldType = mp4FieldType;
        this.tagger = tagger;
    }

    public static Mp4FieldKey valueOf(String string2) {
        return (Mp4FieldKey)Enum.valueOf(Mp4FieldKey.class, (String)string2);
    }

    public static Mp4FieldKey[] values() {
        return (Mp4FieldKey[])$VALUES.clone();
    }

    public int getFieldLength() {
        return this.fieldLength;
    }

    public String getFieldName() {
        return this.fieldName;
    }

    public Mp4FieldType getFieldType() {
        return this.fieldType;
    }

    public String getIdentifier() {
        return this.identifier;
    }

    public String getIssuer() {
        return this.issuer;
    }

    public Mp4TagFieldSubType getSubClassFieldType() {
        return this.subclassType;
    }

    public Tagger getTagger() {
        Tagger tagger = this.tagger;
        if (tagger != null) {
            return tagger;
        }
        return Tagger.ITUNES;
    }

    public boolean isReverseDnsType() {
        return this.identifier.startsWith("----");
    }
}

