/*
 * Decompiled with CFR 0.0.
 * 
 * Could not load the following classes:
 *  java.lang.Object
 *  java.lang.String
 *  java.util.HashSet
 *  java.util.Set
 */
package org.jaudiotagger.tag.id3.valuepair;

import java.util.HashSet;
import java.util.Set;

public class MusicianCredits {
    private static Set<String> musicianCredits;

    static {
        HashSet hashSet;
        musicianCredits = hashSet = new HashSet();
        hashSet.add((Object)"12 string guitar");
        musicianCredits.add((Object)"17-string koto");
        musicianCredits.add((Object)"accompaniment");
        musicianCredits.add((Object)"accordina");
        musicianCredits.add((Object)"accordion");
        musicianCredits.add((Object)"acoustic");
        musicianCredits.add((Object)"additional");
        musicianCredits.add((Object)"aeolian harp");
        musicianCredits.add((Object)"afox\u00e9");
        musicianCredits.add((Object)"afuche / cabasa");
        musicianCredits.add((Object)"agog\u00f4");
        musicianCredits.add((Object)"ajaeng");
        musicianCredits.add((Object)"akete");
        musicianCredits.add((Object)"alfaia");
        musicianCredits.add((Object)"algozey");
        musicianCredits.add((Object)"alphorn");
        musicianCredits.add((Object)"alto");
        musicianCredits.add((Object)"amadinda");
        musicianCredits.add((Object)"ankle rattlers");
        musicianCredits.add((Object)"anvil");
        musicianCredits.add((Object)"appalachian dulcimer");
        musicianCredits.add((Object)"archlute");
        musicianCredits.add((Object)"archtop guitar");
        musicianCredits.add((Object)"arghul");
        musicianCredits.add((Object)"assistant");
        musicianCredits.add((Object)"associate");
        musicianCredits.add((Object)"atabaque");
        musicianCredits.add((Object)"atarigane");
        musicianCredits.add((Object)"autoharp");
        musicianCredits.add((Object)"background vocals");
        musicianCredits.add((Object)"baglama");
        musicianCredits.add((Object)"bagpipe");
        musicianCredits.add((Object)"band");
        musicianCredits.add((Object)"bajo sexto");
        musicianCredits.add((Object)"balafon");
        musicianCredits.add((Object)"balalaika");
        musicianCredits.add((Object)"baltic psalteries");
        musicianCredits.add((Object)"bamboo angklung");
        musicianCredits.add((Object)"bandone\u00f3n");
        musicianCredits.add((Object)"bandora");
        musicianCredits.add((Object)"bandura");
        musicianCredits.add((Object)"bandurria");
        musicianCredits.add((Object)"bangu");
        musicianCredits.add((Object)"banhu");
        musicianCredits.add((Object)"banjitar");
        musicianCredits.add((Object)"banjo");
        musicianCredits.add((Object)"bansuri");
        musicianCredits.add((Object)"baritone");
        musicianCredits.add((Object)"baroque");
        musicianCredits.add((Object)"barrel drum");
        musicianCredits.add((Object)"barrel organ");
        musicianCredits.add((Object)"baryton");
        musicianCredits.add((Object)"bass");
        musicianCredits.add((Object)"bat\u00e1 drum");
        musicianCredits.add((Object)"bawu");
        musicianCredits.add((Object)"bayan");
        musicianCredits.add((Object)"bazooka");
        musicianCredits.add((Object)"bellow-blown bagpipes");
        musicianCredits.add((Object)"bells");
        musicianCredits.add((Object)"bell tree");
        musicianCredits.add((Object)"bendir");
        musicianCredits.add((Object)"berimbau");
        musicianCredits.add((Object)"bicycle bell");
        musicianCredits.add((Object)"bin-sasara");
        musicianCredits.add((Object)"birch lur");
        musicianCredits.add((Object)"biwa");
        musicianCredits.add((Object)"boatswain's pipe");
        musicianCredits.add((Object)"bodhr\u00e1n");
        musicianCredits.add((Object)"body percussion");
        musicianCredits.add((Object)"bolon");
        musicianCredits.add((Object)"bombarde");
        musicianCredits.add((Object)"bones");
        musicianCredits.add((Object)"bongos");
        musicianCredits.add((Object)"bouzouki");
        musicianCredits.add((Object)"bowed piano");
        musicianCredits.add((Object)"bowed psaltery");
        musicianCredits.add((Object)"bowed string instruments");
        musicianCredits.add((Object)"brass");
        musicianCredits.add((Object)"bronze lur");
        musicianCredits.add((Object)"brushes");
        musicianCredits.add((Object)"bugle");
        musicianCredits.add((Object)"buisine");
        musicianCredits.add((Object)"buk");
        musicianCredits.add((Object)"bulbul tarang");
        musicianCredits.add((Object)"bullroarer");
        musicianCredits.add((Object)"button accordion");
        musicianCredits.add((Object)"buzuq");
        musicianCredits.add((Object)"caj\u00f3n");
        musicianCredits.add((Object)"calabash");
        musicianCredits.add((Object)"calliope");
        musicianCredits.add((Object)"cancelled");
        musicianCredits.add((Object)"carillon");
        musicianCredits.add((Object)"castanets");
        musicianCredits.add((Object)"cavaquinho");
        musicianCredits.add((Object)"caxixi");
        musicianCredits.add((Object)"celeste");
        musicianCredits.add((Object)"celesta");
        musicianCredits.add((Object)"cello");
        musicianCredits.add((Object)"cembalet");
        musicianCredits.add((Object)"\u00e7evgen");
        musicianCredits.add((Object)"chacha");
        musicianCredits.add((Object)"chainsaw");
        musicianCredits.add((Object)"chakhe");
        musicianCredits.add((Object)"chalumeau");
        musicianCredits.add((Object)"chamberlin");
        musicianCredits.add((Object)"chamber");
        musicianCredits.add((Object)"chande");
        musicianCredits.add((Object)"chanzy");
        musicianCredits.add((Object)"chap");
        musicianCredits.add((Object)"chapman stick");
        musicianCredits.add((Object)"charango");
        musicianCredits.add((Object)"chau gong");
        musicianCredits.add((Object)"chikuzen biwa");
        musicianCredits.add((Object)"chime bar");
        musicianCredits.add((Object)"chimes");
        musicianCredits.add((Object)"ching");
        musicianCredits.add((Object)"chitra veena");
        musicianCredits.add((Object)"choir");
        musicianCredits.add((Object)"chromatic button accordion");
        musicianCredits.add((Object)"chromatic harmonica");
        musicianCredits.add((Object)"citole");
        musicianCredits.add((Object)"cittern");
        musicianCredits.add((Object)"cizhonghu");
        musicianCredits.add((Object)"clarinet");
        musicianCredits.add((Object)"classical guitar");
        musicianCredits.add((Object)"classical kemen\u00e7e");
        musicianCredits.add((Object)"claves");
        musicianCredits.add((Object)"clavichord");
        musicianCredits.add((Object)"clavinet");
        musicianCredits.add((Object)"claviola");
        musicianCredits.add((Object)"co");
        musicianCredits.add((Object)"c\u00f2 ke");
        musicianCredits.add((Object)"concert flute");
        musicianCredits.add((Object)"concert harp");
        musicianCredits.add((Object)"concertina");
        musicianCredits.add((Object)"conch");
        musicianCredits.add((Object)"congas");
        musicianCredits.add((Object)"continuum");
        musicianCredits.add((Object)"contrabass clarinet");
        musicianCredits.add((Object)"contrabassoon");
        musicianCredits.add((Object)"contrabass recorder");
        musicianCredits.add((Object)"contrabass saxophone");
        musicianCredits.add((Object)"contralto vocals");
        musicianCredits.add((Object)"cornamuse");
        musicianCredits.add((Object)"cornet");
        musicianCredits.add((Object)"cornett");
        musicianCredits.add((Object)"countertenor vocals");
        musicianCredits.add((Object)"cover");
        musicianCredits.add((Object)"cowbell");
        musicianCredits.add((Object)"craviola");
        musicianCredits.add((Object)"cretan lyra");
        musicianCredits.add((Object)"cristal baschet");
        musicianCredits.add((Object)"crotales");
        musicianCredits.add((Object)"crumhorn");
        musicianCredits.add((Object)"crwth");
        musicianCredits.add((Object)"cuatro");
        musicianCredits.add((Object)"cu\u00edca");
        musicianCredits.add((Object)"c\u00fcmb\u00fc\u015f");
        musicianCredits.add((Object)"cylindrical drum");
        musicianCredits.add((Object)"cymbals");
        musicianCredits.add((Object)"cymbalum");
        musicianCredits.add((Object)"daegeum");
        musicianCredits.add((Object)"daf");
        musicianCredits.add((Object)"daire");
        musicianCredits.add((Object)"daluo");
        musicianCredits.add((Object)"\u0111\u00e0n b\u1ea7u");
        musicianCredits.add((Object)"\u0111\u00e0n nguy\u1ec7t");
        musicianCredits.add((Object)"\u0111\u00e0n nh\u1ecb");
        musicianCredits.add((Object)"\u0111\u00e0n tam");
        musicianCredits.add((Object)"\u0111\u00e0n tam th\u1eadp l\u1ee5c");
        musicianCredits.add((Object)"\u0111\u00e0n tranh");
        musicianCredits.add((Object)"\u0111\u00e0n t\u1ee9");
        musicianCredits.add((Object)"\u0111\u00e0n t\u1ee9 d\u00e2y");
        musicianCredits.add((Object)"\u0111\u00e0n t\u1ef3 b\u00e0");
        musicianCredits.add((Object)"darbuka");
        musicianCredits.add((Object)"daruan");
        musicianCredits.add((Object)"davul");
        musicianCredits.add((Object)"denis d'or");
        musicianCredits.add((Object)"descant recorder / soprano recorder");
        musicianCredits.add((Object)"dhol");
        musicianCredits.add((Object)"dholak");
        musicianCredits.add((Object)"diatonic accordion / melodeon");
        musicianCredits.add((Object)"diddley bow");
        musicianCredits.add((Object)"didgeridoo");
        musicianCredits.add((Object)"dilruba");
        musicianCredits.add((Object)"\u0111ing bu\u1ed1t");
        musicianCredits.add((Object)"\u0111ing n\u0103m");
        musicianCredits.add((Object)"ding tac ta");
        musicianCredits.add((Object)"disk drive");
        musicianCredits.add((Object)"diyingehu");
        musicianCredits.add((Object)"dizi");
        musicianCredits.add((Object)"djembe");
        musicianCredits.add((Object)"dobro");
        musicianCredits.add((Object)"dohol");
        musicianCredits.add((Object)"dolceola");
        musicianCredits.add((Object)"dombra");
        musicianCredits.add((Object)"domra");
        musicianCredits.add((Object)"donso ng\u0254ni");
        musicianCredits.add((Object)"doshpuluur");
        musicianCredits.add((Object)"double bass");
        musicianCredits.add((Object)"double reed");
        musicianCredits.add((Object)"doyra");
        musicianCredits.add((Object)"dramyin");
        musicianCredits.add((Object)"drum machine");
        musicianCredits.add((Object)"drums");
        musicianCredits.add((Object)"drumset");
        musicianCredits.add((Object)"dubreq stylophone");
        musicianCredits.add((Object)"duck call");
        musicianCredits.add((Object)"duct flute");
        musicianCredits.add((Object)"duduk");
        musicianCredits.add((Object)"dulce melos");
        musicianCredits.add((Object)"dulcian");
        musicianCredits.add((Object)"dulzaina");
        musicianCredits.add((Object)"dunun");
        musicianCredits.add((Object)"dutar");
        musicianCredits.add((Object)"duxianqin");
        musicianCredits.add((Object)"ebow");
        musicianCredits.add((Object)"effects");
        musicianCredits.add((Object)"e-flat clarinet");
        musicianCredits.add((Object)"ektara");
        musicianCredits.add((Object)"electric bass guitar");
        musicianCredits.add((Object)"electric cello");
        musicianCredits.add((Object)"electric fretless guitar");
        musicianCredits.add((Object)"electric grand piano");
        musicianCredits.add((Object)"electric guitar");
        musicianCredits.add((Object)"electric harp");
        musicianCredits.add((Object)"electric lap steel guitar");
        musicianCredits.add((Object)"electric piano");
        musicianCredits.add((Object)"electric sitar");
        musicianCredits.add((Object)"electric upright bass");
        musicianCredits.add((Object)"electric viola");
        musicianCredits.add((Object)"electric violin");
        musicianCredits.add((Object)"electronic drum set");
        musicianCredits.add((Object)"electronic instruments");
        musicianCredits.add((Object)"electronic organ");
        musicianCredits.add((Object)"electronic wind instrument");
        musicianCredits.add((Object)"emeritus");
        musicianCredits.add((Object)"end-blown flute");
        musicianCredits.add((Object)"english horn");
        musicianCredits.add((Object)"erhu");
        musicianCredits.add((Object)"esraj");
        musicianCredits.add((Object)"euphonium");
        musicianCredits.add((Object)"ewi");
        musicianCredits.add((Object)"executive");
        musicianCredits.add((Object)"farfisa");
        musicianCredits.add((Object)"fiddle");
        musicianCredits.add((Object)"fife");
        musicianCredits.add((Object)"finger cymbals");
        musicianCredits.add((Object)"finger snaps");
        musicianCredits.add((Object)"five-string banjo");
        musicianCredits.add((Object)"floppy disk drive");
        musicianCredits.add((Object)"flugelhorn");
        musicianCredits.add((Object)"flumpet");
        musicianCredits.add((Object)"flute");
        musicianCredits.add((Object)"fl\u00fbte d'amour");
        musicianCredits.add((Object)"folk harp");
        musicianCredits.add((Object)"foot percussion");
        musicianCredits.add((Object)"fortepiano");
        musicianCredits.add((Object)"four-string banjo");
        musicianCredits.add((Object)"fourth flute");
        musicianCredits.add((Object)"frame drum");
        musicianCredits.add((Object)"free reed");
        musicianCredits.add((Object)"french horn");
        musicianCredits.add((Object)"fretless bass");
        musicianCredits.add((Object)"friction drum");
        musicianCredits.add((Object)"friction idiophone");
        musicianCredits.add((Object)"frottoir");
        musicianCredits.add((Object)"fujara");
        musicianCredits.add((Object)"gadulka");
        musicianCredits.add((Object)"gamelan");
        musicianCredits.add((Object)"gankogui");
        musicianCredits.add((Object)"ganz\u00e1");
        musicianCredits.add((Object)"gaohu");
        musicianCredits.add((Object)"garifuna drum");
        musicianCredits.add((Object)"garklein recorder");
        musicianCredits.add((Object)"gayageum");
        musicianCredits.add((Object)"gehu");
        musicianCredits.add((Object)"geomungo");
        musicianCredits.add((Object)"german harp");
        musicianCredits.add((Object)"ghatam");
        musicianCredits.add((Object)"\u0123\u012bga");
        musicianCredits.add((Object)"gittern");
        musicianCredits.add((Object)"gizmo");
        musicianCredits.add((Object)"glass harmonica");
        musicianCredits.add((Object)"glass harp");
        musicianCredits.add((Object)"glockenspiel");
        musicianCredits.add((Object)"goblet drum");
        musicianCredits.add((Object)"gong");
        musicianCredits.add((Object)"gong bass drum");
        musicianCredits.add((Object)"gongs");
        musicianCredits.add((Object)"gralla");
        musicianCredits.add((Object)"gramorimba");
        musicianCredits.add((Object)"grand piano");
        musicianCredits.add((Object)"great bass recorder / c-bass recorder");
        musicianCredits.add((Object)"greek baglama");
        musicianCredits.add((Object)"guan");
        musicianCredits.add((Object)"gudok");
        musicianCredits.add((Object)"guest");
        musicianCredits.add((Object)"g\u00fciro");
        musicianCredits.add((Object)"guitalele");
        musicianCredits.add((Object)"guitar");
        musicianCredits.add((Object)"guitaret");
        musicianCredits.add((Object)"guitaret");
        musicianCredits.add((Object)"guitarr\u00f3n chileno");
        musicianCredits.add((Object)"guitarr\u00f3n mexicano");
        musicianCredits.add((Object)"guitars");
        musicianCredits.add((Object)"guitar synthesizer");
        musicianCredits.add((Object)"gumbri");
        musicianCredits.add((Object)"guqin");
        musicianCredits.add((Object)"gusli");
        musicianCredits.add((Object)"gut guitar");
        musicianCredits.add((Object)"guzheng");
        musicianCredits.add((Object)"haegeum");
        musicianCredits.add((Object)"hammered dulcimer");
        musicianCredits.add((Object)"hammond organ");
        musicianCredits.add((Object)"handbells");
        musicianCredits.add((Object)"handclaps");
        musicianCredits.add((Object)"hang");
        musicianCredits.add((Object)"hardart");
        musicianCredits.add((Object)"hard disk drive");
        musicianCredits.add((Object)"hardingfele");
        musicianCredits.add((Object)"harmonica");
        musicianCredits.add((Object)"harmonium");
        musicianCredits.add((Object)"harp");
        musicianCredits.add((Object)"harp guitar");
        musicianCredits.add((Object)"harpsichord");
        musicianCredits.add((Object)"hawaiian guitar");
        musicianCredits.add((Object)"heckelphone");
        musicianCredits.add((Object)"heike biwa");
        musicianCredits.add((Object)"helicon");
        musicianCredits.add((Object)"hichiriki");
        musicianCredits.add((Object)"hi-hat");
        musicianCredits.add((Object)"hm\u00f4ng flute");
        musicianCredits.add((Object)"horn");
        musicianCredits.add((Object)"hotchiku");
        musicianCredits.add((Object)"hourglass drum");
        musicianCredits.add((Object)"hulusi");
        musicianCredits.add((Object)"huqin");
        musicianCredits.add((Object)"hurdy gurdy");
        musicianCredits.add((Object)"idiophone");
        musicianCredits.add((Object)"igil");
        musicianCredits.add((Object)"indian bamboo flutes");
        musicianCredits.add((Object)"instrument");
        musicianCredits.add((Object)"instrumental");
        musicianCredits.add((Object)"irish bouzouki");
        musicianCredits.add((Object)"irish harp / cl\u00e0rsach");
        musicianCredits.add((Object)"janggu");
        musicianCredits.add((Object)"jew's harp");
        musicianCredits.add((Object)"jing");
        musicianCredits.add((Object)"jing'erhu");
        musicianCredits.add((Object)"jinghu");
        musicianCredits.add((Object)"jouhikko");
        musicianCredits.add((Object)"jug");
        musicianCredits.add((Object)"kamancheh");
        musicianCredits.add((Object)"kanjira");
        musicianCredits.add((Object)"kankl\u0117s");
        musicianCredits.add((Object)"kantele");
        musicianCredits.add((Object)"kanun");
        musicianCredits.add((Object)"kartal");
        musicianCredits.add((Object)"kaval");
        musicianCredits.add((Object)"kazoo");
        musicianCredits.add((Object)"kemen\u00e7e of the black sea");
        musicianCredits.add((Object)"kemenche");
        musicianCredits.add((Object)"k\u00e8n b\u1ea7u");
        musicianCredits.add((Object)"k\u00e8n l\u00e1");
        musicianCredits.add((Object)"keyboard");
        musicianCredits.add((Object)"keyboard bass");
        musicianCredits.add((Object)"keyed brass instruments");
        musicianCredits.add((Object)"keytar");
        musicianCredits.add((Object)"khene");
        musicianCredits.add((Object)"kh\u00e8n m\u00e8o");
        musicianCredits.add((Object)"khim");
        musicianCredits.add((Object)"khlui");
        musicianCredits.add((Object)"khong wong");
        musicianCredits.add((Object)"khong wong lek");
        musicianCredits.add((Object)"khong wong yai");
        musicianCredits.add((Object)"kinnor");
        musicianCredits.add((Object)"ki pah");
        musicianCredits.add((Object)"kithara");
        musicianCredits.add((Object)"kkwaenggwari");
        musicianCredits.add((Object)"klong khaek");
        musicianCredits.add((Object)"k'l\u00f4ng p\u00fat");
        musicianCredits.add((Object)"klong song na");
        musicianCredits.add((Object)"klong that");
        musicianCredits.add((Object)"klong yao");
        musicianCredits.add((Object)"k\u014dauau");
        musicianCredits.add((Object)"kokyu");
        musicianCredits.add((Object)"komuz");
        musicianCredits.add((Object)"kora");
        musicianCredits.add((Object)"kortholt");
        musicianCredits.add((Object)"k\u00f6s");
        musicianCredits.add((Object)"koto");
        musicianCredits.add((Object)"kotsuzumi");
        musicianCredits.add((Object)"krakebs");
        musicianCredits.add((Object)"krar");
        musicianCredits.add((Object)"kud\u00fcm");
        musicianCredits.add((Object)"lamellophone");
        musicianCredits.add((Object)"langeleik");
        musicianCredits.add((Object)"laouto");
        musicianCredits.add((Object)"lap steel guitar");
        musicianCredits.add((Object)"laser harp");
        musicianCredits.add((Object)"lasso d'amore");
        musicianCredits.add((Object)"launeddas");
        musicianCredits.add((Object)"lautenwerck");
        musicianCredits.add((Object)"lavta");
        musicianCredits.add((Object)"lead vocals");
        musicianCredits.add((Object)"limbe");
        musicianCredits.add((Object)"lirone");
        musicianCredits.add((Object)"lithophone");
        musicianCredits.add((Object)"liuqin");
        musicianCredits.add((Object)"live");
        musicianCredits.add((Object)"low whistle");
        musicianCredits.add((Object)"lute");
        musicianCredits.add((Object)"luth\u00e9al");
        musicianCredits.add((Object)"lyre");
        musicianCredits.add((Object)"lyricon");
        musicianCredits.add((Object)"madal");
        musicianCredits.add((Object)"maddale");
        musicianCredits.add((Object)"mandocello");
        musicianCredits.add((Object)"mandola");
        musicianCredits.add((Object)"mandolin");
        musicianCredits.add((Object)"mandolute");
        musicianCredits.add((Object)"maracas");
        musicianCredits.add((Object)"marimba");
        musicianCredits.add((Object)"marimba lumina");
        musicianCredits.add((Object)"mar\u00edmbula");
        musicianCredits.add((Object)"mark tree");
        musicianCredits.add((Object)"marxophone");
        musicianCredits.add((Object)"mbira");
        musicianCredits.add((Object)"medium");
        musicianCredits.add((Object)"medium 1");
        musicianCredits.add((Object)"medium 2");
        musicianCredits.add((Object)"medium 3");
        musicianCredits.add((Object)"medium 4");
        musicianCredits.add((Object)"medium 5");
        musicianCredits.add((Object)"medium 6");
        musicianCredits.add((Object)"medium 7");
        musicianCredits.add((Object)"medium 8");
        musicianCredits.add((Object)"medium 9");
        musicianCredits.add((Object)"medley");
        musicianCredits.add((Object)"mellophone");
        musicianCredits.add((Object)"mellotron");
        musicianCredits.add((Object)"melodica");
        musicianCredits.add((Object)"mendoza");
        musicianCredits.add((Object)"metal angklung");
        musicianCredits.add((Object)"metallophone");
        musicianCredits.add((Object)"mexican vihuela");
        musicianCredits.add((Object)"mezzo-soprano vocals");
        musicianCredits.add((Object)"minimoog");
        musicianCredits.add((Object)"minipiano");
        musicianCredits.add((Object)"minor");
        musicianCredits.add((Object)"mirliton");
        musicianCredits.add((Object)"moog");
        musicianCredits.add((Object)"morin khuur / matouqin");
        musicianCredits.add((Object)"morsing");
        musicianCredits.add((Object)"mouth organ");
        musicianCredits.add((Object)"mridangam");
        musicianCredits.add((Object)"mukkuri");
        musicianCredits.add((Object)"musette de cour");
        musicianCredits.add((Object)"musical bow");
        musicianCredits.add((Object)"musical box");
        musicianCredits.add((Object)"musical saw");
        musicianCredits.add((Object)"nabal");
        musicianCredits.add((Object)"nadaswaram");
        musicianCredits.add((Object)"nagadou-daiko");
        musicianCredits.add((Object)"nagak");
        musicianCredits.add((Object)"nai");
        musicianCredits.add((Object)"n\u00e3o b\u1ea1t / ch\u1eadp ch\u00f5a");
        musicianCredits.add((Object)"naobo");
        musicianCredits.add((Object)"natural brass instruments");
        musicianCredits.add((Object)"natural horn");
        musicianCredits.add((Object)"ney");
        musicianCredits.add((Object)"ng\u0254ni");
        musicianCredits.add((Object)"nguru");
        musicianCredits.add((Object)"nohkan");
        musicianCredits.add((Object)"northumbrian pipes");
        musicianCredits.add((Object)"nose flute");
        musicianCredits.add((Object)"nose whistle");
        musicianCredits.add((Object)"number");
        musicianCredits.add((Object)"nyatiti");
        musicianCredits.add((Object)"nyckelharpa");
        musicianCredits.add((Object)"nylon guitar");
        musicianCredits.add((Object)"oboe");
        musicianCredits.add((Object)"oboe da caccia");
        musicianCredits.add((Object)"oboe d'amore");
        musicianCredits.add((Object)"ocarina");
        musicianCredits.add((Object)"ocean drum");
        musicianCredits.add((Object)"octave mandolin");
        musicianCredits.add((Object)"oktawka");
        musicianCredits.add((Object)"omnichord");
        musicianCredits.add((Object)"ondes martenot");
        musicianCredits.add((Object)"ophicleide");
        musicianCredits.add((Object)"organ");
        musicianCredits.add((Object)"original");
        musicianCredits.add((Object)"orpharion");
        musicianCredits.add((Object)"other instruments");
        musicianCredits.add((Object)"other vocals");
        musicianCredits.add((Object)"\u014dtsuzumi");
        musicianCredits.add((Object)"oud");
        musicianCredits.add((Object)"pah\u016b pounamu");
        musicianCredits.add((Object)"pakhavaj");
        musicianCredits.add((Object)"pan flute");
        musicianCredits.add((Object)"pang gu ly hu hm\u00f4ng");
        musicianCredits.add((Object)"paraguayan harp");
        musicianCredits.add((Object)"parody");
        musicianCredits.add((Object)"partial");
        musicianCredits.add((Object)"p\u0101t\u0113");
        musicianCredits.add((Object)"pedal piano");
        musicianCredits.add((Object)"pedal steel guitar");
        musicianCredits.add((Object)"percussion");
        musicianCredits.add((Object)"ph\u00e1ch");
        musicianCredits.add((Object)"pi");
        musicianCredits.add((Object)"pianet");
        musicianCredits.add((Object)"piano");
        musicianCredits.add((Object)"piccolo");
        musicianCredits.add((Object)"pi nai");
        musicianCredits.add((Object)"pipa");
        musicianCredits.add((Object)"pipe organ");
        musicianCredits.add((Object)"piri");
        musicianCredits.add((Object)"p\u00ed thiu");
        musicianCredits.add((Object)"pkhachich");
        musicianCredits.add((Object)"plucked string instruments");
        musicianCredits.add((Object)"pocket trumpet");
        musicianCredits.add((Object)"poi awhiowhio");
        musicianCredits.add((Object)"portuguese guitar");
        musicianCredits.add((Object)"p\u014drutu");
        musicianCredits.add((Object)"post horn");
        musicianCredits.add((Object)"practice chanter");
        musicianCredits.add((Object)"prepared piano");
        musicianCredits.add((Object)"primero");
        musicianCredits.add((Object)"principal");
        musicianCredits.add((Object)"psaltery");
        musicianCredits.add((Object)"p\u016bkaea");
        musicianCredits.add((Object)"p\u016bmotomoto");
        musicianCredits.add((Object)"p\u016brerehua");
        musicianCredits.add((Object)"p\u016bt\u0101tara");
        musicianCredits.add((Object)"p\u016bt\u014drino");
        musicianCredits.add((Object)"qilaut");
        musicianCredits.add((Object)"quena");
        musicianCredits.add((Object)"quijada");
        musicianCredits.add((Object)"quinto");
        musicianCredits.add((Object)"rainstick");
        musicianCredits.add((Object)"rammana");
        musicianCredits.add((Object)"ranat ek");
        musicianCredits.add((Object)"ranat kaeo");
        musicianCredits.add((Object)"ranat thum");
        musicianCredits.add((Object)"ratchet");
        musicianCredits.add((Object)"rattle");
        musicianCredits.add((Object)"rauschpfeife");
        musicianCredits.add((Object)"ravanahatha");
        musicianCredits.add((Object)"reactable");
        musicianCredits.add((Object)"rebab");
        musicianCredits.add((Object)"rebec");
        musicianCredits.add((Object)"recorder");
        musicianCredits.add((Object)"reco-reco");
        musicianCredits.add((Object)"reed organ");
        musicianCredits.add((Object)"reeds");
        musicianCredits.add((Object)"rehu");
        musicianCredits.add((Object)"repinique");
        musicianCredits.add((Object)"resonator guitar");
        musicianCredits.add((Object)"rhodes piano");
        musicianCredits.add((Object)"rhythm sticks");
        musicianCredits.add((Object)"riq");
        musicianCredits.add((Object)"rondador");
        musicianCredits.add((Object)"rototom");
        musicianCredits.add((Object)"ruan");
        musicianCredits.add((Object)"rudra veena");
        musicianCredits.add((Object)"ryuteki");
        musicianCredits.add((Object)"sabar");
        musicianCredits.add((Object)"sackbut");
        musicianCredits.add((Object)"samba whistle");
        musicianCredits.add((Object)"sampler");
        musicianCredits.add((Object)"sanshin");
        musicianCredits.add((Object)"santoor");
        musicianCredits.add((Object)"santur");
        musicianCredits.add((Object)"sanxian");
        musicianCredits.add((Object)"s\u00e1o me\u00f2");
        musicianCredits.add((Object)"sa\u00f3 \u00f4i flute");
        musicianCredits.add((Object)"s\u00e1o tr\u00fac");
        musicianCredits.add((Object)"sapek clappers");
        musicianCredits.add((Object)"sarangi");
        musicianCredits.add((Object)"saraswati veena");
        musicianCredits.add((Object)"\u0161argija");
        musicianCredits.add((Object)"sarod");
        musicianCredits.add((Object)"saron");
        musicianCredits.add((Object)"sarrusophone");
        musicianCredits.add((Object)"satsuma biwa");
        musicianCredits.add((Object)"saw duang");
        musicianCredits.add((Object)"saw sam sai");
        musicianCredits.add((Object)"saw u");
        musicianCredits.add((Object)"sax");
        musicianCredits.add((Object)"saxophone");
        musicianCredits.add((Object)"saz");
        musicianCredits.add((Object)"schwyzer\u00f6rgeli");
        musicianCredits.add((Object)"scottish smallpipes");
        musicianCredits.add((Object)"segunda");
        musicianCredits.add((Object)"s\u00eanh ti\u1ec1n");
        musicianCredits.add((Object)"serpent");
        musicianCredits.add((Object)"setar");
        musicianCredits.add((Object)"shakers");
        musicianCredits.add((Object)"shakuhachi");
        musicianCredits.add((Object)"shamisen");
        musicianCredits.add((Object)"shawm");
        musicianCredits.add((Object)"shehnai");
        musicianCredits.add((Object)"shekere");
        musicianCredits.add((Object)"sheng");
        musicianCredits.add((Object)"shichepshin");
        musicianCredits.add((Object)"shime-daiko");
        musicianCredits.add((Object)"shinobue");
        musicianCredits.add((Object)"sho");
        musicianCredits.add((Object)"shofar");
        musicianCredits.add((Object)"shruti box");
        musicianCredits.add((Object)"shudraga");
        musicianCredits.add((Object)"siku");
        musicianCredits.add((Object)"singing bowl");
        musicianCredits.add((Object)"single reed");
        musicianCredits.add((Object)"sistrum");
        musicianCredits.add((Object)"sitar");
        musicianCredits.add((Object)"slide");
        musicianCredits.add((Object)"slit drum");
        musicianCredits.add((Object)"snare drum");
        musicianCredits.add((Object)"solo");
        musicianCredits.add((Object)"song loan");
        musicianCredits.add((Object)"sopilka");
        musicianCredits.add((Object)"sopranino");
        musicianCredits.add((Object)"soprano");
        musicianCredits.add((Object)"sousaphone");
        musicianCredits.add((Object)"spanish");
        musicianCredits.add((Object)"spil\u00e5pipa");
        musicianCredits.add((Object)"spinet");
        musicianCredits.add((Object)"spinettone");
        musicianCredits.add((Object)"spoken vocals");
        musicianCredits.add((Object)"spoons");
        musicianCredits.add((Object)"steel guitar");
        musicianCredits.add((Object)"steelpan");
        musicianCredits.add((Object)"steel-string guitar");
        musicianCredits.add((Object)"strings");
        musicianCredits.add((Object)"string quartet");
        musicianCredits.add((Object)"string ensemble");
        musicianCredits.add((Object)"stroh violin");
        musicianCredits.add((Object)"struck idiophone");
        musicianCredits.add((Object)"struck string instruments");
        musicianCredits.add((Object)"subcontrabass recorder");
        musicianCredits.add((Object)"suikinkutsu");
        musicianCredits.add((Object)"suka");
        musicianCredits.add((Object)"suling");
        musicianCredits.add((Object)"suona");
        musicianCredits.add((Object)"surdo");
        musicianCredits.add((Object)"swarmandal");
        musicianCredits.add((Object)"swedish bagpipes");
        musicianCredits.add((Object)"synclavier");
        musicianCredits.add((Object)"synthesizer");
        musicianCredits.add((Object)"syrinx");
        musicianCredits.add((Object)"tabla");
        musicianCredits.add((Object)"table steel guitar");
        musicianCredits.add((Object)"tack piano");
        musicianCredits.add((Object)"taepyeongso");
        musicianCredits.add((Object)"taiko");
        musicianCredits.add((Object)"taishogoto");
        musicianCredits.add((Object)"talharpa");
        musicianCredits.add((Object)"talkbox");
        musicianCredits.add((Object)"talking drum");
        musicianCredits.add((Object)"tamborim");
        musicianCredits.add((Object)"tambourine");
        musicianCredits.add((Object)"tambura");
        musicianCredits.add((Object)"tamburitza");
        musicianCredits.add((Object)"tanbou ka");
        musicianCredits.add((Object)"tanbur");
        musicianCredits.add((Object)"tangent piano");
        musicianCredits.add((Object)"taonga p\u016boro");
        musicianCredits.add((Object)"tap dancing");
        musicianCredits.add((Object)"tape");
        musicianCredits.add((Object)"taphon");
        musicianCredits.add((Object)"tar");
        musicianCredits.add((Object)"taragot");
        musicianCredits.add((Object)"tef");
        musicianCredits.add((Object)"teleharmonium");
        musicianCredits.add((Object)"temple blocks");
        musicianCredits.add((Object)"tenor");
        musicianCredits.add((Object)"thavil");
        musicianCredits.add((Object)"theatre organ");
        musicianCredits.add((Object)"theorbo");
        musicianCredits.add((Object)"theremin");
        musicianCredits.add((Object)"thon");
        musicianCredits.add((Object)"tibetan water drum");
        musicianCredits.add((Object)"ti bwa");
        musicianCredits.add((Object)"ti\u00eau");
        musicianCredits.add((Object)"timbales");
        musicianCredits.add((Object)"time");
        musicianCredits.add((Object)"timpani");
        musicianCredits.add((Object)"tin whistle");
        musicianCredits.add((Object)"tinya");
        musicianCredits.add((Object)"tiple");
        musicianCredits.add((Object)"tololoche");
        musicianCredits.add((Object)"tom-tom");
        musicianCredits.add((Object)"tonkori");
        musicianCredits.add((Object)"topshuur");
        musicianCredits.add((Object)"toy piano");
        musicianCredits.add((Object)"tr\u00e0m pl\u00e8");
        musicianCredits.add((Object)"tr\u1eafng j\u00e2u");
        musicianCredits.add((Object)"tr\u1eafng lu");
        musicianCredits.add((Object)"translated");
        musicianCredits.add((Object)"transliterated");
        musicianCredits.add((Object)"transverse flute");
        musicianCredits.add((Object)"treble");
        musicianCredits.add((Object)"tres");
        musicianCredits.add((Object)"triangle");
        musicianCredits.add((Object)"tromba marina");
        musicianCredits.add((Object)"trombone");
        musicianCredits.add((Object)"tromboon");
        musicianCredits.add((Object)"tr\u1ed1ng b\u00f4ng");
        musicianCredits.add((Object)"trumpet");
        musicianCredits.add((Object)"t'r\u01b0ng");
        musicianCredits.add((Object)"tuba");
        musicianCredits.add((Object)"tubax");
        musicianCredits.add((Object)"tubon");
        musicianCredits.add((Object)"tubular bells");
        musicianCredits.add((Object)"tumbi");
        musicianCredits.add((Object)"tuned percussion");
        musicianCredits.add((Object)"turkish baglama");
        musicianCredits.add((Object)"turntable(s)");
        musicianCredits.add((Object)"txalaparta");
        musicianCredits.add((Object)"typewriter");
        musicianCredits.add((Object)"tzoura");
        musicianCredits.add((Object)"udu");
        musicianCredits.add((Object)"uilleann pipes");
        musicianCredits.add((Object)"ukeke");
        musicianCredits.add((Object)"ukulele");
        musicianCredits.add((Object)"upright piano");
        musicianCredits.add((Object)"\u00fct\u0151gardon");
        musicianCredits.add((Object)"vacuum cleaner");
        musicianCredits.add((Object)"valiha");
        musicianCredits.add((Object)"valved brass instruments");
        musicianCredits.add((Object)"valve trombone");
        musicianCredits.add((Object)"venu");
        musicianCredits.add((Object)"vessel drum");
        musicianCredits.add((Object)"vessel flute");
        musicianCredits.add((Object)"vibraphone");
        musicianCredits.add((Object)"vibraslap");
        musicianCredits.add((Object)"vichitra veena");
        musicianCredits.add((Object)"vielle");
        musicianCredits.add((Object)"vienna horn");
        musicianCredits.add((Object)"vietnamese guitar");
        musicianCredits.add((Object)"viola");
        musicianCredits.add((Object)"violin");
        musicianCredits.add((Object)"violoncello piccolo");
        musicianCredits.add((Object)"violone");
        musicianCredits.add((Object)"violotta");
        musicianCredits.add((Object)"virginal");
        musicianCredits.add((Object)"vocal");
        musicianCredits.add((Object)"vocals");
        musicianCredits.add((Object)"vocoder");
        musicianCredits.add((Object)"voice synthesizer");
        musicianCredits.add((Object)"wagner tuba");
        musicianCredits.add((Object)"warr guitar");
        musicianCredits.add((Object)"washboard");
        musicianCredits.add((Object)"washtub bass");
        musicianCredits.add((Object)"waterphone");
        musicianCredits.add((Object)"wavedrum");
        musicianCredits.add((Object)"whip");
        musicianCredits.add((Object)"whistle");
        musicianCredits.add((Object)"willow flute");
        musicianCredits.add((Object)"wind chime");
        musicianCredits.add((Object)"wind instruments");
        musicianCredits.add((Object)"wire-strung harp");
        musicianCredits.add((Object)"wood block");
        musicianCredits.add((Object)"wooden fish");
        musicianCredits.add((Object)"woodwind");
        musicianCredits.add((Object)"wot");
        musicianCredits.add((Object)"wurlitzer electric piano");
        musicianCredits.add((Object)"xalam");
        musicianCredits.add((Object)"xaphoon");
        musicianCredits.add((Object)"xiao");
        musicianCredits.add((Object)"xiaoluo");
        musicianCredits.add((Object)"xun");
        musicianCredits.add((Object)"xylophone");
        musicianCredits.add((Object)"xylorimba");
        musicianCredits.add((Object)"yangqin");
        musicianCredits.add((Object)"yatga");
        musicianCredits.add((Object)"yayl\u0131 tanbur");
        musicianCredits.add((Object)"yehu");
        musicianCredits.add((Object)"yonggo");
        musicianCredits.add((Object)"yueqin");
        musicianCredits.add((Object)"zabumba");
        musicianCredits.add((Object)"\u017caf\u017cafa");
        musicianCredits.add((Object)"\u017caqq");
        musicianCredits.add((Object)"zarb");
        musicianCredits.add((Object)"zhaleika");
        musicianCredits.add((Object)"zhonghu");
        musicianCredits.add((Object)"zhongruan");
        musicianCredits.add((Object)"zill");
        musicianCredits.add((Object)"zither");
        musicianCredits.add((Object)"\u017cummara");
        musicianCredits.add((Object)"zurna");
    }

    public static boolean isKey(String string2) {
        for (String string3 : musicianCredits) {
            if (!string2.toLowerCase().trim().startsWith(string3)) continue;
            return true;
        }
        return false;
    }
}

